"""
External Curated Learning -- Security / Governance / Sandboxing
FRONT-EXTERNAL-CURATED-LEARNING-SECURITY-GOVERNANCE-SANDBOXING-01

This module is a CURATION DRY-RUN ONLY.
It does NOT ingest into semantic memory or FAISS.
It does NOT download full papers or repos.
It does NOT modify protected runtime files.
It does NOT test exploit code or change real security posture.

Purpose: Create a safe, attributable, technically relevant, cross-checked
source plan for Brain to learn security, governance, and sandboxing:
execution gates, RBAC, policy-as-code, audit logs, least privilege,
secrets management, sandboxed execution, supply-chain security,
rollback, approvals, tool governance, prompt-injection defense,
safe autonomy, and production-grade governance.
"""

from pathlib import Path
import json


FRONT_ID = "FRONT-EXTERNAL-CURATED-LEARNING-SECURITY-GOVERNANCE-SANDBOXING-01"


def front_id() -> str:
    return FRONT_ID


def learning_domain() -> dict:
    return {
        "id": "security_governance_sandboxing",
        "display_name": "Security / Governance / Sandboxing",
        "description": (
            "How to secure agent systems, enforce governance, manage risk, "
            "sandbox execution, protect secrets, audit behavior, and maintain "
            "safe autonomy levels without compromising operational integrity."
        ),
        "macro_order": 4,
        "target_brain_capabilities": [
            "define safe autonomy levels",
            "define permission model",
            "design execution gates",
            "design tool allowlist / denylist",
            "design filesystem sandbox",
            "design network egress restrictions",
            "protect secrets and .env",
            "preserve audit logs",
            "preserve immutable evidence",
            "evaluate policy compliance",
            "prevent chain-of-thought leakage",
            "prevent private data leakage",
            "detect prompt injection",
            "design human approval gates",
            "design rollback / recovery",
            "manage dependency trust",
            "prepare financial action governance",
            "decide promote / reject / rollback under risk",
        ],
    }


def canonical_taxonomy() -> list[dict]:
    """22 required categories covering security/governance landscape."""
    return [
        {"id": "least_privilege", "name": "Least Privilege", "description": "Granting only the minimum permissions necessary for each operation."},
        {"id": "role_based_access_control", "name": "Role-Based Access Control", "description": "Permission model based on defined roles and responsibilities."},
        {"id": "policy_as_code", "name": "Policy-as-Code", "description": "Expressing governance rules as versioned, testable code."},
        {"id": "execution_gates", "name": "Execution Gates", "description": "Checkpoints that must pass before an action is allowed to execute."},
        {"id": "sandboxed_code_execution", "name": "Sandboxed Code Execution", "description": "Running untrusted or agent-generated code in isolated environments."},
        {"id": "filesystem_boundaries", "name": "Filesystem Boundaries", "description": "Restricting file system access to authorized paths and operations."},
        {"id": "network_egress_control", "name": "Network Egress Control", "description": "Controlling and monitoring outbound network connections."},
        {"id": "secrets_management", "name": "Secrets Management", "description": "Secure handling, storage, and rotation of credentials and API keys."},
        {"id": "audit_logging", "name": "Audit Logging", "description": "Recording all significant actions for accountability and forensics."},
        {"id": "immutable_evidence_logs", "name": "Immutable Evidence Logs", "description": "Tamper-proof records of decisions, approvals, and executions."},
        {"id": "supply_chain_security", "name": "Supply-Chain Security", "description": "Securing dependencies, builds, and artifact provenance."},
        {"id": "dependency_trust", "name": "Dependency Trust", "description": "Verifying and monitoring third-party libraries and components."},
        {"id": "prompt_injection_defense", "name": "Prompt Injection Defense", "description": "Protecting against adversarial inputs that override system instructions."},
        {"id": "tool_use_governance", "name": "Tool-Use Governance", "description": "Enforcing rules on which tools can be invoked, when, and with what parameters."},
        {"id": "human_approval_gates", "name": "Human Approval Gates", "description": "Requiring explicit human authorization for high-risk actions."},
        {"id": "rollback_recovery", "name": "Rollback / Recovery", "description": "Procedures to revert changes and restore safe state after failures."},
        {"id": "incident_response", "name": "Incident Response", "description": "Structured process for detecting, containing, and recovering from security incidents."},
        {"id": "safe_autonomy_levels", "name": "Safe Autonomy Levels", "description": "Graduated permissions that increase only with verified competence."},
        {"id": "privacy_governance", "name": "Privacy Governance", "description": "Ensuring personal and sensitive data is handled according to policy."},
        {"id": "local_first_governance", "name": "Local-First Governance", "description": "Governance that does not depend on external cloud or third-party control."},
        {"id": "chain_of_thought_non_disclosure", "name": "Chain-of-Thought Non-Disclosure", "description": "Preventing internal reasoning from leaking to users or logs."},
        {"id": "financial_action_governance", "name": "Financial-Action Governance", "description": "Specialized controls for trading, transfers, and financial decisions."},
    ]


def source_acceptance_criteria() -> dict:
    return {
        "description": "A source is accepted only if it is safe, attributable, technically relevant, and cross-checkable.",
        "minimum_conditions": [
            "Clear attribution (authors, org, or maintainers)",
            "Publicly reachable URL or repo",
            "Technical depth exceeds marketing/hype",
            "License allows metadata/summary reference",
            "Relevance to at least one taxonomy category",
            "Not contradicted by a more authoritative source",
            "No critical risk flagged by safety rubric",
        ],
        "accept_threshold": {"score_min": 58, "no_critical_risks": True},
        "hold_threshold": {"score_range": [42, 57], "metadata_incomplete_ok": True},
        "decision_rule": "Accept if score >= 58 and no critical risks; hold if 42-57 or incomplete; reject if < 42 or any critical risk.",
    }


def source_rejection_criteria() -> dict:
    return {
        "description": "Automatic rejection conditions regardless of popularity.",
        "critical_risks": [
            "Private or access-restricted content",
            "No identifiable attribution",
            "Illegal or copyright-violating distribution",
            "Offensive security content without defensive framing",
            "Exploit/malware code emphasis",
            "Source requires copying full copyrighted text to be useful",
            "Privacy-invasive architecture with no safeguards",
            "Unverifiable security claims",
            "Abandoned and directly contradicted by newer official source",
        ],
        "score_reject_threshold": 42,
    }


def source_safety_scoring_rubric() -> dict:
    """
    18 dimensions scored 0-5.
    Max possible = 90.
    Accept >= 58, Hold 42-57, Reject < 42.
    """
    return {
        "dimensions": {
            "attribution_quality": "Can the source be clearly attributed to known authors, orgs, or maintainers?",
            "primary_source_quality": "Is this a primary source (standard, official repo, official docs) rather than repackaged blog?",
            "technical_depth": "Does the source contain concrete security architecture, controls, or implementation details?",
            "implementation_relevance": "Can the ideas be implemented without vendor-specific proprietary infrastructure?",
            "governance_method_clarity": "Are governance rules, policies, and enforcement mechanisms clearly defined?",
            "sandboxing_method_clarity": "Are isolation boundaries, resource limits, and escape prevention clearly described?",
            "reproducibility": "Are there reproducible steps, examples, or tests?",
            "license_clarity": "Is the license clearly stated and compatible with metadata reference?",
            "maintenance_status": "Is the repo/docs actively maintained, or at least archived with clear status?",
            "test_or_example_presence": "Does the source include runnable examples, tests, or demos?",
            "copyright_safety": "Can we reference it at metadata/summary level without copyright risk?",
            "relevance_to_brain": "Does it map directly to a Brain governance capability target?",
            "risk_of_hype_or_marketing": "Is the content free of exaggerated marketing claims? (5 = very safe, 0 = pure hype)",
            "risk_of_obsolescence": "Is the source likely to remain relevant for 12+ months?",
            "risk_of_vendor_lock_in": "Does the approach require a specific vendor/cloud service? (5 = vendor-neutral, 0 = full lock-in)",
            "risk_of_security_misuse": "Could the source be misused for offensive/exploitative purposes? (5 = purely defensive, 0 = primarily offensive)",
            "risk_of_privacy_leakage": "Does the design risk leaking private/sensitive data? (5 = very safe, 0 = high risk)",
            "risk_of_unverifiable_claims": "Are core claims supported by evidence, code, or reproducible results?",
        },
        "scale": "0-5 per dimension",
        "max_possible": 90,
        "thresholds": {
            "accept": {"min_score": 58, "condition": "no_critical_risks"},
            "hold": {"min_score": 42, "max_score": 57},
            "reject": {"max_score": 41},
        },
    }


def source_contrast_scoring_rubric() -> dict:
    return {
        "description": "Each candidate source must be contrasted against at least two sources of different types when possible.",
        "contrast_types": [
            "security framework vs official docs",
            "sandboxing docs vs policy-as-code docs",
            "supply-chain framework vs dependency scanning tool docs",
            "prompt-injection paper vs tool governance framework",
            "RBAC docs vs execution gate implementation pattern",
            "incident response framework vs rollback/recovery runbook pattern",
        ],
        "per_source_fields": [
            "confirms",
            "contradicts",
            "complements",
            "unresolved_questions",
            "confidence_level",
        ],
        "confidence_levels": ["low", "medium", "high"],
    }


def brain_governance_capability_map() -> list[dict]:
    """Map sources to concrete Brain governance capabilities."""
    return [
        {"capability_id": "define_safe_autonomy", "name": "Define Safe Autonomy Levels", "description": "Graduated permissions that increase only with verified competence.", "relevant_taxonomy": ["safe_autonomy_levels", "human_approval_gates"], "example_sources": ["nist_ai_rmf", "anthropic_responsible_scaling"]},
        {"capability_id": "define_permission_model", "name": "Define Permission Model", "description": "Role-based or attribute-based access control for agent actions.", "relevant_taxonomy": ["role_based_access_control", "least_privilege"], "example_sources": ["nist_csf", "opa_docs"]},
        {"capability_id": "design_execution_gates", "name": "Design Execution Gates", "description": "Checkpoints that must pass before an action executes.", "relevant_taxonomy": ["execution_gates", "tool_use_governance"], "example_sources": ["owasp_llm_top10", "google_saif"]},
        {"capability_id": "design_tool_allowlist", "name": "Design Tool Allowlist / Denylist", "description": "Explicit enumeration of permitted and forbidden tools.", "relevant_taxonomy": ["tool_use_governance", "least_privilege"], "example_sources": ["owasp_llm_top10", "mitre_atlas"]},
        {"capability_id": "design_filesystem_sandbox", "name": "Design Filesystem Sandbox", "description": "Restricting file system access to authorized paths.", "relevant_taxonomy": ["filesystem_boundaries", "sandboxed_code_execution"], "example_sources": ["gvisor_docs", "firecracker_docs"]},
        {"capability_id": "design_network_egress", "name": "Design Network Egress Restrictions", "description": "Controlling outbound connections from agent execution.", "relevant_taxonomy": ["network_egress_control", "sandboxed_code_execution"], "example_sources": ["gvisor_docs", "docker_security_docs"]},
        {"capability_id": "protect_secrets", "name": "Protect Secrets and .env", "description": "Secure handling of credentials, keys, and sensitive configuration.", "relevant_taxonomy": ["secrets_management", "privacy_governance"], "example_sources": ["nist_csf", "openssf_scorecard"]},
        {"capability_id": "preserve_audit_logs", "name": "Preserve Audit Logs", "description": "Recording all significant actions for accountability.", "relevant_taxonomy": ["audit_logging", "immutable_evidence_logs"], "example_sources": ["nist_ai_rmf", "microsoft_responsible_ai"]},
        {"capability_id": "preserve_evidence", "name": "Preserve Immutable Evidence", "description": "Tamper-proof records of decisions and executions.", "relevant_taxonomy": ["immutable_evidence_logs", "audit_logging"], "example_sources": ["slsa_framework", "sigstore_docs"]},
        {"capability_id": "evaluate_policy_compliance", "name": "Evaluate Policy Compliance", "description": "Automated checking of behavior against declared policies.", "relevant_taxonomy": ["policy_as_code", "execution_gates"], "example_sources": ["opa_docs", "owasp_llm_top10"]},
        {"capability_id": "prevent_cot_leakage", "name": "Prevent Chain-of-Thought Leakage", "description": "Ensuring internal reasoning is not exposed externally.", "relevant_taxonomy": ["chain_of_thought_non_disclosure", "privacy_governance"], "example_sources": ["prompt_injection_paper", "anthropic_constitutional_ai"]},
        {"capability_id": "prevent_data_leakage", "name": "Prevent Private Data Leakage", "description": "Stopping sensitive information from being logged or transmitted.", "relevant_taxonomy": ["privacy_governance", "secrets_management"], "example_sources": ["microsoft_presidio", "nist_ai_rmf"]},
        {"capability_id": "detect_prompt_injection", "name": "Detect Prompt Injection", "description": "Identifying adversarial inputs that attempt to override instructions.", "relevant_taxonomy": ["prompt_injection_defense", "tool_use_governance"], "example_sources": ["prompt_injection_paper", "owasp_llm_top10"]},
        {"capability_id": "design_human_approval", "name": "Design Human Approval Gates", "description": "Requiring explicit authorization for high-risk actions.", "relevant_taxonomy": ["human_approval_gates", "safe_autonomy_levels"], "example_sources": ["nist_ai_rmf", "microsoft_responsible_ai"]},
        {"capability_id": "design_rollback", "name": "Design Rollback / Recovery", "description": "Procedures to revert changes and restore safe state.", "relevant_taxonomy": ["rollback_recovery", "incident_response"], "example_sources": ["slsa_framework", "docker_security_docs"]},
        {"capability_id": "manage_dependencies", "name": "Manage Dependency Trust", "description": "Verifying and monitoring third-party libraries.", "relevant_taxonomy": ["dependency_trust", "supply_chain_security"], "example_sources": ["openssf_scorecard", "pip_audit_repo"]},
        {"capability_id": "prepare_financial_governance", "name": "Prepare Financial Action Governance", "description": "Specialized controls for trading and financial decisions.", "relevant_taxonomy": ["financial_action_governance", "human_approval_gates"], "example_sources": ["nist_ai_rmf", "policy_as_code"]},
        {"capability_id": "decide_under_risk", "name": "Decide Promote / Reject / Rollback Under Risk", "description": "Making go/no-go decisions when security or governance risks are present.", "relevant_taxonomy": ["rollback_recovery", "safe_autonomy_levels"], "example_sources": ["nist_csf", "incident_response_framework"]},
    ]


def _seed_standards_papers() -> list[dict]:
    """Standards and research paper candidates (metadata only)."""
    return [
        {
            "source_id": "nist_ai_rmf",
            "source_group": "standard",
            "title": "NIST AI Risk Management Framework (AI RMF 1.0)",
            "authors_or_org": "National Institute of Standards and Technology (NIST)",
            "year_or_first_release": "2023",
            "url": "https://www.nist.gov/itl/ai-risk-management-framework",
            "repo_url": None,
            "docs_url": "https://www.nist.gov/itl/ai-risk-management-framework",
            "license": "Public Domain (U.S. Government)",
            "maintenance_status": "active",
            "source_type": "government_standard",
            "taxonomy_tags": ["safe_autonomy_levels", "human_approval_gates", "audit_logging", "privacy_governance", "financial_action_governance"],
            "expected_learning_value": "Comprehensive framework for managing AI risks across governance, mapping, measurement, and management.",
            "specific_brain_capability_target": "define_safe_autonomy",
            "cross_check_targets": ["nist_csf", "microsoft_responsible_ai"],
            "safety_score_estimate": 65,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Authoritative U.S. government standard. Widely adopted. No vendor bias.",
        },
        {
            "source_id": "nist_csf",
            "source_group": "standard",
            "title": "NIST Cybersecurity Framework (CSF 2.0)",
            "authors_or_org": "National Institute of Standards and Technology (NIST)",
            "year_or_first_release": "2024",
            "url": "https://www.nist.gov/cyberframework",
            "repo_url": None,
            "docs_url": "https://www.nist.gov/cyberframework",
            "license": "Public Domain (U.S. Government)",
            "maintenance_status": "active",
            "source_type": "government_standard",
            "taxonomy_tags": ["least_privilege", "role_based_access_control", "secrets_management", "audit_logging", "incident_response"],
            "expected_learning_value": "Foundational cybersecurity framework: identify, protect, detect, respond, recover.",
            "specific_brain_capability_target": "define_permission_model",
            "cross_check_targets": ["nist_ai_rmf", "owasp_llm_top10"],
            "safety_score_estimate": 66,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Updated to CSF 2.0 in 2024. Added governance function. Vendor-neutral.",
        },
        {
            "source_id": "owasp_llm_top10",
            "source_group": "standard",
            "title": "OWASP Top 10 for Large Language Model Applications",
            "authors_or_org": "OWASP Foundation",
            "year_or_first_release": "2023",
            "url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
            "repo_url": "https://github.com/OWASP/www-project-top-10-for-large-language-model-applications",
            "docs_url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
            "license": "CC-BY-SA-4.0",
            "maintenance_status": "active",
            "source_type": "security_standard",
            "taxonomy_tags": ["prompt_injection_defense", "tool_use_governance", "execution_gates", "secrets_management", "chain_of_thought_non_disclosure"],
            "expected_learning_value": "Top risks specific to LLM applications: prompt injection, insecure output handling, training data poisoning, etc.",
            "specific_brain_capability_target": "detect_prompt_injection",
            "cross_check_targets": ["mitre_atlas", "google_saif"],
            "safety_score_estimate": 62,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Community-driven. Very relevant to Brain's LLM-based architecture. Active updates.",
        },
        {
            "source_id": "mitre_atlas",
            "source_group": "standard",
            "title": "MITRE ATLAS -- Adversarial Threat Landscape for Artificial-Intelligence Systems",
            "authors_or_org": "MITRE Corporation",
            "year_or_first_release": "2023",
            "url": "https://atlas.mitre.org/",
            "repo_url": None,
            "docs_url": "https://atlas.mitre.org/",
            "license": "Public Domain (MITRE)",
            "maintenance_status": "active",
            "source_type": "threat_framework",
            "taxonomy_tags": ["prompt_injection_defense", "tool_use_governance", "incident_response", "supply_chain_security"],
            "expected_learning_value": "Tactics and techniques for AI system attacks, mapped to MITRE ATT&CK style framework.",
            "specific_brain_capability_target": "detect_prompt_injection",
            "cross_check_targets": ["owasp_llm_top10", "nist_ai_rmf"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Defensive-focused threat intelligence. No offensive exploitation emphasis.",
        },
        {
            "source_id": "google_saif",
            "source_group": "standard",
            "title": "Google SAIF -- Secure AI Framework",
            "authors_or_org": "Google",
            "year_or_first_release": "2023",
            "url": "https://saif.google/",
            "repo_url": None,
            "docs_url": "https://saif.google/",
            "license": "Proprietary (public reference)",
            "maintenance_status": "active",
            "source_type": "security_framework",
            "taxonomy_tags": ["supply_chain_security", "privacy_governance", "sandboxed_code_execution", "execution_gates"],
            "expected_learning_value": "Google's framework for securing AI systems: expand strong security foundations, extend detection, automate defenses.",
            "specific_brain_capability_target": "design_execution_gates",
            "cross_check_targets": ["nist_ai_rmf", "owasp_llm_top10"],
            "safety_score_estimate": 58,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "medium",
            "notes": "Google-specific but principles are generalizable. Some Google Cloud coupling.",
        },
        {
            "source_id": "microsoft_responsible_ai",
            "source_group": "standard",
            "title": "Microsoft Responsible AI Standard / AI Red Team",
            "authors_or_org": "Microsoft",
            "year_or_first_release": "2022",
            "url": "https://www.microsoft.com/en-us/ai/responsible-ai",
            "repo_url": None,
            "docs_url": "https://www.microsoft.com/en-us/ai/responsible-ai",
            "license": "Proprietary (public reference)",
            "maintenance_status": "active",
            "source_type": "governance_framework",
            "taxonomy_tags": ["human_approval_gates", "audit_logging", "privacy_governance", "safe_autonomy_levels"],
            "expected_learning_value": "Microsoft's governance framework for fairness, reliability, safety, privacy, security, inclusiveness, transparency.",
            "specific_brain_capability_target": "design_human_approval",
            "cross_check_targets": ["nist_ai_rmf", "anthropic_responsible_scaling"],
            "safety_score_estimate": 59,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "medium",
            "notes": "Good governance principles. Some Microsoft-specific tooling references.",
        },
        {
            "source_id": "anthropic_responsible_scaling",
            "source_group": "standard",
            "title": "Anthropic Responsible Scaling Policy",
            "authors_or_org": "Anthropic",
            "year_or_first_release": "2023",
            "url": "https://www.anthropic.com/responsible-scaling",
            "repo_url": None,
            "docs_url": "https://www.anthropic.com/responsible-scaling",
            "license": "Proprietary (public reference)",
            "maintenance_status": "active",
            "source_type": "governance_framework",
            "taxonomy_tags": ["safe_autonomy_levels", "human_approval_gates", "execution_gates", "financial_action_governance"],
            "expected_learning_value": "Safety levels and capabilities that trigger increased security measures as models become more capable.",
            "specific_brain_capability_target": "define_safe_autonomy",
            "cross_check_targets": ["nist_ai_rmf", "microsoft_responsible_ai"],
            "safety_score_estimate": 60,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "medium",
            "notes": "Influential in AI safety community. Good for graduated autonomy concepts.",
        },
        {
            "source_id": "anthropic_constitutional_ai",
            "source_group": "paper",
            "title": "Constitutional AI: Harmlessness from AI Feedback",
            "authors_or_org": "Bai et al. / Anthropic",
            "year_or_first_release": "2022",
            "url": "https://arxiv.org/abs/2212.08073",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "research_paper",
            "taxonomy_tags": ["chain_of_thought_non_disclosure", "privacy_governance", "safe_autonomy_levels"],
            "expected_learning_value": "Self-critique and revision based on constitutional principles to reduce harmful outputs.",
            "specific_brain_capability_target": "prevent_cot_leakage",
            "cross_check_targets": ["prompt_injection_paper", "owasp_llm_top10"],
            "safety_score_estimate": 58,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Conceptual framework for self-governance. Practical implementation varies.",
        },
        {
            "source_id": "prompt_injection_paper",
            "source_group": "paper",
            "title": "Not What You've Signed Up For: Compromising Real-World LLM-Integrated Applications with Indirect Prompt Injection",
            "authors_or_org": "Greshake et al. / CISPA / others",
            "year_or_first_release": "2023",
            "url": "https://arxiv.org/abs/2302.12173",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "security_research_paper",
            "taxonomy_tags": ["prompt_injection_defense", "tool_use_governance", "chain_of_thought_non_disclosure"],
            "expected_learning_value": "Demonstrates how adversarial data in retrieval sources can hijack LLM behavior.",
            "specific_brain_capability_target": "detect_prompt_injection",
            "cross_check_targets": ["owasp_llm_top10", "mitre_atlas"],
            "safety_score_estimate": 59,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Critical for Brain's RAG-based architecture. Defensive framing; no exploit code.",
        },
        {
            "source_id": "slsa_framework",
            "source_group": "standard",
            "title": "SLSA -- Supply-chain Levels for Software Artifacts",
            "authors_or_org": "OpenSSF / Google / others",
            "year_or_first_release": "2021",
            "url": "https://slsa.dev/",
            "repo_url": "https://github.com/slsa-framework/slsa",
            "docs_url": "https://slsa.dev/spec/v1.0/",
            "license": "CC-BY-4.0",
            "maintenance_status": "active",
            "source_type": "security_framework",
            "taxonomy_tags": ["supply_chain_security", "immutable_evidence_logs", "rollback_recovery"],
            "expected_learning_value": "Four-level framework for gradually improving software supply-chain security.",
            "specific_brain_capability_target": "preserve_evidence",
            "cross_check_targets": ["sigstore_docs", "openssf_scorecard"],
            "safety_score_estimate": 62,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open standard. Vendor-neutral. Good for artifact provenance and rollback trust.",
        },
    ]


def _seed_repos_frameworks() -> list[dict]:
    """GitHub repos and framework docs candidates."""
    return [
        {
            "source_id": "opa_docs",
            "source_group": "framework",
            "title": "Open Policy Agent (OPA) -- Policy-Based Control for Cloud-Native Environments",
            "authors_or_org": "Open Policy Agent / CNCF",
            "year_or_first_release": "2016",
            "url": "https://www.openpolicyagent.org/",
            "repo_url": "https://github.com/open-policy-agent/opa",
            "docs_url": "https://www.openpolicyagent.org/docs/latest/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "policy_engine_framework",
            "taxonomy_tags": ["policy_as_code", "execution_gates", "role_based_access_control"],
            "expected_learning_value": "Declarative policy language (Rego) for enforcing fine-grained authorization across services.",
            "specific_brain_capability_target": "evaluate_policy_compliance",
            "cross_check_targets": ["nist_csf", "owasp_llm_top10"],
            "safety_score_estimate": 64,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "CNCF project. Very active. Good for policy-as-code implementation in Brain's execution gates.",
        },
        {
            "source_id": "gvisor_docs",
            "source_group": "framework",
            "title": "gVisor -- Application Kernel for Sandboxing",
            "authors_or_org": "Google",
            "year_or_first_release": "2018",
            "url": "https://gvisor.dev/",
            "repo_url": "https://github.com/google/gvisor",
            "docs_url": "https://gvisor.dev/docs/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "sandboxing_framework",
            "taxonomy_tags": ["sandboxed_code_execution", "filesystem_boundaries", "network_egress_control"],
            "expected_learning_value": "Userspace kernel that intercepts and limits system calls to provide container isolation.",
            "specific_brain_capability_target": "design_filesystem_sandbox",
            "cross_check_targets": ["firecracker_docs", "docker_security_docs"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source. Good for understanding sandboxing architecture. Used in Google Cloud Run.",
        },
        {
            "source_id": "firecracker_docs",
            "source_group": "framework",
            "title": "Firecracker -- Secure and Fast MicroVMs for Serverless Computing",
            "authors_or_org": "AWS / Amazon",
            "year_or_first_release": "2018",
            "url": "https://firecracker-microvm.github.io/",
            "repo_url": "https://github.com/firecracker-microvm/firecracker",
            "docs_url": "https://firecracker-microvm.github.io/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "sandboxing_framework",
            "taxonomy_tags": ["sandboxed_code_execution", "filesystem_boundaries", "network_egress_control"],
            "expected_learning_value": "MicroVM-based isolation with minimal overhead, used in AWS Lambda and Fargate.",
            "specific_brain_capability_target": "design_filesystem_sandbox",
            "cross_check_targets": ["gvisor_docs", "docker_security_docs"],
            "safety_score_estimate": 62,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source despite AWS origin. Good for understanding VM-level sandboxing.",
        },
        {
            "source_id": "docker_security_docs",
            "source_group": "docs",
            "title": "Docker Security Documentation",
            "authors_or_org": "Docker Inc",
            "year_or_first_release": "2013",
            "url": "https://docs.docker.com/engine/security/",
            "repo_url": None,
            "docs_url": "https://docs.docker.com/engine/security/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "container_security_docs",
            "taxonomy_tags": ["filesystem_boundaries", "network_egress_control", "secrets_management", "sandboxed_code_execution"],
            "expected_learning_value": "Best practices for securing containers: namespaces, cgroups, seccomp, capabilities, AppArmor/SELinux.",
            "specific_brain_capability_target": "design_network_egress",
            "cross_check_targets": ["gvisor_docs", "firecracker_docs"],
            "safety_score_estimate": 60,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Standard reference for container security. Good for understanding Linux sandboxing primitives.",
        },
        {
            "source_id": "sigstore_docs",
            "source_group": "framework",
            "title": "Sigstore -- Software Signing and Transparency",
            "authors_or_org": "OpenSSF / Linux Foundation",
            "year_or_first_release": "2021",
            "url": "https://www.sigstore.dev/",
            "repo_url": "https://github.com/sigstore",
            "docs_url": "https://docs.sigstore.dev/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "supply_chain_security_framework",
            "taxonomy_tags": ["supply_chain_security", "immutable_evidence_logs", "dependency_trust"],
            "expected_learning_value": "Keyless signing and transparency log for software artifacts, eliminating the need for long-lived keys.",
            "specific_brain_capability_target": "preserve_evidence",
            "cross_check_targets": ["slsa_framework", "openssf_scorecard"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open standard backed by Linux Foundation. Good for artifact provenance and audit trails.",
        },
        {
            "source_id": "openssf_scorecard",
            "source_group": "framework",
            "title": "OpenSSF Scorecard -- Security Health Metrics for Open Source Projects",
            "authors_or_org": "Open Source Security Foundation (OpenSSF)",
            "year_or_first_release": "2021",
            "url": "https://securityscorecards.dev/",
            "repo_url": "https://github.com/ossf/scorecard",
            "docs_url": "https://securityscorecards.dev/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "dependency_security_framework",
            "taxonomy_tags": ["dependency_trust", "supply_chain_security", "audit_logging"],
            "expected_learning_value": "Automated security scoring for open source repos: dependency update, code review, signed releases, etc.",
            "specific_brain_capability_target": "manage_dependencies",
            "cross_check_targets": ["pip_audit_repo", "slsa_framework"],
            "safety_score_estimate": 62,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Good for automated dependency risk assessment. Can be integrated into CI/CD.",
        },
        {
            "source_id": "pip_audit_repo",
            "source_group": "repo",
            "title": "pip-audit -- Scan Python Environments for Known Vulnerabilities",
            "authors_or_org": "Trail of Bits / PyPA",
            "year_or_first_release": "2022",
            "url": "https://github.com/pypa/pip-audit",
            "repo_url": "https://github.com/pypa/pip-audit",
            "docs_url": "https://pip-audit.readthedocs.io/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "dependency_scanning_tool",
            "taxonomy_tags": ["dependency_trust", "supply_chain_security"],
            "expected_learning_value": "Scanning installed Python packages against known vulnerability databases (OSV).",
            "specific_brain_capability_target": "manage_dependencies",
            "cross_check_targets": ["openssf_scorecard", "semgrep_repo"],
            "safety_score_estimate": 61,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "PyPA-backed. Good for Python dependency vulnerability scanning.",
        },
        {
            "source_id": "semgrep_repo",
            "source_group": "repo",
            "title": "Semgrep -- Lightweight Static Analysis for Many Languages",
            "authors_or_org": "Semgrep (r2c)",
            "year_or_first_release": "2020",
            "url": "https://github.com/returntocorp/semgrep",
            "repo_url": "https://github.com/returntocorp/semgrep",
            "docs_url": "https://semgrep.dev/docs/",
            "license": "LGPL-2.1",
            "maintenance_status": "active",
            "source_type": "static_analysis_tool",
            "taxonomy_tags": ["supply_chain_security", "dependency_trust", "secrets_management"],
            "expected_learning_value": "Fast static analysis with community and custom rule sets for security and correctness.",
            "specific_brain_capability_target": "manage_dependencies",
            "cross_check_targets": ["bandit_repo", "openssf_scorecard"],
            "safety_score_estimate": 60,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source core with optional managed rules. Good for code security scanning.",
        },
        {
            "source_id": "bandit_repo",
            "source_group": "repo",
            "title": "Bandit -- Security Linter for Python",
            "authors_or_org": "PyCQA",
            "year_or_first_release": "2014",
            "url": "https://github.com/PyCQA/bandit",
            "repo_url": "https://github.com/PyCQA/bandit",
            "docs_url": "https://bandit.readthedocs.io/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "static_analysis_tool",
            "taxonomy_tags": ["secrets_management", "sandboxed_code_execution", "supply_chain_security"],
            "expected_learning_value": "Python-specific security linting: hardcoded passwords, unsafe eval, weak crypto, etc.",
            "specific_brain_capability_target": "protect_secrets",
            "cross_check_targets": ["semgrep_repo", "pip_audit_repo"],
            "safety_score_estimate": 60,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "PyCQA project. Well-established. Good for Python security baseline.",
        },
        {
            "source_id": "github_actions_security",
            "source_group": "docs",
            "title": "GitHub Actions Security Hardening",
            "authors_or_org": "GitHub",
            "year_or_first_release": "2019",
            "url": "https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions",
            "repo_url": None,
            "docs_url": "https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions",
            "license": "Proprietary (public reference)",
            "maintenance_status": "active",
            "source_type": "ci_cd_security_docs",
            "taxonomy_tags": ["supply_chain_security", "secrets_management", "dependency_trust"],
            "expected_learning_value": "Best practices for securing CI/CD pipelines: pinned actions, minimal permissions, secret scanning.",
            "specific_brain_capability_target": "manage_dependencies",
            "cross_check_targets": ["openssf_scorecard", "sigstore_docs"],
            "safety_score_estimate": 56,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "medium",
            "notes": "GitHub-specific but principles generalize. Good for CI/CD security posture.",
        },
        {
            "source_id": "microsoft_presidio",
            "source_group": "repo",
            "title": "Microsoft Presidio -- Data Protection and PII Detection",
            "authors_or_org": "Microsoft",
            "year_or_first_release": "2019",
            "url": "https://github.com/microsoft/presidio",
            "repo_url": "https://github.com/microsoft/presidio",
            "docs_url": "https://microsoft.github.io/presidio/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "privacy_framework",
            "taxonomy_tags": ["privacy_governance", "chain_of_thought_non_disclosure", "secrets_management"],
            "expected_learning_value": "Context-aware PII detection and anonymization for text, images, and structured data.",
            "specific_brain_capability_target": "prevent_data_leakage",
            "cross_check_targets": ["nist_ai_rmf", "anthropic_constitutional_ai"],
            "safety_score_estimate": 59,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source. Good for PII detection before logging or transmitting data.",
        },
        {
            "source_id": "promptfoo_docs",
            "source_group": "docs",
            "title": "promptfoo -- LLM Red-Team and Security Testing",
            "authors_or_org": "promptfoo",
            "year_or_first_release": "2023",
            "url": "https://www.promptfoo.dev/",
            "repo_url": "https://github.com/promptfoo/promptfoo",
            "docs_url": "https://www.promptfoo.dev/docs/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "security_testing_framework",
            "taxonomy_tags": ["prompt_injection_defense", "tool_use_governance", "audit_logging"],
            "expected_learning_value": "Automated red-team testing for LLM applications: prompt injection, jailbreak, bias, PII leakage.",
            "specific_brain_capability_target": "detect_prompt_injection",
            "cross_check_targets": ["prompt_injection_paper", "owasp_llm_top10"],
            "safety_score_estimate": 58,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source red-teaming. Useful for testing Brain's prompt defenses. Defensive-only.",
        },
        {
            "source_id": "unknown_security_blog",
            "source_group": "docs",
            "title": "10 AI Security Tips -- Unattributed Blog Post",
            "authors_or_org": "unknown",
            "year_or_first_release": "unknown",
            "url": "https://example-blog.com/ai-security",
            "repo_url": None,
            "docs_url": None,
            "license": "unknown",
            "maintenance_status": "unknown",
            "source_type": "blog_post",
            "taxonomy_tags": ["execution_gates"],
            "expected_learning_value": "Generic listicle. No methodology depth.",
            "specific_brain_capability_target": "design_execution_gates",
            "cross_check_targets": ["nist_ai_rmf"],
            "safety_score_estimate": 20,
            "contrast_confidence": "low",
            "acceptance_status": "reject",
            "ingestion_status": "not_ingested",
            "copyright_risk": "medium",
            "privacy_risk": "low",
            "security_misuse_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "No attribution. No evidence. SEO content. Reject.",
        },
    ]


def seed_candidate_sources() -> list[dict]:
    return _seed_standards_papers() + _seed_repos_frameworks()


def cross_source_contrast_matrix() -> list[dict]:
    """Cross-source contrast for selected pairs."""
    return [
        {
            "pair": ["nist_ai_rmf", "nist_csf"],
            "contrast_type": "AI-specific vs general cybersecurity standard",
            "confirms": "Both frameworks emphasize risk identification, protection, and continuous improvement.",
            "contradicts": None,
            "complements": "AI RMF adds AI-specific risks (bias, transparency, accountability); CSF provides broader infrastructure security.",
            "unresolved_questions": "How should AI RMF and CSF be integrated for hybrid AI/infrastructure systems?",
            "confidence_level": "high",
        },
        {
            "pair": ["owasp_llm_top10", "mitre_atlas"],
            "contrast_type": "risk list vs threat framework",
            "confirms": "Both identify prompt injection as a top risk for LLM systems.",
            "contradicts": None,
            "complements": "OWASP provides actionable mitigations; MITRE ATLAS provides adversary tactics and techniques.",
            "unresolved_questions": "How often do real-world attackers use the techniques catalogued in ATLAS?",
            "confidence_level": "high",
        },
        {
            "pair": ["google_saif", "microsoft_responsible_ai"],
            "contrast_type": "vendor security framework vs vendor governance framework",
            "confirms": "Both major cloud providers recognize supply-chain and privacy as critical AI security areas.",
            "contradicts": None,
            "complements": "SAIF is more technical/operational; Responsible AI is more governance/policy-oriented.",
            "unresolved_questions": "Which framework's controls are more effective in practice?",
            "confidence_level": "medium",
        },
        {
            "pair": ["gvisor_docs", "firecracker_docs"],
            "contrast_type": "userspace sandbox vs microvm sandbox",
            "confirms": "Both provide strong isolation for untrusted code execution.",
            "contradicts": None,
            "complements": "gVisor is easier to integrate with containers; Firecracker provides stronger VM-level isolation.",
            "unresolved_questions": "What is the performance overhead of gVisor vs Firecracker for Brain's workload?",
            "confidence_level": "high",
        },
        {
            "pair": ["opa_docs", "nist_csf"],
            "contrast_type": "policy engine vs security standard",
            "confirms": "Policy enforcement is a core component of the CSF 'Protect' function.",
            "contradicts": None,
            "complements": "OPA is a concrete implementation of policy-as-code; CSF describes the governance need for it.",
            "unresolved_questions": "Can OPA scale to real-time policy decisions for every Brain action?",
            "confidence_level": "high",
        },
        {
            "pair": ["prompt_injection_paper", "promptfoo_docs"],
            "contrast_type": "academic research vs security testing tool",
            "confirms": "Indirect prompt injection is a real and testable threat to RAG-based systems.",
            "contradicts": None,
            "complements": "Paper defines the threat model; promptfoo provides automated red-team testing for it.",
            "unresolved_questions": "How effective are current prompt injection defenses against adaptive attackers?",
            "confidence_level": "high",
        },
        {
            "pair": ["slsa_framework", "sigstore_docs"],
            "contrast_type": "supply-chain levels vs signing framework",
            "confirms": "Both aim to improve software supply-chain trust through transparency and verification.",
            "contradicts": None,
            "complements": "SLSA defines the maturity levels; Sigstore provides the keyless signing and transparency log infrastructure.",
            "unresolved_questions": "What is the adoption rate of SLSA + Sigstore in mainstream open source?",
            "confidence_level": "high",
        },
        {
            "pair": ["openssf_scorecard", "pip_audit_repo"],
            "contrast_type": "security scoring vs vulnerability scanning",
            "confirms": "Both improve open-source security posture through automated assessment.",
            "contradicts": None,
            "complements": "Scorecard evaluates overall project health; pip-audit focuses on known CVEs in installed packages.",
            "unresolved_questions": "Can Scorecard and pip-audit be combined into a unified dependency risk score?",
            "confidence_level": "medium",
        },
        {
            "pair": ["anthropic_responsible_scaling", "anthropic_constitutional_ai"],
            "contrast_type": "governance policy vs technical method",
            "confirms": "Both aim to align AI behavior with human values and safety.",
            "contradicts": None,
            "complements": "Responsible Scaling defines the governance framework; Constitutional AI provides a technical self-critique mechanism.",
            "unresolved_questions": "Can Constitutional AI fully satisfy the safety requirements of Responsible Scaling?",
            "confidence_level": "medium",
        },
    ]


def knowledge_record_schema() -> dict:
    return {
        "description": "Schema for a future knowledge record if ingestion is ever authorized.",
        "required_fields": [
            "source_id",
            "source_group",
            "title",
            "authors_or_org",
            "url",
            "taxonomy_tags",
            "specific_brain_capability_target",
            "safety_score",
            "acceptance_status",
            "ingestion_status",
            "copyright_risk",
            "privacy_risk",
            "security_misuse_risk",
            "vendor_lock_in_risk",
        ],
        "optional_fields": [
            "repo_url",
            "docs_url",
            "license",
            "maintenance_status",
            "year_or_first_release",
            "expected_learning_value",
            "cross_check_targets",
            "contrast_confidence",
            "notes",
        ],
        "forbidden_fields": [
            "full_text",
            "raw_pdf_bytes",
            "full_readme_text",
            "proprietary_dataset",
            "api_keys",
            "credentials",
            "exploit_code",
            "malware_samples",
        ],
        "retention_policy": "Metadata and summary only. Full content must remain external. No offensive security content.",
    }


def build_curated_learning_plan() -> dict:
    sources = seed_candidate_sources()
    taxonomy = canonical_taxonomy()
    contrast = cross_source_contrast_matrix()
    cap_map = brain_governance_capability_map()
    accepted = [s for s in sources if s["acceptance_status"] == "accept"]
    hold = [s for s in sources if s["acceptance_status"] == "hold"]
    rejected = [s for s in sources if s["acceptance_status"] == "reject"]
    return {
        "front_id": front_id(),
        "domain": learning_domain(),
        "taxonomy": taxonomy,
        "acceptance_criteria": source_acceptance_criteria(),
        "rejection_criteria": source_rejection_criteria(),
        "safety_rubric": source_safety_scoring_rubric(),
        "contrast_rubric": source_contrast_scoring_rubric(),
        "brain_governance_capability_map": cap_map,
        "sources": sources,
        "cross_source_contrast_matrix": contrast,
        "knowledge_record_schema": knowledge_record_schema(),
        "summary": {
            "source_count": len(sources),
            "taxonomy_count": len(taxonomy),
            "capability_map_count": len(cap_map),
            "source_groups": list({s["source_group"] for s in sources}),
            "accepted_count": len(accepted),
            "hold_count": len(hold),
            "rejected_count": len(rejected),
            "ingestion_status": "dry_run_only",
            "memory_mutated": False,
            "faiss_mutated": False,
        },
    }


def summarize_curated_learning_plan() -> dict:
    plan = build_curated_learning_plan()
    return {
        "front_id": plan["front_id"],
        "domain": plan["domain"]["id"],
        "source_count": plan["summary"]["source_count"],
        "taxonomy_count": plan["summary"]["taxonomy_count"],
        "capability_map_count": plan["summary"]["capability_map_count"],
        "source_groups": plan["summary"]["source_groups"],
        "accepted_count": plan["summary"]["accepted_count"],
        "hold_count": plan["summary"]["hold_count"],
        "rejected_count": plan["summary"]["rejected_count"],
        "ingestion_status": plan["summary"]["ingestion_status"],
        "memory_mutated": plan["summary"]["memory_mutated"],
        "faiss_mutated": plan["summary"]["faiss_mutated"],
    }


def assert_no_memory_or_faiss_mutation(before: dict, after: dict) -> dict:
    """Compare before/after inventory dicts. Returns pass/fail details."""
    checks = {
        "semantic_memory_jsonl_sha": before.get("semantic_memory_jsonl", {}).get("sha256") == after.get("semantic_memory_jsonl", {}).get("sha256"),
        "semantic_memory_jsonl_lines": before.get("semantic_memory_jsonl", {}).get("line_count") == after.get("semantic_memory_jsonl", {}).get("line_count"),
        "faiss_index_sha": before.get("semantic_memory_faiss_index", {}).get("sha256") == after.get("semantic_memory_faiss_index", {}).get("sha256"),
        "faiss_ids_sha": before.get("semantic_memory_faiss_ids", {}).get("sha256") == after.get("semantic_memory_faiss_ids", {}).get("sha256"),
        "faiss_ids_count": before.get("semantic_memory_faiss_ids", {}).get("id_count") == after.get("semantic_memory_faiss_ids", {}).get("id_count"),
    }
    all_pass = all(checks.values())
    return {
        "pass": all_pass,
        "checks": checks,
        "before_summary": {k: before.get(k, {}).get("sha256", before.get(k, {}).get("line_count", before.get(k, {}).get("id_count"))) for k in before if k not in ("timestamp", "head")},
        "after_summary": {k: after.get(k, {}).get("sha256", after.get(k, {}).get("line_count", after.get(k, {}).get("id_count"))) for k in after if k not in ("timestamp", "head")},
    }
