"""
External Curated Learning -- Autonomous Coding & Patch Generation
FRONT-EXTERNAL-CURATED-LEARNING-AUTONOMOUS-CODING-PATCH-GENERATION-01

This module is a CURATION DRY-RUN ONLY.
It does NOT ingest into semantic memory or FAISS.
It does NOT download full papers or repos.
It does NOT modify protected runtime files.
It does NOT create actual patch-generation autonomy.
It does NOT run untrusted code from external repos.

Purpose: Create a safe, attributable, technically relevant, cross-checked
source plan for Brain to learn autonomous coding, patch generation, test-driven
repair, CI validation, regression prevention, and safe patch promotion.
"""

from pathlib import Path
import json


FRONT_ID = "FRONT-EXTERNAL-CURATED-LEARNING-AUTONOMOUS-CODING-PATCH-GENERATION-01"


def front_id() -> str:
    return FRONT_ID


def learning_domain() -> dict:
    return {
        "id": "autonomous_coding_patch_generation",
        "display_name": "Autonomous Coding & Patch Generation",
        "description": (
            "How to design, evaluate, and govern coding agents that can "
            "understand issues, navigate codebases, generate patches, validate "
            "through tests, and promote changes safely without corrupting "
            "repository state or violating boundaries."
        ),
        "macro_order": 5,
        "target_brain_capabilities": [
            "understand issue / task description",
            "inspect repository safely",
            "localize relevant files",
            "plan small patch",
            "generate minimal diff",
            "avoid protected files",
            "run static checks",
            "run unit/smoke tests",
            "evaluate before/after behavior",
            "detect regression risk",
            "preserve git hygiene",
            "avoid hash chasing",
            "create small commits",
            "produce patch evidence",
            "decide promote / reject / rollback",
            "avoid untrusted code execution",
            "support human approval gates",
            "prepare future financial code safety",
            "evaluate coding-agent performance",
            "integrate with governance/security fronts",
        ],
    }


def canonical_taxonomy() -> list[dict]:
    """25 required categories covering autonomous coding landscape."""
    return [
        {"id": "codebase_navigation", "name": "Codebase Navigation", "description": "Understanding repository structure and locating relevant files."},
        {"id": "issue_understanding", "name": "Issue Understanding", "description": "Parsing bug reports, feature requests, and task descriptions."},
        {"id": "bug_localization", "name": "Bug Localization", "description": "Identifying the specific code regions responsible for a failure."},
        {"id": "patch_planning", "name": "Patch Planning", "description": "Designing a minimal, correct fix before implementation."},
        {"id": "code_generation", "name": "Code Generation", "description": "Writing new code or modifying existing code to satisfy requirements."},
        {"id": "diff_generation", "name": "Diff Generation", "description": "Producing precise, reviewable patches (unified diff format)."},
        {"id": "test_driven_repair", "name": "Test-Driven Repair", "description": "Using failing tests to guide and validate patch correctness."},
        {"id": "regression_testing", "name": "Regression Testing", "description": "Ensuring changes do not break existing functionality."},
        {"id": "static_analysis", "name": "Static Analysis", "description": "Analyzing code without execution to detect bugs, style issues, or security flaws."},
        {"id": "linting_formatting", "name": "Linting / Formatting", "description": "Enforcing code style and catching simple errors automatically."},
        {"id": "ci_validation", "name": "CI Validation", "description": "Running automated checks in continuous integration before merge."},
        {"id": "patch_review", "name": "Patch Review", "description": "Evaluating patch quality, correctness, and safety before acceptance."},
        {"id": "small_commit_discipline", "name": "Small Commit Discipline", "description": "Keeping changes minimal and focused for easier review and rollback."},
        {"id": "rollback_revert_strategy", "name": "Rollback / Revert Strategy", "description": "Procedures to undo changes and restore safe repository state."},
        {"id": "refactoring_safety", "name": "Refactoring Safety", "description": "Improving code structure without changing external behavior."},
        {"id": "dependency_aware_patching", "name": "Dependency-Aware Patching", "description": "Considering downstream effects of changes on dependent modules."},
        {"id": "benchmark_driven_coding_agents", "name": "Benchmark-Driven Coding Agents", "description": "Using standard benchmarks to measure and compare coding agent performance."},
        {"id": "swe_bench_style_evaluation", "name": "SWE-bench Style Evaluation", "description": "Execution-based evaluation of real-world software engineering tasks."},
        {"id": "code_execution_sandboxing", "name": "Code Execution Sandboxing", "description": "Isolating untrusted or generated code during test and validation."},
        {"id": "tool_use_governance_for_coding", "name": "Tool-Use Governance for Coding Agents", "description": "Controlling which tools (compilers, linters, test runners) agents may invoke."},
        {"id": "human_approval_gates_for_patches", "name": "Human Approval Gates for Patches", "description": "Requiring explicit authorization before applying generated patches."},
        {"id": "autonomous_coding_failure_modes", "name": "Autonomous Coding Failure Modes", "description": "Understanding how coding agents fail: hallucinated APIs, incomplete fixes, test overfitting."},
        {"id": "repository_state_hygiene", "name": "Repository State Hygiene", "description": "Maintaining clean working trees, avoiding uncommitted debris, respecting .gitignore."},
        {"id": "protected_file_boundaries", "name": "Protected File Boundaries", "description": "Preventing agents from modifying sensitive files (secrets, configs, protected modules)."},
        {"id": "financial_code_safety_readiness", "name": "Financial Code Safety Readiness", "description": "Preparing coding agents to safely modify trading, risk, or financial logic."},
    ]


def source_acceptance_criteria() -> dict:
    return {
        "description": "A source is accepted only if it is safe, attributable, technically relevant, and cross-checkable.",
        "minimum_conditions": [
            "Clear attribution (authors, org, or maintainers)",
            "Publicly reachable URL or repo",
            "Technical depth exceeds marketing/hype",
            "License allows metadata/summary reference",
            "Relevance to at least one taxonomy category",
            "Not contradicted by a more authoritative source",
            "No critical risk flagged by safety rubric",
        ],
        "accept_threshold": {"score_min": 62, "no_critical_risks": True},
        "hold_threshold": {"score_range": [45, 61], "metadata_incomplete_ok": True},
        "decision_rule": "Accept if score >= 62 and no critical risks; hold if 45-61 or incomplete; reject if < 45 or any critical risk.",
    }


def source_rejection_criteria() -> dict:
    return {
        "description": "Automatic rejection conditions regardless of popularity.",
        "critical_risks": [
            "Private or access-restricted content",
            "No identifiable attribution",
            "Illegal or copyright-violating distribution",
            "Source requires copying full copyrighted text to be useful",
            "Source requires running untrusted code",
            "Exploit/malware emphasis",
            "Unsafe autonomous patching without rollback",
            "Unverifiable coding benchmark claims",
            "Abandoned and directly contradicted by newer official source",
        ],
        "score_reject_threshold": 45,
    }


def source_safety_scoring_rubric() -> dict:
    """
    19 dimensions scored 0-5.
    Max possible = 95.
    Accept >= 62, Hold 45-61, Reject < 45.
    """
    return {
        "dimensions": {
            "attribution_quality": "Can the source be clearly attributed to known authors, orgs, or maintainers?",
            "primary_source_quality": "Is this a primary source (paper, official repo, official docs) rather than repackaged blog?",
            "technical_depth": "Does the source contain concrete coding-agent architecture, algorithms, or implementation details?",
            "implementation_relevance": "Can the ideas be implemented without vendor-specific proprietary infrastructure?",
            "coding_workflow_clarity": "Are the steps from issue understanding to patch generation clearly defined?",
            "patch_validation_clarity": "Are validation methods (tests, static analysis, review) explicitly described?",
            "benchmark_method_clarity": "Are benchmark tasks, metrics, and baselines clearly defined?",
            "reproducibility": "Are there reproducible steps, examples, or tests?",
            "license_clarity": "Is the license clearly stated and compatible with metadata reference?",
            "maintenance_status": "Is the repo/docs actively maintained, or at least archived with clear status?",
            "test_or_example_presence": "Does the source include runnable examples, tests, or demos?",
            "copyright_safety": "Can we reference it at metadata/summary level without copyright risk?",
            "relevance_to_brain": "Does it map directly to a Brain coding capability target?",
            "risk_of_hype_or_marketing": "Is the content free of exaggerated marketing claims? (5 = very safe, 0 = pure hype)",
            "risk_of_obsolescence": "Is the source likely to remain relevant for 12+ months?",
            "risk_of_vendor_lock_in": "Does the approach require a specific vendor/cloud service? (5 = vendor-neutral, 0 = full lock-in)",
            "risk_of_unsafe_code_execution": "Does the source require or encourage running untrusted code? (5 = very safe, 0 = high risk)",
            "risk_of_repo_state_corruption": "Could following this source corrupt repository state or working tree? (5 = very safe, 0 = high risk)",
            "risk_of_unverifiable_claims": "Are core claims supported by evidence, code, or reproducible results?",
        },
        "scale": "0-5 per dimension",
        "max_possible": 95,
        "thresholds": {
            "accept": {"min_score": 62, "condition": "no_critical_risks"},
            "hold": {"min_score": 45, "max_score": 61},
            "reject": {"max_score": 44},
        },
    }


def source_contrast_scoring_rubric() -> dict:
    return {
        "description": "Each candidate source must be contrasted against at least two sources of different types when possible.",
        "contrast_types": [
            "coding-agent paper vs benchmark repo",
            "SWE-bench paper vs SWE-agent implementation",
            "issue-to-patch framework vs CI/testing docs",
            "benchmark claim vs reproducible harness",
            "autonomous patch framework vs sandbox/governance source",
            "refactoring source vs regression testing source",
        ],
        "per_source_fields": [
            "confirms",
            "contradicts",
            "complements",
            "unresolved_questions",
            "confidence_level",
        ],
        "confidence_levels": ["low", "medium", "high"],
    }


def brain_coding_capability_map() -> list[dict]:
    """Map sources to concrete Brain coding capabilities."""
    return [
        {"capability_id": "understand_issue", "name": "Understand Issue / Task Description", "description": "Parsing and interpreting bug reports, feature requests, and specifications.", "relevant_taxonomy": ["issue_understanding", "bug_localization"], "example_sources": ["swe_bench_jimenez_2023", "swe_agent_yang_2024"]},
        {"capability_id": "inspect_repo", "name": "Inspect Repository Safely", "description": "Navigating codebase structure without modifying files.", "relevant_taxonomy": ["codebase_navigation", "repository_state_hygiene"], "example_sources": ["swe_agent_repo", "aider_repo"]},
        {"capability_id": "localize_files", "name": "Localize Relevant Files", "description": "Identifying files and functions related to a bug or feature.", "relevant_taxonomy": ["bug_localization", "codebase_navigation"], "example_sources": ["swe_bench_jimenez_2023", "swe_agent_yang_2024"]},
        {"capability_id": "plan_patch", "name": "Plan Small Patch", "description": "Designing a minimal, focused fix before writing code.", "relevant_taxonomy": ["patch_planning", "small_commit_discipline"], "example_sources": ["swe_agent_yang_2024", "react_yao_2022"]},
        {"capability_id": "generate_diff", "name": "Generate Minimal Diff", "description": "Producing precise, reviewable code changes.", "relevant_taxonomy": ["diff_generation", "code_generation"], "example_sources": ["swe_agent_repo", "aider_repo"]},
        {"capability_id": "avoid_protected", "name": "Avoid Protected Files", "description": "Respecting boundaries on files that must not be modified.", "relevant_taxonomy": ["protected_file_boundaries", "tool_use_governance_for_coding"], "example_sources": ["brain_governance_front", "bandit_repo"]},
        {"capability_id": "run_static_checks", "name": "Run Static Checks", "description": "Using linters and static analyzers to catch issues.", "relevant_taxonomy": ["static_analysis", "linting_formatting"], "example_sources": ["ruff_docs", "semgrep_repo"]},
        {"capability_id": "run_tests", "name": "Run Unit/Smoke Tests", "description": "Executing test suites to validate behavior.", "relevant_taxonomy": ["test_driven_repair", "ci_validation"], "example_sources": ["pytest_docs", "swe_bench_repo"]},
        {"capability_id": "evaluate_before_after", "name": "Evaluate Before/After Behavior", "description": "Comparing system behavior before and after a patch.", "relevant_taxonomy": ["regression_testing", "swe_bench_style_evaluation"], "example_sources": ["swe_bench_jimenez_2023", "agentbench_liu_2023"]},
        {"capability_id": "detect_regression", "name": "Detect Regression Risk", "description": "Identifying whether a change might break other functionality.", "relevant_taxonomy": ["regression_testing", "dependency_aware_patching"], "example_sources": ["agentbench_liu_2023", "big_bench_srivastava_2022"]},
        {"capability_id": "preserve_git_hygiene", "name": "Preserve Git Hygiene", "description": "Maintaining clean working trees and proper commit discipline.", "relevant_taxonomy": ["repository_state_hygiene", "small_commit_discipline"], "example_sources": ["github_actions_security", "pre_commit_docs"]},
        {"capability_id": "avoid_hash_chasing", "name": "Avoid Hash Chasing", "description": "Not creating commits solely to update metadata hashes.", "relevant_taxonomy": ["repository_state_hygiene", "protected_file_boundaries"], "example_sources": ["brain_governance_front", "ledger_practices"]},
        {"capability_id": "create_small_commits", "name": "Create Small Commits", "description": "Keeping changes minimal and focused.", "relevant_taxonomy": ["small_commit_discipline", "patch_review"], "example_sources": ["github_actions_security", "aider_repo"]},
        {"capability_id": "produce_evidence", "name": "Produce Patch Evidence", "description": "Documenting what changed, why, and test results.", "relevant_taxonomy": ["patch_review", "ci_validation"], "example_sources": ["swe_bench_jimenez_2023", "trulens_repo"]},
        {"capability_id": "decide_promote", "name": "Decide Promote / Reject / Rollback", "description": "Making go/no-go decisions on patch acceptance.", "relevant_taxonomy": ["rollback_revert_strategy", "human_approval_gates_for_patches"], "example_sources": ["brain_governance_front", "swe_bench_repo"]},
        {"capability_id": "avoid_untrusted", "name": "Avoid Untrusted Code Execution", "description": "Not running external or generated code without sandboxing.", "relevant_taxonomy": ["code_execution_sandboxing", "tool_use_governance_for_coding"], "example_sources": ["gvisor_docs", "docker_security_docs"]},
        {"capability_id": "support_approval", "name": "Support Human Approval Gates", "description": "Requiring explicit authorization for high-risk patches.", "relevant_taxonomy": ["human_approval_gates_for_patches", "financial_code_safety_readiness"], "example_sources": ["brain_governance_front", "nist_ai_rmf"]},
        {"capability_id": "prepare_financial", "name": "Prepare Future Financial Code Safety", "description": "Specialized controls for trading and financial code modification.", "relevant_taxonomy": ["financial_code_safety_readiness", "dependency_aware_patching"], "example_sources": ["brain_governance_front", "swe_agent_yang_2024"]},
        {"capability_id": "evaluate_agent", "name": "Evaluate Coding-Agent Performance", "description": "Measuring success rate, patch quality, and safety.", "relevant_taxonomy": ["benchmark_driven_coding_agents", "swe_bench_style_evaluation"], "example_sources": ["swe_bench_jimenez_2023", "human_eval_chen_2021"]},
        {"capability_id": "integrate_governance", "name": "Integrate with Governance/Security Fronts", "description": "Ensuring coding agents respect security and governance constraints.", "relevant_taxonomy": ["tool_use_governance_for_coding", "protected_file_boundaries"], "example_sources": ["brain_governance_front", "owasp_llm_top10"]},
    ]


def _seed_papers_benchmarks() -> list[dict]:
    """Papers, benchmarks, and research candidates (metadata only)."""
    return [
        {
            "source_id": "swe_bench_jimenez_2023",
            "source_group": "benchmark",
            "title": "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?",
            "authors_or_org": "Jimenez et al. / Princeton / others",
            "year_or_first_release": "2023",
            "url": "https://arxiv.org/abs/2310.06770",
            "repo_url": "https://github.com/princeton-nlp/SWE-bench",
            "docs_url": "https://www.swebench.com/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "benchmark_paper",
            "taxonomy_tags": ["swe_bench_style_evaluation", "test_driven_repair", "regression_testing", "benchmark_driven_coding_agents"],
            "expected_learning_value": "Execution-based benchmark for real-world GitHub issue resolution with test validation.",
            "specific_brain_capability_target": "evaluate_agent",
            "cross_check_targets": ["swe_agent_yang_2024", "swe_bench_repo"],
            "safety_score_estimate": 66,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Gold standard for coding-agent evaluation. Active leaderboard. Execution-based validation prevents hallucinated fixes.",
        },
        {
            "source_id": "swe_agent_yang_2024",
            "source_group": "paper",
            "title": "SWE-agent: Agent-Computer Interfaces Enable Automated Software Engineering",
            "authors_or_org": "Yang et al. / Princeton / Stanford / others",
            "year_or_first_release": "2024",
            "url": "https://arxiv.org/abs/2405.17165",
            "repo_url": "https://github.com/SWE-agent/SWE-agent",
            "docs_url": "https://princeton-nlp.github.io/SWE-agent/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "research_paper",
            "taxonomy_tags": ["patch_planning", "code_generation", "diff_generation", "tool_use_governance_for_coding"],
            "expected_learning_value": "Interface design (not model size) is the strongest lever for coding-agent success.",
            "specific_brain_capability_target": "plan_patch",
            "cross_check_targets": ["swe_bench_jimenez_2023", "swe_agent_repo"],
            "safety_score_estimate": 67,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Strong empirical evidence. Active repo. Well-documented. Good for understanding agent-computer interfaces.",
        },
        {
            "source_id": "human_eval_chen_2021",
            "source_group": "benchmark",
            "title": "Evaluating Large Language Models Trained on Code",
            "authors_or_org": "Chen et al. / OpenAI",
            "year_or_first_release": "2021",
            "url": "https://arxiv.org/abs/2107.03374",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "benchmark_paper",
            "taxonomy_tags": ["benchmark_driven_coding_agents", "code_generation", "test_driven_repair"],
            "expected_learning_value": "HumanEval benchmark for functional correctness of synthesized Python programs.",
            "specific_brain_capability_target": "evaluate_agent",
            "cross_check_targets": ["mbpp_austin_2021", "swe_bench_jimenez_2023"],
            "safety_score_estimate": 64,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Widely cited. Simple but effective benchmark. Note: some models may have memorized HumanEval solutions.",
        },
        {
            "source_id": "mbpp_austin_2021",
            "source_group": "benchmark",
            "title": "Program Synthesis with Large Language Models",
            "authors_or_org": "Austin et al. / Google / others",
            "year_or_first_release": "2021",
            "url": "https://arxiv.org/abs/2108.07732",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "benchmark_paper",
            "taxonomy_tags": ["benchmark_driven_coding_agents", "code_generation", "test_driven_repair"],
            "expected_learning_value": "MBPP benchmark: Python programming problems with test cases for evaluating code generation.",
            "specific_brain_capability_target": "evaluate_agent",
            "cross_check_targets": ["human_eval_chen_2021", "swe_bench_jimenez_2023"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Complementary to HumanEval. More diverse problem set. Some memorization risk for large models.",
        },
        {
            "source_id": "autocoderover_zhang_2024",
            "source_group": "paper",
            "title": "AutoCodeRover: Autonomous Program Improvement",
            "authors_or_org": "Zhang et al. / National University of Singapore / others",
            "year_or_first_release": "2024",
            "url": "https://arxiv.org/abs/2404.05427",
            "repo_url": "https://github.com/nus-apr/auto-code-rover",
            "docs_url": None,
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "research_paper",
            "taxonomy_tags": ["bug_localization", "patch_planning", "code_generation", "benchmark_driven_coding_agents"],
            "expected_learning_value": "Iterative context retrieval and patch generation with test feedback for autonomous program repair.",
            "specific_brain_capability_target": "localize_files",
            "cross_check_targets": ["swe_agent_yang_2024", "swe_bench_repo"],
            "safety_score_estimate": 65,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Active repo. Good for understanding iterative repair loops. Strong SWE-bench results reported.",
        },
        {
            "source_id": "react_yao_2022",
            "source_group": "paper",
            "title": "ReAct: Synergizing Reasoning and Acting in Language Models",
            "authors_or_org": "Yao et al. / Google Research",
            "year_or_first_release": "2022",
            "url": "https://arxiv.org/abs/2210.03629",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "research_paper",
            "taxonomy_tags": ["patch_planning", "code_generation", "tool_use_governance_for_coding"],
            "expected_learning_value": "Interleaving reasoning traces with actions improves planning and reduces errors in agentic tasks.",
            "specific_brain_capability_target": "plan_patch",
            "cross_check_targets": ["reflexion_shinn_2023", "swe_agent_yang_2024"],
            "safety_score_estimate": 62,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Foundational pattern for coding agents. Widely reproduced. Good for reasoning-action loops.",
        },
        {
            "source_id": "agentbench_liu_2023",
            "source_group": "benchmark",
            "title": "AgentBench: Evaluating LLM Agents",
            "authors_or_org": "Liu et al. / Tsinghua / others",
            "year_or_first_release": "2023",
            "url": "https://arxiv.org/abs/2308.03688",
            "repo_url": "https://github.com/THUDM/AgentBench",
            "docs_url": None,
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "benchmark_paper",
            "taxonomy_tags": ["benchmark_driven_coding_agents", "code_generation", "autonomous_coding_failure_modes"],
            "expected_learning_value": "Multi-environment benchmark for LLM agents including code execution, database, web browsing, and operating system tasks.",
            "specific_brain_capability_target": "evaluate_agent",
            "cross_check_targets": ["swe_bench_jimenez_2023", "human_eval_chen_2021"],
            "safety_score_estimate": 65,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Covers coding among many agent tasks. Good for comparing coding agents to general agents.",
        },
        {
            "source_id": "reflexion_shinn_2023",
            "source_group": "paper",
            "title": "Reflexion: Self-Reflective Agents with Verbal Reinforcement Learning",
            "authors_or_org": "Shinn et al. / Northeastern / MIT",
            "year_or_first_release": "2023",
            "url": "https://arxiv.org/abs/2303.11366",
            "repo_url": None,
            "docs_url": None,
            "license": "arXiv preprint (open access metadata)",
            "maintenance_status": "published",
            "source_type": "research_paper",
            "taxonomy_tags": ["patch_planning", "autonomous_coding_failure_modes", "test_driven_repair"],
            "expected_learning_value": "Self-critique loops improve success rates in programming and decision tasks.",
            "specific_brain_capability_target": "evaluate_before_after",
            "cross_check_targets": ["react_yao_2022", "autocoderover_zhang_2024"],
            "safety_score_estimate": 61,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Good for self-improvement patterns. High citation count. Core idea is compact.",
        },
    ]


def _seed_repos_frameworks() -> list[dict]:
    """GitHub repos, framework docs, and tool candidates."""
    return [
        {
            "source_id": "firecracker_docs",
            "source_group": "framework",
            "title": "AWS Firecracker -- Secure and Fast MicroVMs for Serverless Computing",
            "authors_or_org": "AWS / Amazon",
            "year_or_first_release": "2018",
            "url": "https://firecracker-microvm.github.io/",
            "repo_url": "https://github.com/firecracker-microvm/firecracker",
            "docs_url": "https://firecracker-microvm.github.io/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "sandboxing_framework",
            "taxonomy_tags": ["code_execution_sandboxing", "tool_use_governance_for_coding", "autonomous_coding_failure_modes"],
            "expected_learning_value": "MicroVM technology for lightweight, secure isolation of untrusted code execution environments.",
            "specific_brain_capability_target": "avoid_untrusted",
            "cross_check_targets": ["gvisor_docs", "docker_security_docs"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source. Very fast boot. Good for ephemeral sandboxed agent execution.",
        },
        {
            "source_id": "owasp_llm_top10",
            "source_group": "docs",
            "title": "OWASP Top 10 for Large Language Model Applications",
            "authors_or_org": "OWASP Foundation",
            "year_or_first_release": "2023",
            "url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
            "repo_url": None,
            "docs_url": "https://owasp.org/www-project-top-10-for-large-language-model-applications/",
            "license": "CC-BY-SA-4.0",
            "maintenance_status": "active",
            "source_type": "security_reference",
            "taxonomy_tags": ["tool_use_governance_for_coding", "protected_file_boundaries", "autonomous_coding_failure_modes"],
            "expected_learning_value": "Systematic enumeration of LLM application risks including insecure output handling and excessive agency relevant to coding agents.",
            "specific_brain_capability_target": "integrate_governance",
            "cross_check_targets": ["brain_governance_front", "nist_ai_rmf"],
            "safety_score_estimate": 59,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Industry-standard risk taxonomy for LLM apps. Applies directly to autonomous coding agents.",
        },
        {
            "source_id": "swe_bench_repo",
            "source_group": "repo",
            "title": "SWE-bench -- Can Language Models Resolve Real-World GitHub Issues?",
            "authors_or_org": "Princeton NLP",
            "year_or_first_release": "2023",
            "url": "https://github.com/princeton-nlp/SWE-bench",
            "repo_url": "https://github.com/princeton-nlp/SWE-bench",
            "docs_url": "https://www.swebench.com/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "benchmark_repo",
            "taxonomy_tags": ["swe_bench_style_evaluation", "test_driven_repair", "regression_testing", "benchmark_driven_coding_agents"],
            "expected_learning_value": "Execution-based benchmark harness for evaluating real-world software engineering tasks.",
            "specific_brain_capability_target": "evaluate_agent",
            "cross_check_targets": ["swe_bench_jimenez_2023", "swe_agent_repo"],
            "safety_score_estimate": 66,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Gold standard harness. Active leaderboard. Strong methodology.",
        },
        {
            "source_id": "swe_agent_repo",
            "source_group": "repo",
            "title": "SWE-agent -- Agent-Computer Interfaces for Software Engineering",
            "authors_or_org": "Princeton NLP",
            "year_or_first_release": "2024",
            "url": "https://github.com/SWE-agent/SWE-agent",
            "repo_url": "https://github.com/SWE-agent/SWE-agent",
            "docs_url": "https://princeton-nlp.github.io/SWE-agent/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "coding_agent_repo",
            "taxonomy_tags": ["code_generation", "diff_generation", "tool_use_governance_for_coding", "code_execution_sandboxing"],
            "expected_learning_value": "Open-source coding agent with specialized computer interface for repository navigation and patch generation.",
            "specific_brain_capability_target": "generate_diff",
            "cross_check_targets": ["swe_agent_yang_2024", "swe_bench_repo"],
            "safety_score_estimate": 67,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Very active. Strong paper + repo alignment. Good for understanding agent interfaces.",
        },
        {
            "source_id": "openhands_repo",
            "source_group": "repo",
            "title": "OpenHands (formerly OpenDevin) -- Code Less, Make More",
            "authors_or_org": "All Hands AI",
            "year_or_first_release": "2024",
            "url": "https://github.com/All-Hands-AI/OpenHands",
            "repo_url": "https://github.com/All-Hands-AI/OpenHands",
            "docs_url": "https://docs.all-hands.dev/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "coding_agent_repo",
            "taxonomy_tags": ["code_generation", "codebase_navigation", "tool_use_governance_for_coding", "human_approval_gates_for_patches"],
            "expected_learning_value": "Modular agent framework for software development with multiple agent backends and sandboxed execution.",
            "specific_brain_capability_target": "inspect_repo",
            "cross_check_targets": ["swe_agent_repo", "aider_repo"],
            "safety_score_estimate": 64,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Active community. Modular design. Good for understanding multi-agent coding workflows.",
        },
        {
            "source_id": "aider_repo",
            "source_group": "repo",
            "title": "Aider -- AI Pair Programming in Your Terminal",
            "authors_or_org": "Paul Gauthier / aider",
            "year_or_first_release": "2023",
            "url": "https://github.com/paul-gauthier/aider",
            "repo_url": "https://github.com/paul-gauthier/aider",
            "docs_url": "https://aider.chat/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "coding_agent_repo",
            "taxonomy_tags": ["code_generation", "diff_generation", "repository_state_hygiene", "small_commit_discipline"],
            "expected_learning_value": "Terminal-based AI pair programming with automatic commit discipline and repository awareness.",
            "specific_brain_capability_target": "create_small_commits",
            "cross_check_targets": ["openhands_repo", "continue_dev_repo"],
            "safety_score_estimate": 63,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Popular for pair programming. Good commit discipline. Active development.",
        },
        {
            "source_id": "continue_dev_repo",
            "source_group": "repo",
            "title": "Continue.dev -- Open-Source AI Code Assistant for IDEs",
            "authors_or_org": "Continue Dev",
            "year_or_first_release": "2023",
            "url": "https://github.com/continuedev/continue",
            "repo_url": "https://github.com/continuedev/continue",
            "docs_url": "https://docs.continue.dev/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "coding_assistant_repo",
            "taxonomy_tags": ["code_generation", "codebase_navigation", "tool_use_governance_for_coding"],
            "expected_learning_value": "IDE-integrated AI assistant with context awareness and multi-model support.",
            "specific_brain_capability_target": "inspect_repo",
            "cross_check_targets": ["aider_repo", "openhands_repo"],
            "safety_score_estimate": 62,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Good for IDE integration patterns. Active development.",
        },
        {
            "source_id": "ruff_docs",
            "source_group": "docs",
            "title": "Ruff -- An Extremely Fast Python Linter and Code Formatter",
            "authors_or_org": "Astral",
            "year_or_first_release": "2022",
            "url": "https://docs.astral.sh/ruff/",
            "repo_url": "https://github.com/astral-sh/ruff",
            "docs_url": "https://docs.astral.sh/ruff/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "linting_tool_docs",
            "taxonomy_tags": ["linting_formatting", "static_analysis", "ci_validation"],
            "expected_learning_value": "Ultra-fast Python linter and formatter replacing Flake8, Black, isort, pydocstyle.",
            "specific_brain_capability_target": "run_static_checks",
            "cross_check_targets": ["semgrep_repo", "bandit_repo"],
            "safety_score_estimate": 64,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Very fast. Good for CI integration. Active development by Astral.",
        },
        {
            "source_id": "pytest_docs",
            "source_group": "docs",
            "title": "pytest -- Python Testing Framework",
            "authors_or_org": "pytest-dev",
            "year_or_first_release": "2008",
            "url": "https://docs.pytest.org/",
            "repo_url": "https://github.com/pytest-dev/pytest",
            "docs_url": "https://docs.pytest.org/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "testing_framework_docs",
            "taxonomy_tags": ["test_driven_repair", "regression_testing", "ci_validation"],
            "expected_learning_value": "Mature Python testing framework with fixtures, parametrization, plugins, and CI integration.",
            "specific_brain_capability_target": "run_tests",
            "cross_check_targets": ["swe_bench_repo", "pre_commit_docs"],
            "safety_score_estimate": 65,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Industry standard for Python testing. Essential for Brain's test-driven repair capability.",
        },
        {
            "source_id": "pre_commit_docs",
            "source_group": "docs",
            "title": "pre-commit -- A Framework for Managing and Maintaining Multi-Language Pre-Commit Hooks",
            "authors_or_org": "pre-commit",
            "year_or_first_release": "2014",
            "url": "https://pre-commit.com/",
            "repo_url": "https://github.com/pre-commit/pre-commit",
            "docs_url": "https://pre-commit.com/",
            "license": "MIT",
            "maintenance_status": "active",
            "source_type": "ci_tool_docs",
            "taxonomy_tags": ["linting_formatting", "ci_validation", "repository_state_hygiene"],
            "expected_learning_value": "Running checks (lint, format, tests) before each commit to maintain code quality.",
            "specific_brain_capability_target": "preserve_git_hygiene",
            "cross_check_targets": ["pytest_docs", "github_actions_security"],
            "safety_score_estimate": 63,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Good for maintaining repository hygiene. Widely adopted.",
        },
        {
            "source_id": "github_actions_security",
            "source_group": "docs",
            "title": "GitHub Actions Security Hardening",
            "authors_or_org": "GitHub",
            "year_or_first_release": "2019",
            "url": "https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions",
            "repo_url": None,
            "docs_url": "https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions",
            "license": "Proprietary (public reference)",
            "maintenance_status": "active",
            "source_type": "ci_security_docs",
            "taxonomy_tags": ["ci_validation", "repository_state_hygiene", "tool_use_governance_for_coding"],
            "expected_learning_value": "Best practices for securing CI/CD pipelines for code validation.",
            "specific_brain_capability_target": "preserve_git_hygiene",
            "cross_check_targets": ["pre_commit_docs", "docker_security_docs"],
            "safety_score_estimate": 58,
            "contrast_confidence": "medium",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "medium",
            "notes": "GitHub-specific but principles generalize. Good for CI security posture.",
        },
        {
            "source_id": "gvisor_docs",
            "source_group": "framework",
            "title": "gVisor -- Application Kernel for Sandboxing",
            "authors_or_org": "Google",
            "year_or_first_release": "2018",
            "url": "https://gvisor.dev/",
            "repo_url": "https://github.com/google/gvisor",
            "docs_url": "https://gvisor.dev/docs/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "sandboxing_framework",
            "taxonomy_tags": ["code_execution_sandboxing", "tool_use_governance_for_coding", "autonomous_coding_failure_modes"],
            "expected_learning_value": "Userspace kernel for isolating untrusted code execution during agent validation.",
            "specific_brain_capability_target": "avoid_untrusted",
            "cross_check_targets": ["docker_security_docs", "firecracker_docs"],
            "safety_score_estimate": 62,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source. Good for sandboxing generated code during testing.",
        },
        {
            "source_id": "docker_security_docs",
            "source_group": "docs",
            "title": "Docker Security Documentation",
            "authors_or_org": "Docker Inc",
            "year_or_first_release": "2013",
            "url": "https://docs.docker.com/engine/security/",
            "repo_url": None,
            "docs_url": "https://docs.docker.com/engine/security/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "container_security_docs",
            "taxonomy_tags": ["code_execution_sandboxing", "tool_use_governance_for_coding", "repository_state_hygiene"],
            "expected_learning_value": "Container security best practices for isolating coding agent execution environments.",
            "specific_brain_capability_target": "avoid_untrusted",
            "cross_check_targets": ["gvisor_docs", "firecracker_docs"],
            "safety_score_estimate": 60,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Standard reference for container security. Good for isolating agent builds/tests.",
        },
        {
            "source_id": "semgrep_repo",
            "source_group": "repo",
            "title": "Semgrep -- Lightweight Static Analysis for Many Languages",
            "authors_or_org": "Semgrep (r2c)",
            "year_or_first_release": "2020",
            "url": "https://github.com/returntocorp/semgrep",
            "repo_url": "https://github.com/returntocorp/semgrep",
            "docs_url": "https://semgrep.dev/docs/",
            "license": "LGPL-2.1",
            "maintenance_status": "active",
            "source_type": "static_analysis_tool",
            "taxonomy_tags": ["static_analysis", "linting_formatting", "ci_validation"],
            "expected_learning_value": "Fast static analysis with community and custom rule sets for security and correctness.",
            "specific_brain_capability_target": "run_static_checks",
            "cross_check_targets": ["bandit_repo", "ruff_docs"],
            "safety_score_estimate": 61,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "Open-source core with optional managed rules. Good for security scanning in CI.",
        },
        {
            "source_id": "bandit_repo",
            "source_group": "repo",
            "title": "Bandit -- Security Linter for Python",
            "authors_or_org": "PyCQA",
            "year_or_first_release": "2014",
            "url": "https://github.com/PyCQA/bandit",
            "repo_url": "https://github.com/PyCQA/bandit",
            "docs_url": "https://bandit.readthedocs.io/",
            "license": "Apache-2.0",
            "maintenance_status": "active",
            "source_type": "static_analysis_tool",
            "taxonomy_tags": ["static_analysis", "linting_formatting", "protected_file_boundaries"],
            "expected_learning_value": "Python-specific security linting: hardcoded passwords, unsafe eval, weak crypto.",
            "specific_brain_capability_target": "run_static_checks",
            "cross_check_targets": ["semgrep_repo", "ruff_docs"],
            "safety_score_estimate": 60,
            "contrast_confidence": "high",
            "acceptance_status": "accept",
            "ingestion_status": "not_ingested",
            "copyright_risk": "low",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "PyCQA project. Well-established. Good for Python security baseline in agent patches.",
        },
        {
            "source_id": "unknown_coding_blog",
            "source_group": "docs",
            "title": "10 AI Coding Tools You Must Use -- Unattributed Blog Post",
            "authors_or_org": "unknown",
            "year_or_first_release": "unknown",
            "url": "https://example-blog.com/ai-coding",
            "repo_url": None,
            "docs_url": None,
            "license": "unknown",
            "maintenance_status": "unknown",
            "source_type": "blog_post",
            "taxonomy_tags": ["code_generation"],
            "expected_learning_value": "Generic listicle. No methodology depth.",
            "specific_brain_capability_target": "inspect_repo",
            "cross_check_targets": ["swe_bench_jimenez_2023"],
            "safety_score_estimate": 20,
            "contrast_confidence": "low",
            "acceptance_status": "reject",
            "ingestion_status": "not_ingested",
            "copyright_risk": "medium",
            "unsafe_code_execution_risk": "low",
            "repo_state_corruption_risk": "low",
            "vendor_lock_in_risk": "low",
            "notes": "No attribution. No evidence. SEO content. Reject.",
        },
    ]


def seed_candidate_sources() -> list[dict]:
    return _seed_papers_benchmarks() + _seed_repos_frameworks()


def cross_source_contrast_matrix() -> list[dict]:
    """Cross-source contrast for selected pairs."""
    return [
        {
            "pair": ["swe_bench_jimenez_2023", "swe_bench_repo"],
            "contrast_type": "paper vs benchmark repo",
            "confirms": "Execution-based evaluation prevents hallucinated code fixes.",
            "contradicts": None,
            "complements": "Repo provides the harness, leaderboard, and dataset construction tools.",
            "unresolved_questions": "How generalizable is SWE-bench to non-Python codebases?",
            "confidence_level": "high",
        },
        {
            "pair": ["swe_agent_yang_2024", "swe_agent_repo"],
            "contrast_type": "paper vs implementation",
            "confirms": "Agent-computer interface design is a stronger lever than model scale.",
            "contradicts": None,
            "complements": "Repo provides the actual interface implementations and benchmark harness.",
            "unresolved_questions": "Can SWE-agent interfaces generalize to non-software-engineering tasks?",
            "confidence_level": "high",
        },
        {
            "pair": ["human_eval_chen_2021", "mbpp_austin_2021"],
            "contrast_type": "code generation benchmark vs code generation benchmark",
            "confirms": "Both measure functional correctness of synthesized Python programs.",
            "contradicts": None,
            "complements": "HumanEval is simpler function-level; MBPP has more diverse problem descriptions.",
            "unresolved_questions": "Which benchmark better predicts real-world coding agent performance?",
            "confidence_level": "high",
        },
        {
            "pair": ["autocoderover_zhang_2024", "swe_agent_yang_2024"],
            "contrast_type": "autonomous repair paper vs agent interface paper",
            "confirms": "Iterative retrieval and feedback improve patch generation.",
            "contradicts": None,
            "complements": "AutoCodeRover focuses on iterative context retrieval; SWE-agent focuses on interface design.",
            "unresolved_questions": "Which approach is more sample-efficient?",
            "confidence_level": "medium",
        },
        {
            "pair": ["aider_repo", "openhands_repo"],
            "contrast_type": "pair programming tool vs modular agent framework",
            "confirms": "Both provide AI-assisted code generation with repository awareness.",
            "contradicts": None,
            "complements": "Aider is terminal-focused with commit discipline; OpenHands is modular with sandboxed execution.",
            "unresolved_questions": "Which tool produces higher-quality patches on average?",
            "confidence_level": "medium",
        },
        {
            "pair": ["ruff_docs", "semgrep_repo"],
            "contrast_type": "formatter/linter vs security analyzer",
            "confirms": "Both improve code quality through automated static analysis.",
            "contradicts": None,
            "complements": "Ruff is extremely fast for style and simple errors; Semgrep is slower but finds complex security issues.",
            "unresolved_questions": "Can Ruff and Semgrep be run in parallel without conflicts?",
            "confidence_level": "high",
        },
        {
            "pair": ["pytest_docs", "pre_commit_docs"],
            "contrast_type": "testing framework vs git hook framework",
            "confirms": "Both are essential for maintaining code quality in development workflows.",
            "contradicts": None,
            "complements": "pytest runs tests; pre-commit orchestrates checks (including pytest) before each commit.",
            "unresolved_questions": "What is the optimal pre-commit check order for Python projects?",
            "confidence_level": "high",
        },
        {
            "pair": ["gvisor_docs", "docker_security_docs"],
            "contrast_type": "userspace sandbox vs container security",
            "confirms": "Both provide isolation for untrusted code execution.",
            "contradicts": None,
            "complements": "gVisor adds userspace kernel isolation; Docker security docs describe standard container hardening.",
            "unresolved_questions": "What is the performance overhead of gVisor for typical Python test suites?",
            "confidence_level": "medium",
        },
        {
            "pair": ["react_yao_2022", "reflexion_shinn_2023"],
            "contrast_type": "reasoning-action paper vs self-critique paper",
            "confirms": "Both improve agent performance through structured reasoning loops.",
            "contradicts": None,
            "complements": "ReAct interleaves reasoning with action; Reflexion adds explicit self-evaluation after failure.",
            "unresolved_questions": "Can ReAct and Reflexion be combined into a single agent architecture?",
            "confidence_level": "medium",
        },
    ]


def knowledge_record_schema() -> dict:
    return {
        "description": "Schema for a future knowledge record if ingestion is ever authorized.",
        "required_fields": [
            "source_id",
            "source_group",
            "title",
            "authors_or_org",
            "url",
            "taxonomy_tags",
            "specific_brain_capability_target",
            "safety_score",
            "acceptance_status",
            "ingestion_status",
            "copyright_risk",
            "unsafe_code_execution_risk",
            "repo_state_corruption_risk",
            "vendor_lock_in_risk",
        ],
        "optional_fields": [
            "repo_url",
            "docs_url",
            "license",
            "maintenance_status",
            "year_or_first_release",
            "expected_learning_value",
            "cross_check_targets",
            "contrast_confidence",
            "notes",
        ],
        "forbidden_fields": [
            "full_text",
            "raw_pdf_bytes",
            "full_readme_text",
            "proprietary_dataset",
            "api_keys",
            "credentials",
            "exploit_code",
            "malware_samples",
            "untrusted_executable",
        ],
        "retention_policy": "Metadata and summary only. Full content must remain external. No untrusted code execution.",
    }


def build_curated_learning_plan() -> dict:
    sources = seed_candidate_sources()
    taxonomy = canonical_taxonomy()
    contrast = cross_source_contrast_matrix()
    cap_map = brain_coding_capability_map()
    accepted = [s for s in sources if s["acceptance_status"] == "accept"]
    hold = [s for s in sources if s["acceptance_status"] == "hold"]
    rejected = [s for s in sources if s["acceptance_status"] == "reject"]
    return {
        "front_id": front_id(),
        "domain": learning_domain(),
        "taxonomy": taxonomy,
        "acceptance_criteria": source_acceptance_criteria(),
        "rejection_criteria": source_rejection_criteria(),
        "safety_rubric": source_safety_scoring_rubric(),
        "contrast_rubric": source_contrast_scoring_rubric(),
        "brain_coding_capability_map": cap_map,
        "sources": sources,
        "cross_source_contrast_matrix": contrast,
        "knowledge_record_schema": knowledge_record_schema(),
        "summary": {
            "source_count": len(sources),
            "taxonomy_count": len(taxonomy),
            "capability_map_count": len(cap_map),
            "source_groups": list({s["source_group"] for s in sources}),
            "accepted_count": len(accepted),
            "hold_count": len(hold),
            "rejected_count": len(rejected),
            "ingestion_status": "dry_run_only",
            "memory_mutated": False,
            "faiss_mutated": False,
        },
    }


def summarize_curated_learning_plan() -> dict:
    plan = build_curated_learning_plan()
    return {
        "front_id": plan["front_id"],
        "domain": plan["domain"]["id"],
        "source_count": plan["summary"]["source_count"],
        "taxonomy_count": plan["summary"]["taxonomy_count"],
        "capability_map_count": plan["summary"]["capability_map_count"],
        "source_groups": plan["summary"]["source_groups"],
        "accepted_count": plan["summary"]["accepted_count"],
        "hold_count": plan["summary"]["hold_count"],
        "rejected_count": plan["summary"]["rejected_count"],
        "ingestion_status": plan["summary"]["ingestion_status"],
        "memory_mutated": plan["summary"]["memory_mutated"],
        "faiss_mutated": plan["summary"]["faiss_mutated"],
    }


def assert_no_memory_or_faiss_mutation(before: dict, after: dict) -> dict:
    """Compare before/after inventory dicts. Returns pass/fail details."""
    checks = {
        "semantic_memory_jsonl_sha": before.get("semantic_memory_jsonl", {}).get("sha256") == after.get("semantic_memory_jsonl", {}).get("sha256"),
        "semantic_memory_jsonl_lines": before.get("semantic_memory_jsonl", {}).get("line_count") == after.get("semantic_memory_jsonl", {}).get("line_count"),
        "faiss_index_sha": before.get("semantic_memory_faiss_index", {}).get("sha256") == after.get("semantic_memory_faiss_index", {}).get("sha256"),
        "faiss_ids_sha": before.get("semantic_memory_faiss_ids", {}).get("sha256") == after.get("semantic_memory_faiss_ids", {}).get("sha256"),
        "faiss_ids_count": before.get("semantic_memory_faiss_ids", {}).get("id_count") == after.get("semantic_memory_faiss_ids", {}).get("id_count"),
    }
    all_pass = all(checks.values())
    return {
        "pass": all_pass,
        "checks": checks,
        "before_summary": {k: before.get(k, {}).get("sha256", before.get(k, {}).get("line_count", before.get(k, {}).get("id_count"))) for k in before if k not in ("timestamp", "head")},
        "after_summary": {k: after.get(k, {}).get("sha256", after.get(k, {}).get("line_count", after.get(k, {}).get("id_count"))) for k in after if k not in ("timestamp", "head")},
    }
