"""
Shadow retrieval check.
"""
import json, sys
from pathlib import Path
sys.path.insert(0, "tmp_agent")
from brain_v9.core.semantic_memory_faiss import SemanticMemoryFAISS

mem = SemanticMemoryFAISS(root=Path("tmp_agent/front_brain_canonical_memory_promotion_execute_approved_01/shadow"))
mem._ensure_index_loaded()

records = []
with open("tmp_agent/front_brain_canonical_memory_promotion_execute_approved_01/dry_run_promotion_records.jsonl",encoding="utf-8") as f:
    for line in f:
        line=line.strip()
        if not line:
            continue
        records.append(json.loads(line))

all_ok = True
for rec in records:
    hits = mem.search(rec["summary"], top_k=5)
    hit_ids = {h.get("id") for h in hits}
    print(f"{rec['id']} top_ids={hit_ids}")
    # The actual record id is inside metadata, because the canonical semantic_memory.jsonl contains our custom id
    # We need to check if any hit has id matching the generated sha id.
    # Actually, ingest_text generates a record_id from hash. Our records have an 'id' field that was placed in metadata.
    # The canonical semantic_memory.jsonl line has "id":"...", which is the sha256-based id generated by ingest_text.
    # So we need to map the original 'id' to the canonical id.
    # For simplicity, let's check that the summary text appears in the hit snippets.
    found = any(rec["summary"].lower() in (h.get("snippet","").lower()) for h in hits)
    if not found:
        print(f"FAIL: {rec['id']} not retrievable by summary")
        all_ok = False
    else:
        print(f"OK: {rec['id']} retrievable")

if all_ok:
    print("RETRIEVAL_OK")
else:
    print("RETRIEVAL_FAIL")
    sys.exit(1)
