"""
Smoke test for FRONT-BRAIN-CANONICAL-MEMORY-PROMOTION-EXECUTE-APPROVED-01.
Tests canonical semantic memory and FAISS after promotion.
"""
import json, os
import pytest

EVIDENCE_DIR = "tmp_agent/front_brain_canonical_memory_promotion_execute_approved_01"
SHADOW_DIR = os.path.join(EVIDENCE_DIR, "shadow")

# Phase 0 state lock exists
def test_01_state_lock_exists():
    assert os.path.isfile(os.path.join(EVIDENCE_DIR, "state_lock.json"))

# Approval source verification exists
def test_02_approval_source_verify_exists():
    assert os.path.isfile(os.path.join(EVIDENCE_DIR, "approval_source_verify.json"))

# Backup exists
def test_03_backup_dir_exists():
    dirs = [d for d in os.listdir("memory/rollback_snapshots") if d.startswith("canonical_promotion_execute_approved_01_")]
    assert len(dirs) >= 1

# Dry run records exist
def test_04_dry_run_records_exist():
    assert os.path.isfile(os.path.join(EVIDENCE_DIR, "dry_run_promotion_records.jsonl"))
    with open(os.path.join(EVIDENCE_DIR, "dry_run_promotion_records.jsonl"),encoding="utf-8") as f:
        lines = [l for l in f if l.strip()]
    assert len(lines) == 5

# Shadow files exist
def test_05_shadow_files_exist():
    assert os.path.isfile(os.path.join(SHADOW_DIR, "semantic_memory.jsonl"))
    assert os.path.isfile(os.path.join(SHADOW_DIR, "semantic_memory_faiss.index"))
    assert os.path.isfile(os.path.join(SHADOW_DIR, "semantic_memory_faiss_ids.json"))

# Shadow record count increased by 5
def test_06_shadow_record_count():
    with open(os.path.join(SHADOW_DIR, "semantic_memory.jsonl"),encoding="utf-8") as f:
        lines = [l for l in f if l.strip()]
    assert len(lines) == 1720

# Shadow FAISS count increased by 5
def test_07_shadow_faiss_count():
    import faiss
    idx = faiss.read_index(os.path.join(SHADOW_DIR, "semantic_memory_faiss.index"))
    assert idx.ntotal == 1621

# Shadow IDs count increased by 5
def test_08_shadow_ids_count():
    with open(os.path.join(SHADOW_DIR, "semantic_memory_faiss_ids.json"),encoding="utf-8") as f:
        ids = json.load(f)
    assert len(ids) == 1621

# Canonical semantic record count is 1720
def test_09_canonical_record_count():
    with open("memory/semantic/semantic_memory.jsonl",encoding="utf-8") as f:
        lines = [l for l in f if l.strip()]
    assert len(lines) == 1720

# Canonical FAISS count is 1621
def test_10_canonical_faiss_count():
    import faiss
    idx = faiss.read_index("memory/semantic/semantic_memory_faiss.index")
    assert idx.ntotal == 1621

# Canonical IDs count is 1621
def test_11_canonical_ids_count():
    with open("memory/semantic/semantic_memory_faiss_ids.json",encoding="utf-8") as f:
        ids = json.load(f)
    assert len(ids) == 1621

# Canonical last 5 records contain canonical_promoted kind
def test_12_new_records_are_canonical_promoted():
    with open("memory/semantic/semantic_memory.jsonl",encoding="utf-8") as f:
        lines = [l for l in f if l.strip()]
    for line in lines[-5:]:
        rec = json.loads(line)
        assert rec.get("kind") == "canonical_promoted"
        assert rec.get("source") == "canonical_memory_promotion"

# New IDs present in canonical FAISS ids list
def test_13_new_ids_in_canonical_faiss_ids():
    with open("memory/semantic/semantic_memory_faiss_ids.json",encoding="utf-8") as f:
        ids = json.load(f)
    # IDs generated by ingest_text hash - we know them from canonical_faiss_update.py output
    expected_ids = [
        "13792dba579afd64b72195fa",
        "8480c034d7c754e54f10d6a8",
        "cefdf682c3559f04ee571102",
        "5eb050fcc96b08da864ec66f",
        "62bed9a5eb0db6ea71afa604"
    ]
    for eid in expected_ids:
        assert eid in ids, f"Missing {eid}"

# Retrieval sanity check on canonical
def test_14_retrieval_on_canonical():
    import sys
    sys.path.insert(0, "tmp_agent")
    from brain_v9.core.semantic_memory_faiss import SemanticMemoryFAISS
    mem = SemanticMemoryFAISS(root="memory/semantic")
    mem._ensure_index_loaded()
    summaries = [
        "Fallback must remain visible in reports and dashboard instead of being hidden as provider success.",
        "Canonical semantic promotion requires snapshot, shadow index, rollback verification, and small batch gate.",
        "Dashboard recovery should use safe port 8092 to avoid touching 8090 or destabilizing 8091.",
        "Kimi K2.6 provider_probe on 8091 is available and returns fast governed metadata.",
        "Persistent autonomy must run bounded cycles with STOP and PAUSE controls before any scheduler escalation."
    ]
    for s in summaries:
        hits = mem.search(s, top_k=5)
        assert len(hits) > 0, f"No hits for: {s}"

# Semantic hash changed from baseline (expected)
def test_15_semantic_hash_changed_expected():
    import hashlib
    with open("memory/semantic/semantic_memory.jsonl","rb") as f:
        current_sha = hashlib.sha256(f.read()).hexdigest()
    # Baseline was ce81fbe1f97e257e2b124d7a929f0b2af86ce61e9ff1d8d832fdb5da1f69e64e
    assert current_sha != "ce81fbe1f97e257e2b124d7a929f0b2af86ce61e9ff1d8d832fdb5da1f69e64e"

# No secrets or raw CoT in new records
def test_16_no_secrets_or_raw_cot():
    with open("memory/semantic/semantic_memory.jsonl",encoding="utf-8") as f:
        lines = [l for l in f if l.strip()]
    for line in lines[-5:]:
        rec = json.loads(line)
        text = rec.get("text","")
        assert "-----BEGIN" not in text
        assert "token" not in text.lower() or "returns fast governed metadata" in text
        assert "cot" not in text.lower()

# Semantic/FAISS count consistency
def test_17_consistency_semantic_vs_faiss():
    with open("memory/semantic/semantic_memory.jsonl",encoding="utf-8") as f:
        sem_count = len([l for l in f if l.strip()])
    import faiss
    idx = faiss.read_index("memory/semantic/semantic_memory_faiss.index")
    with open("memory/semantic/semantic_memory_faiss_ids.json",encoding="utf-8") as f:
        ids_count = len(json.load(f))
    assert idx.ntotal == ids_count
    assert sem_count == 1720
    assert idx.ntotal == 1621

# Evidence directory contains shadow validation artifact
def test_18_shadow_validation_exists():
    assert os.path.isfile(os.path.join(EVIDENCE_DIR, "shadow_validation.json"))
