import test from "node:test";
import assert from "node:assert/strict";
import {AgentLoopBuilderAdapter} from "../../../scripts/operator_proxy/agent_loop_builder_adapter.js";
import {agentLoopIssueBody} from "../../../scripts/operator_proxy/spec_contract.js";
import type {ProxySpec} from "../../../scripts/operator_proxy/types.js";

const base="a".repeat(40),head="b".repeat(40),forbidden=["memory/semantic/","memory/rollback","tmp_agent/state/","tmp_agent/brain_v9/trading/","financial_autonomy/","tmp_agent/brain_v9/core/session.py"];
const spec:ProxySpec={schema_version:1,authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",roadmap_id:"BRAIN-101",roadmap_version:"1.0.0-reconstructed-glm-harmonized",roadmap_item_id:"R1.9",expected_base_sha:base,executor:"agent_loop",risk:"LOW",allowed_paths:["tests/contract/synthetic.py"],forbidden_paths:forbidden,acceptance:["pass"],test_commands:["git diff --check"],deployment_allowed:false,objective:"synthetic",work_branch:"agent/test-only-brain-101-synthetic",dependencies:["R0"],deployment_mode:"NO_DEPLOY",front_id:"BRAIN-101-R1-KIMI-SYNTHETIC-01",roadmap_sha256:"c".repeat(64),manifest_sha256:"d".repeat(64),test_profile:"test-only",max_executor_cycles:2};

const trustedPr=(overrides:any={})=>({number:71,state:"OPEN",isDraft:true,isCrossRepository:false,author:{login:"cesarmanuel8102"},headRepository:{nameWithOwner:"cesarmanuel8102/AI_Vault"},baseRefName:"codex/own-capital-sustainable-return",baseRefOid:base,headRefName:spec.work_branch,headRefOid:head,body:`AGENT_LOOP_FRONT: ${spec.front_id}\nAGENT_LOOP_ISSUE: #70\n`,...overrides});
function fixture(options:any={}){let issues=0,labels=0,binds=0;const candidates=options.candidates??(options.noPr?[]:[trustedPr({headRefOid:options.head??head})]);const bus:any={createGovernedIssue:(_t:string,_b:string,label:string)=>{issues++;assert.equal(label,"agent:queued");return 70;},issueSnapshot:()=>({state:"OPEN",body:agentLoopIssueBody(spec),labels:options.labels??[]}),reconcileLabel:()=>{labels++;},prCandidatesByBranch:()=>candidates,prIdentity:()=>options.pr??trustedPr({headRefOid:options.head??head}),bindPrToIssue:()=>{binds++;}};return {adapter:new AgentLoopBuilderAdapter(bus),counts:()=>({issues,labels,binds})};}

test("agent loop item creates one worker-parseable queued Issue",()=>{const f=fixture();assert.equal(f.adapter.ensureIssue(spec,[]),70);assert.deepEqual(f.counts(),{issues:1,labels:0,binds:0});});
test("existing Issue is reused and queued exactly once only when phase is absent",()=>{const f=fixture();assert.equal(f.adapter.ensureIssue(spec,[70]),70);assert.equal(f.counts().labels,1);const queued=fixture({labels:["agent:queued"]});queued.adapter.ensureIssue(spec,[70]);assert.equal(queued.counts().labels,0);});
test("worker absence is recoverable without duplicate Issue or PR effects",()=>{const f=fixture({noPr:true,labels:["agent:queued"]});assert.equal(f.adapter.ensureIssue(spec,[70]),70);assert.equal(f.adapter.observe(spec,70,0),"PENDING");assert.equal(f.adapter.observe(spec,70,0),"PENDING");assert.deepEqual(f.counts(),{issues:0,labels:0,binds:0});});
test("duplicate, terminal, ambiguous, or hostile Issues fail closed",()=>{assert.throws(()=>fixture().adapter.ensureIssue(spec,[70,72]),/duplicate/);assert.throws(()=>fixture({labels:["loop:blocked"]}).adapter.ensureIssue(spec,[70]),/terminal/);assert.throws(()=>fixture({labels:["agent:queued","loop:executing"]}).adapter.ensureIssue(spec,[70]),/ambiguous/);const f=fixture();(f.adapter as any).bus.issueSnapshot=()=>({state:"OPEN",body:agentLoopIssueBody(spec).replace(spec.front_id!,"HOSTILE-FRONT"),labels:[]});assert.throws(()=>f.adapter.ensureIssue(spec,[70]),/mismatch/);});
test("adapter waits for worker PR and binds only exact Draft identity",()=>{assert.equal(fixture({noPr:true}).adapter.observe(spec,70,0),"PENDING");const f=fixture(),result=f.adapter.observe(spec,70,0);assert.deepEqual(result,{pr:71,head_sha:head,session:`agent-loop-builder-${head}`});assert.equal(f.counts().binds,1);for(const drift of [{headRefOid:"c".repeat(40)},{body:"hostile"}])assert.throws(()=>fixture({pr:trustedPr(drift)}).adapter.observe(spec,70,0),/identity|evidence/);});
test("untrusted or ambiguous PR candidates cause zero external mutations",()=>{const hostile=[{name:"fork with identical branch",patch:{isCrossRepository:true,headRepository:{nameWithOwner:"attacker/AI_Vault"}}},{name:"different repository",patch:{headRepository:{nameWithOwner:"other/AI_Vault"}}},{name:"wrong author",patch:{author:{login:"attacker"}}},{name:"wrong base branch",patch:{baseRefName:"main"}},{name:"wrong base sha",patch:{baseRefOid:"c".repeat(40)}},{name:"not draft",patch:{isDraft:false}},{name:"closed",patch:{state:"CLOSED"}}];for(const item of hostile){const f=fixture({candidates:[trustedPr(item.patch)]});assert.throws(()=>f.adapter.observe(spec,70,0),/candidate count/,item.name);assert.deepEqual(f.counts(),{issues:0,labels:0,binds:0});}const duplicate=fixture({candidates:[trustedPr(),trustedPr({number:72})]});assert.throws(()=>duplicate.adapter.observe(spec,70,0),/candidate count/);assert.equal(duplicate.counts().binds,0);});
test("one trusted candidate wins over a discarded hostile fork",()=>{const f=fixture({candidates:[trustedPr({isCrossRepository:true,headRepository:{nameWithOwner:"attacker/AI_Vault"}}),trustedPr()]});const result=f.adapter.observe(spec,70,0);assert.deepEqual(result,{pr:71,head_sha:head,session:`agent-loop-builder-${head}`});assert.equal(f.counts().binds,1);});
test("missing PR after worker CI phase blocks instead of polling forever",()=>{const f=fixture({noPr:true,labels:["loop:ci"]});assert.throws(()=>f.adapter.observe(spec,70,0),/candidate count/);assert.equal(f.counts().binds,0);});
test("Issue mutation after admission blocks PR observation",()=>{const f=fixture();(f.adapter as any).bus.issueSnapshot=()=>({state:"OPEN",body:agentLoopIssueBody(spec).replace(spec.front_id!,"HOSTILE-FRONT"),labels:["loop:ci"]});assert.throws(()=>f.adapter.observe(spec,70,0),/mismatch/);assert.equal(f.counts().binds,0);});
test("repair waits for a new worker head and records a distinct builder session",()=>{assert.equal(fixture().adapter.observe(spec,70,1,head),"PENDING");const next="c".repeat(40),result=fixture({head:next}).adapter.observe(spec,70,1,head);assert.equal((result as any).session,`agent-loop-builder-${next}`);assert.notEqual((result as any).session,"reviewer-session");});
