import test from "node:test";import assert from "node:assert/strict";import {mkdtempSync,readFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";
import {AutonomousFlow,type AutonomousEffects} from "../../../scripts/operator_proxy/autonomous_flow.js";import {LifecycleStore} from "../../../scripts/operator_proxy/lifecycle_store.js";import type {ProxySpec,ReviewerOutput} from "../../../scripts/operator_proxy/types.js";
const spec:ProxySpec={schema_version:1,authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",roadmap_id:"BRAIN-101",roadmap_version:"1.0.0-reconstructed-glm-harmonized",roadmap_item_id:"R1.9",expected_base_sha:"a".repeat(40),executor:"codex_control_plane",risk:"LOW",allowed_paths:["docs/synthetic.md"],forbidden_paths:["trading/"],acceptance:["pass"],test_commands:["git diff --check"],deployment_allowed:false,objective:"synthetic",work_branch:"control-plane/synthetic",dependencies:["R0"],deployment_mode:"NO_DEPLOY",front_id:"BRAIN-101-R1-SYNTHETIC-01"};
function fixture(reviewVerdicts:("PASS"|"CHANGES_REQUESTED"|"BLOCKED")[]=["PASS"]){let issueCalls=0,buildCalls=0,mergeCalls=0,closeoutCalls=0,nextCalls=0,reviewCalls=0;const sessions:{builder:string[];reviewer:string[]}={builder:[],reviewer:[]};const effects:AutonomousEffects={bindLifecycle:()=>{},ensureIssue:()=>{issueCalls++;return 70;},ensureBuild:(_s,_i,session,cycle)=>{buildCalls++;sessions.builder.push(session);return {pr:71,head_sha:(cycle+1).toString(16).repeat(40),session};},ci:()=>"PASS",review:(_p,head,session)=>{sessions.reviewer.push(session);const verdict=reviewVerdicts[Math.min(reviewCalls++,reviewVerdicts.length-1)];return {verdict,head_sha:head,summary:verdict,findings:verdict==="CHANGES_REQUESTED"?[{severity:"P2",title:"bounded repair",evidence:"fixture",required_correction:"repair"}]:[]} as ReviewerOutput;},policy:(_s,_i,_p,_h,review,_b,_r,_c)=>({outcome:review.verdict==="PASS"?"APPROVE":review.verdict==="CHANGES_REQUESTED"?"REPAIR":"BLOCK",decision_id:crypto.randomUUID()}),ensureMerge:()=>{mergeCalls++;return "f".repeat(40);},ensureInstall:()=>"PASS",ensureRuntimePilot:()=>"PASS",ensureCloseout:()=>{closeoutCalls++;return "PASS";},discoverNext:()=>{nextCalls++;}};return {effects,counts:()=>({issueCalls,buildCalls,mergeCalls,closeoutCalls,nextCalls}),sessions};}
function drive(flow:AutonomousFlow,max=40){let state;for(let i=0;i<max;i++){state=flow.step(spec);if(state.state==="TERMINAL_COMPLETED")break;}return state!;}
test("synthetic LOW flow completes without owner or runtime model dependency",()=>{const f=fixture();const store=new LifecycleStore(mkdtempSync(join(tmpdir(),"flow-")));const state=drive(new AutonomousFlow(store,f.effects));assert.equal(state.state,"TERMINAL_COMPLETED");assert.deepEqual(f.counts(),{issueCalls:1,buildCalls:1,mergeCalls:1,closeoutCalls:1,nextCalls:0});new AutonomousFlow(store,f.effects).step(spec);assert.equal(f.counts().nextCalls,1);assert.notEqual(f.sessions.builder[0],f.sessions.reviewer[0]);});
test("restart resumes persisted state without duplicating Issue",()=>{const f=fixture();const root=mkdtempSync(join(tmpdir(),"flow-"));let flow=new AutonomousFlow(new LifecycleStore(root),f.effects);flow.step(spec);flow.step(spec);flow.step(spec);assert.equal(f.counts().issueCalls,1);flow=new AutonomousFlow(new LifecycleStore(root),f.effects);drive(flow);assert.equal(f.counts().issueCalls,1);assert.equal(JSON.parse(readFileSync(join(root,`${spec.front_id}.json`),"utf8")).state,"TERMINAL_COMPLETED");});
test("repair uses fresh builder and reviewer sessions and same PR",()=>{const f=fixture(["CHANGES_REQUESTED","CHANGES_REQUESTED","PASS"]);const state=drive(new AutonomousFlow(new LifecycleStore(mkdtempSync(join(tmpdir(),"flow-"))),f.effects));assert.equal(state.state,"TERMINAL_COMPLETED");assert.equal(f.counts().buildCalls,3);assert.equal(new Set(f.sessions.builder).size,3);assert.equal(new Set(f.sessions.reviewer).size,3);assert.equal(state.repair_cycles,2);});
test("third requested repair blocks",()=>{const f=fixture(["CHANGES_REQUESTED"]);const state=drive(new AutonomousFlow(new LifecycleStore(mkdtempSync(join(tmpdir(),"flow-"))),f.effects));assert.equal(state.state,"BLOCKED");assert.equal(state.last_error,"REPAIR_LIMIT_REACHED");assert.equal(f.counts().mergeCalls,0);});
test("UAC escalation is resumable only from exact persisted reason",()=>{const f=fixture();const elevatedSpec={...spec,deployment_mode:"INSTALL_ONLY" as const,front_id:"BRAIN-101-R1-INSTALL-01"};f.effects.ensureInstall=()=>"LOCAL_PRIVILEGE_REQUIRED";const store=new LifecycleStore(mkdtempSync(join(tmpdir(),"flow-")));const flow=new AutonomousFlow(store,f.effects);let state;for(let i=0;i<30;i++){state=flow.step(elevatedSpec);if(state.state==="ESCALATED")break;}assert.equal(state!.last_error,"LOCAL_PRIVILEGE_REQUIRED");assert.equal(flow.resumePrivilegedInstall(elevatedSpec.front_id!).state,"INSTALL_PENDING");assert.throws(()=>flow.resumePrivilegedInstall(elevatedSpec.front_id!));});
test("lifecycle rejects binding drift after restart",()=>{const f=fixture();const store=new LifecycleStore(mkdtempSync(join(tmpdir(),"flow-")));const flow=new AutonomousFlow(store,f.effects);flow.step(spec);assert.throws(()=>flow.step({...spec,expected_base_sha:"b".repeat(40)}),/binding mismatch/);});
