import test from "node:test";import assert from "node:assert/strict";import {execFileSync} from "node:child_process";import {mkdirSync,mkdtempSync,writeFileSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";
import {GovernedBuilder,parseTestCommand} from "../../../scripts/operator_proxy/governed_builder.js";import {validateSpec,agentLoopIssueBody} from "../../../scripts/operator_proxy/spec_contract.js";import type {ProxySpec} from "../../../scripts/operator_proxy/types.js";
const spec:ProxySpec={schema_version:1,authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",roadmap_id:"BRAIN-101",roadmap_version:"1.0.0-reconstructed-glm-harmonized",roadmap_item_id:"R1.9",expected_base_sha:"a".repeat(40),executor:"codex_control_plane",risk:"LOW",allowed_paths:["docs/x.md"],forbidden_paths:["trading/"],acceptance:["pass"],test_commands:["git diff --check"],deployment_allowed:false,objective:"x",work_branch:"control-plane/synthetic-x",dependencies:["R0"],deployment_mode:"NO_DEPLOY",front_id:"BRAIN-101-R1-SYNTHETIC-01"};
for(const command of ["git diff --check","npm test","npm.cmd run typecheck","python -m pytest tests/contract/test_x.py -q","python tests/contract/test_x.py","pwsh -NoProfile -File tests/contract/test_x.ps1"])test(`safe structured test command: ${command}`,()=>assert.equal(parseTestCommand(command)[0],command.split(" ")[0]));
for(const command of ["git push origin main","git reset --hard","npm exec evil","python -c print(1)","python ../evil.py","pwsh -Command evil","cmd /c test","git diff --check; whoami","python C:/evil.py"])test(`dangerous test command denied: ${command}`,()=>assert.throws(()=>parseTestCommand(command)));
test("spec rejects traversal, absolute paths, and ambiguous branches",()=>{for(const path of ["../x","C:/x","/x","docs\\x","docs//x"])assert.throws(()=>validateSpec({...spec,allowed_paths:[path]},true),/path invalid/);for(const branch of ["control-plane/a..b","control-plane/a//b","feature/x"])assert.throws(()=>validateSpec({...spec,work_branch:branch},true));});
test("agent loop issue carries both governed contracts",()=>{const agent={...spec,executor:"agent_loop" as const,test_profile:"test-only" as const,max_executor_cycles:2,roadmap_sha256:"b".repeat(64),manifest_sha256:"c".repeat(64)};const body=agentLoopIssueBody(agent);assert.match(body,/OPERATOR_PROXY_SPEC/);assert.match(body,/AGENT_LOOP_SPEC/);assert.match(body,/"test_profile": "test-only"/);assert.match(body,/"human_final_authority": true/);});
test("agent loop issue fails closed without runtime profile metadata",()=>assert.throws(()=>agentLoopIssueBody({...spec,executor:"agent_loop"}),/metadata missing/));
test("closeout contract rejects incomplete and unsafe metadata",()=>{const closeout={front_id:"BRAIN-101-R1-CLOSEOUT-01",objective:"close",work_branch:"control-plane/closeout",executor:"codex_control_plane" as const,risk:"LOW" as const,allowed_paths:["docs/x.md"],forbidden_paths:[],acceptance:["pass"],test_commands:["git diff --check"]};assert.doesNotThrow(()=>validateSpec({...spec,closeout},true));assert.throws(()=>validateSpec({...spec,closeout:{...closeout,acceptance:[]}},true),/closeout invalid/);assert.throws(()=>validateSpec({...spec,closeout:{...closeout,allowed_paths:["../x"]}},true),/closeout invalid/);});
test("orphan published branch becomes a Draft PR without rerunning builder",()=>{let created=0,bound=0;const head="b".repeat(40);const bus={findPrByBranch:()=>undefined,remoteBranchHead:()=>head,createDraftPr:()=>{created++;return 91;},bindPrToIssue:()=>{bound++;},repairPrompt:()=>""};const builder=new GovernedBuilder("unused","unused",bus as any,()=>{},"must-not-run");assert.deepEqual(builder.build(spec,90,"builder-session",0),{pr:91,head_sha:head,session:"builder-session"});assert.equal(created,1);assert.equal(bound,1);});
function recoveryRepo(){const root=mkdtempSync(join(tmpdir(),"builder-recovery-")),source=join(root,"source"),remote=join(root,"remote.git"),worktrees=join(root,"worktrees");mkdirSync(source);execFileSync("git",["init","--bare",remote]);execFileSync("git",["init",source]);execFileSync("git",["-C",source,"config","user.email","builder@test.invalid"]);execFileSync("git",["-C",source,"config","user.name","Builder Test"]);writeFileSync(join(source,"README.md"),"base\n");execFileSync("git",["-C",source,"add","README.md"]);execFileSync("git",["-C",source,"commit","-m","base"]);execFileSync("git",["-C",source,"remote","add","origin",remote]);const base=execFileSync("git",["-C",source,"rev-parse","HEAD"],{encoding:"utf8"}).trim();mkdirSync(worktrees);const worktree=join(worktrees,spec.front_id!);execFileSync("git",["-C",source,"worktree","add","-b",spec.work_branch!,worktree,base]);execFileSync("git",["-C",worktree,"config","user.email","builder@test.invalid"]);execFileSync("git",["-C",worktree,"config","user.name","Builder Test"]);mkdirSync(join(worktree,"docs"));return {source,remote,worktrees,worktree,base};}
function recoveryBus(){let created=0,bound=0;return {bus:{findPrByBranch:()=>undefined,remoteBranchHead:()=>undefined,createDraftPr:()=>{created++;return 92;},bindPrToIssue:()=>{bound++;},repairPrompt:()=>""},counts:()=>({created,bound})};}
test("dirty allowlisted worktree resumes without rerunning model",()=>{const r=recoveryRepo(),b=recoveryBus(),s={...spec,expected_base_sha:r.base};writeFileSync(join(r.worktree,"docs","x.md"),"resumed\n");const result=new GovernedBuilder(r.source,r.worktrees,b.bus as any,()=>{},"must-not-run").build(s,90,"resume-dirty",0);assert.match(result.head_sha,/^[0-9a-f]{40}$/);assert.deepEqual(b.counts(),{created:1,bound:1});assert.equal(execFileSync("git",["--git-dir",r.remote,"rev-parse",`refs/heads/${spec.work_branch}`],{encoding:"utf8"}).trim(),result.head_sha);});
test("committed allowlisted worktree resumes push and PR without rerunning model",()=>{const r=recoveryRepo(),b=recoveryBus(),s={...spec,expected_base_sha:r.base};writeFileSync(join(r.worktree,"docs","x.md"),"committed\n");execFileSync("git",["-C",r.worktree,"add","docs/x.md"]);execFileSync("git",["-C",r.worktree,"commit","-m",`feat(control-plane): complete ${spec.front_id}`]);const head=execFileSync("git",["-C",r.worktree,"rev-parse","HEAD"],{encoding:"utf8"}).trim();const result=new GovernedBuilder(r.source,r.worktrees,b.bus as any,()=>{},"must-not-run").build(s,90,"resume-commit",0);assert.equal(result.head_sha,head);assert.deepEqual(b.counts(),{created:1,bound:1});});
