import test from "node:test";
import assert from "node:assert/strict";
import {createHash,randomUUID} from "node:crypto";
import {existsSync,mkdtempSync,readFileSync,readdirSync,renameSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {deriveLegacyDecisionKey,Ledger,parseKeyedDecisionV2,parseLegacyDecisionV1} from "../../../scripts/operator_proxy/decision_ledger.js";

const base="a".repeat(40),head="b".repeat(40),policy="c".repeat(64),evidence="d".repeat(64);
const legacy=(overrides:Record<string,unknown>={})=>({schema_version:1,decision_id:"11111111-1111-4111-a111-111111111111",authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",issue:63,pr:63,base_sha:base,head_sha:head,roadmap_id:"BRAIN-101",roadmap_item_id:"R1.1",risk:"LOW",deterministic_gate:"PASS",codex_review:"PASS",policy_decision:"APPROVE",allowed_action:"MERGE",policy_sha256:policy,evidence_sha256:evidence,created_utc:"2026-07-22T00:00:00.000Z",...overrides});
const keyed=(overrides:Record<string,unknown>={})=>({schema_version:2,decision_key:"e".repeat(64),decision_id:"eeeeeeee-eeee-4eee-aeee-eeeeeeeeeeee",authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",issue:63,pr:63,base_sha:base,head_sha:head,roadmap_id:"BRAIN-101",roadmap_item_id:"R1.1",risk:"LOW",deterministic_gate:"PASS",codex_review:"PASS",review_findings_count:0,review_consistent:true,policy_decision:"APPROVE",allowed_action:"MERGE",policy_sha256:policy,evidence_sha256:evidence,created_utc:"2026-07-27T00:00:00.000Z",...overrides});
const sha=(bytes:Buffer)=>createHash("sha256").update(bytes).digest("hex");
const root=()=>mkdtempSync(join(tmpdir(),"legacy-ledger-"));
const legacyPath=(dir:string,value=legacy())=>{const path=join(dir,`2026-07-22T00-00-00-000Z-${value.decision_id}.json`);writeFileSync(path,JSON.stringify(value,null,2));return path;};
const eventLines=(dir:string)=>existsSync(join(dir,"events.jsonl"))?readFileSync(join(dir,"events.jsonl"),"utf8").trim().split(/\r?\n/).filter(Boolean):[];

test("legacy v1 parses without a decision key while hybrid and keyed-v1 fail closed",()=>{const v=legacy();assert.equal(parseLegacyDecisionV1(Buffer.from(JSON.stringify(v))).decision_id,v.decision_id);assert.throws(()=>parseLegacyDecisionV1(Buffer.from(JSON.stringify({...v,decision_key:"e".repeat(64)}))),/legacy schema/);assert.throws(()=>parseKeyedDecisionV2(Buffer.from(JSON.stringify({...keyed(),schema_version:1}))),/keyed schema/);});

test("legacy scan preserves source bytes and creates one valid append-only sidecar",()=>{const dir=root(),path=legacyPath(dir),before=readFileSync(path),beforeHash=sha(before),ledger=new Ledger(dir),first=ledger.decisions()[0];assert.equal(first.schema_version,1);assert.equal(sha(readFileSync(path)),beforeHash);assert.deepEqual(readFileSync(path),before);const sidecars=readdirSync(join(dir,"legacy-index-v2"));assert.deepEqual(sidecars,[`${beforeHash}.json`]);const sidecar=JSON.parse(readFileSync(join(dir,"legacy-index-v2",sidecars[0]),"utf8"));assert.equal(sidecar.legacy_source_sha256,beforeHash);assert.equal(sidecar.legacy_decision_id,(legacy() as any).decision_id);assert.equal(sidecar.derived_decision_key,first.decision_key);});

test("legacy key and sidecar are stable across retries",()=>{const dir=root(),path=legacyPath(dir),ledger=new Ledger(dir),one=ledger.decisions()[0],sidecar=join(dir,"legacy-index-v2",`${sha(readFileSync(path))}.json`),bytes=readFileSync(sidecar);const two=new Ledger(dir).decisions()[0];assert.equal(two.decision_key,one.decision_key);assert.deepEqual(readFileSync(sidecar),bytes);assert.equal(readdirSync(join(dir,"legacy-index-v2")).length,1);});

test("staged sidecar left before rename is completed idempotently",()=>{const dir=root(),path=legacyPath(dir),ledger=new Ledger(dir);ledger.decisions();const sidecar=join(dir,"legacy-index-v2",`${sha(readFileSync(path))}.json`),temp=`${sidecar}.tmp`;renameSync(sidecar,temp);assert.equal(existsSync(sidecar),false);new Ledger(dir).decisions();assert.equal(existsSync(sidecar),true);assert.equal(existsSync(temp),false);});

test("existing valid sidecar after rename remains idempotent",()=>{const dir=root(),path=legacyPath(dir),ledger=new Ledger(dir);ledger.decisions();const sidecar=join(dir,"legacy-index-v2",`${sha(readFileSync(path))}.json`),bytes=readFileSync(sidecar);ledger.decisions();assert.deepEqual(readFileSync(sidecar),bytes);});

test("corrupt or conflicting sidecars block without changing legacy bytes",()=>{for(const corrupt of ["{",JSON.stringify({migration_schema_version:2})]){const dir=root(),path=legacyPath(dir),source=readFileSync(path),ledger=new Ledger(dir);ledger.decisions();const sidecar=join(dir,"legacy-index-v2",`${sha(source)}.json`);writeFileSync(sidecar,corrupt);assert.throws(()=>ledger.decisions(),/sidecar/);assert.deepEqual(readFileSync(path),source);}});

test("corrupt legacy and ambiguous schema block",()=>{const dir=root();writeFileSync(join(dir,"legacy.json"),"{");assert.throws(()=>new Ledger(dir).decisions(),/corrupt/);const hybrid=root();legacyPath(hybrid,{...legacy(),review_findings_count:0} as any);assert.throws(()=>new Ledger(hybrid).decisions(),/legacy schema/);});

test("failed full-ledger validation creates no partial compatibility sidecars",()=>{const dir=root();legacyPath(dir);writeFileSync(join(dir,"zz-corrupt.json"),"{");assert.throws(()=>new Ledger(dir).decisions(),/corrupt/);assert.equal(existsSync(join(dir,"legacy-index-v2")),false);});

test("two legacy decisions for one head with different identities block",()=>{const dir=root();legacyPath(dir);legacyPath(dir,legacy({decision_id:"22222222-2222-4222-a222-222222222222",created_utc:"2026-07-23T00:00:00.000Z"}));assert.throws(()=>new Ledger(dir).findByHead(head),/duplicate decisions/);});

test("equivalent legacy and v2 records collapse to one logical decision",()=>{const dir=root(),path=legacyPath(dir),v2=keyed();writeFileSync(join(dir,`decision-${v2.decision_key}.json`),JSON.stringify(v2,null,2));const ledger=new Ledger(dir),all=ledger.decisions(),legacyKey=deriveLegacyDecisionKey(parseLegacyDecisionV1(readFileSync(path)));assert.equal(all.length,1);assert.equal(all[0].schema_version,1);assert.equal(ledger.findByKey(v2.decision_key)?.decision_id,(legacy() as any).decision_id);assert.equal(ledger.findByKey(legacyKey)?.decision_id,(legacy() as any).decision_id);});

test("conflicting legacy and v2 records fail closed",()=>{const dir=root();legacyPath(dir);const v2=keyed({policy_decision:"BLOCK",allowed_action:"NONE"});writeFileSync(join(dir,`decision-${v2.decision_key}.json`),JSON.stringify(v2));assert.throws(()=>new Ledger(dir).decisions(),/duplicate decisions|IDENTITY_CONFLICT/);});

test("recordOrLoad reconciles an equivalent legacy decision without review, decision, or event duplication",()=>{const dir=root(),value=legacy(),path=legacyPath(dir,value),source=readFileSync(path);writeFileSync(join(dir,"events.jsonl"),`${JSON.stringify({event:"operator_policy_approve",...value})}\n`);const ledger=new Ledger(dir),result=ledger.recordOrLoad(keyed() as any);assert.equal(result.created,false);assert.equal(result.decision.decision_id,value.decision_id);assert.equal(readdirSync(dir).filter(name=>name.startsWith("decision-")).length,0);assert.equal(eventLines(dir).length,1);assert.deepEqual(readFileSync(path),source);});

test("legacy policy event is correlated and never emitted twice",()=>{const dir=root(),value=legacy();legacyPath(dir,value);writeFileSync(join(dir,"events.jsonl"),`${JSON.stringify({event:"operator_policy_approve",...value})}\n`);const ledger=new Ledger(dir);ledger.recordOrLoad(keyed() as any);ledger.recordOrLoad(keyed() as any);assert.equal(eventLines(dir).filter(line=>line.includes("operator_policy_")).length,1);});

test("legacy authorization receipt is correlated and never emitted twice",()=>{const dir=root(),value=legacy();legacyPath(dir,value);writeFileSync(join(dir,`head-${head}.done`),value.decision_id);writeFileSync(join(dir,"events.jsonl"),`${JSON.stringify({event:"supervisor_authorization_consumed",authorization_id:value.authorization_id,decision_id:value.decision_id,issue:value.issue,pr:value.pr,base_sha:value.base_sha,head_sha:value.head_sha,action:value.allowed_action,policy_sha256:value.policy_sha256})}\n`);const decision=new Ledger(dir).decisions()[0],ledger=new Ledger(dir);ledger.ensureConsumed(decision);ledger.ensureConsumed(decision);assert.equal(eventLines(dir).filter(line=>line.includes("supervisor_authorization_consumed")).length,1);});

test("keyed receipt for an equivalent v2 record reconciles with the legacy view",()=>{const dir=root(),value=legacy(),v2=keyed();legacyPath(dir,value);writeFileSync(join(dir,`decision-${v2.decision_key}.json`),JSON.stringify(v2));writeFileSync(join(dir,`head-${head}.done`),v2.decision_id);writeFileSync(join(dir,"events.jsonl"),`${JSON.stringify({event:"supervisor_authorization_consumed",decision_key:v2.decision_key,authorization_id:v2.authorization_id,decision_id:v2.decision_id,issue:v2.issue,pr:v2.pr,base_sha:v2.base_sha,head_sha:v2.head_sha,action:v2.allowed_action,policy_sha256:v2.policy_sha256})}\n`);const ledger=new Ledger(dir),decision=ledger.decisions()[0];assert.equal(decision.schema_version,1);assert.doesNotThrow(()=>ledger.ensureConsumed(decision));assert.equal(eventLines(dir).length,1);});

test("new records are keyed schema v2 and retries produce one decision and event",()=>{const dir=root(),ledger=new Ledger(dir),value=keyed({decision_id:randomUUID()});ledger.recordOrLoad(value as any);ledger.recordOrLoad(value as any);const files=readdirSync(dir).filter(name=>name.startsWith("decision-"));assert.deepEqual(files,[`decision-${value.decision_key}.json`]);assert.equal(JSON.parse(readFileSync(join(dir,files[0]),"utf8")).schema_version,2);assert.equal(eventLines(dir).length,1);});

test("legacy decisions cannot authorize modern merge without reviewer consistency evidence",()=>{const dir=root();legacyPath(dir);const d=new Ledger(dir).decisions()[0];assert.equal(d.schema_version,1);assert.equal("review_consistent" in d,false);});
