import test from "node:test";
import assert from "node:assert/strict";
import {existsSync, readFileSync} from "node:fs";
import {resolve} from "node:path";

const ROOT=resolve(process.cwd(),"..","..");
const MANIFEST="docs/roadmap/BRAIN_101_MANIFEST.json";
const R34_CLOSEOUT="docs/roadmap/evidence/BRAIN_101_R3_4_AGENT_V2_COGNITIVE_PIPELINE_E2E_CLOSEOUT.json";
const R41_BASELINE="docs/roadmap/evidence/BRAIN_101_R4_1_MODULAR_MONOLITH_BASELINE.md";
const readJson=(path:string)=>JSON.parse(readFileSync(resolve(ROOT,path),"utf8"));
const activeItems=(manifest:any)=>Object.entries(manifest.roadmap_items).filter(([,item]:any)=>item.status==="AUTHORIZED_ACTIVE");
const readText=(path:string)=>readFileSync(resolve(ROOT,path),"utf8");
const recommendation=(text:string)=>{
  const matches=[...text.matchAll(/```json\r?\n([\s\S]*?)\r?\n```/g)];
  assert.equal(matches.length,1,"baseline must contain exactly one recommendation JSON object");
  const match=matches[0];
  assert.ok(match,"baseline must contain one recommendation JSON object");
  return JSON.parse(match[1]);
};

test("R3.4 controller closeout remains immutable after downstream roadmap transitions",()=>{
  const manifest=readJson(MANIFEST);
  assert.equal(manifest.roadmap_items["R3.4"].status,"CLOSED_RUNTIME_VERIFIED");
  assert.ok(existsSync(resolve(ROOT,R34_CLOSEOUT)));
});

test("R4.1 contract is no-deploy and protects prohibited boundaries",()=>{
  const item=readJson(MANIFEST).roadmap_items["R4.1"];
  assert.deepEqual(item.dependencies,["R3.4"]);
  assert.equal(item.automation.executor,"codex_control_plane");
  assert.equal(item.automation.deployment_mode,"NO_DEPLOY");
  assert.deepEqual(item.automation.allowed_paths,[R41_BASELINE,"tests/contract/operator_proxy/r4_1_roadmap_contract.test.ts"]);
  for(const path of [".env","tmp_agent/brain_v9/trading/","financial_autonomy/","scripts/"])
    assert.ok(item.automation.forbidden_paths.includes(path));
});

test("R4.1 baseline evidence selects one eligible no-deploy modular-monolith candidate",()=>{
  assert.ok(existsSync(resolve(ROOT,R41_BASELINE)),"baseline evidence must exist before R4.2 authorization");
  const text=readText(R41_BASELINE);
  assert.match(text,/`CANONICAL_BASE_SHA`: `f455904b98d9bc1ed690e7948f99d9200a13cce4`/);
  assert.match(text,/`INVENTORY_INPUT_SHA256`: `[a-f0-9]{64}`/);
  for(const heading of ["Entry Point Inventory","Module Ownership Map","Dependency Boundary Map","Shared-State Inventory","Side-Effect Inventory","Coupling and Hotspots","Extraction Candidates","R4.2 Recommendation","Rollback Strategy","Required Tests","Hard Limits"])
    assert.match(text,new RegExp(`^## ${heading}$`,"m"));
  const selected=recommendation(text);
  assert.equal(selected.roadmap_item_id,"R4.2");
  assert.equal(selected.candidate,"router response-governance helper extraction");
  assert.equal(selected.score,29);
  assert.equal(selected.deployment_mode,"NO_DEPLOY");
  assert.equal(selected.network_boundary,false);
  assert.equal(selected.public_interface_migration,false);
  assert.deepEqual(selected.allowed_paths,[
    "tmp_agent/brain_v9/core/router_entrypoint.py",
    "tmp_agent/brain_v9/core/router_response_governance.py",
    "tests/contract/test_r4_2_router_response_governance.py"
  ]);
});

test("R5.4 through R17.1 closeouts preserve history and hand sole authority to R17.2",()=>{
  const manifest=readJson(MANIFEST);
  assert.equal(manifest.roadmap_items["R4.1"].status,"CLOSED_RUNTIME_VERIFIED");
  const r42=manifest.roadmap_items["R4.2"];
  assert.equal(r42.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r42.automation.front_id,"BRAIN-101-R4-2-ROUTER-RESPONSE-GOVERNANCE-01");
  assert.equal(r42.automation.deployment_mode,"NO_DEPLOY");
  assert.deepEqual(r42.automation.allowed_paths,[
    "tmp_agent/brain_v9/core/router_entrypoint.py",
    "tmp_agent/brain_v9/core/router_response_governance.py",
    "tests/contract/test_r4_2_router_response_governance.py"
  ]);
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R4_1_MODULAR_MONOLITH_BASELINE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R4_2_ROUTER_RESPONSE_GOVERNANCE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R5_1_AGENT_V2_RUNTIME_BASELINE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R5_2_AGENT_V2_LIFECYCLE_CHECKPOINTS_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R5_3_AGENT_V2_PLANNING_EVALUATION_PERSISTENCE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R5_4_AGENT_V2_COGNITIVE_ROUTE_CONVERGENCE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R6_1_MEMORY_SERVICE_OWNERSHIP_INTEGRITY_BASELINE_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R6_2_GOVERNED_MEMORY_CANDIDATE_PROMOTION_ROLLBACK_CLOSEOUT.json")));
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R6_3_MEMORY_RETRIEVAL_HYDRATION_REBUILD_VALIDATION_CLOSEOUT.json")));
  assert.deepEqual(activeItems(manifest).map(([item])=>item),["R18.1"]);
  const r43=manifest.roadmap_items["R4.3"];
  assert.deepEqual(r43.dependencies,["R4.2"]);
  assert.equal(r43.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r43.automation.front_id,"BRAIN-101-R4-3-CHAT-ENTRYPOINT-CONTRACTS-01");
  assert.equal(r43.automation.deployment_mode,"NO_DEPLOY");
  const r51=manifest.roadmap_items["R5.1"];
  assert.deepEqual(r51.dependencies,["R4.3"]);
  assert.equal(r51.automation.front_id,"BRAIN-101-R5-1-AGENT-V2-RUNTIME-BASELINE-01");
  assert.equal(r51.automation.jit_binding_completed,true);
  assert.equal(r51.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(r51.status,"CLOSED_RUNTIME_VERIFIED");
  const r52=manifest.roadmap_items["R5.2"];
  assert.deepEqual(r52.dependencies,["R5.1"]);
  assert.equal(r52.automation.front_id,"BRAIN-101-R5-2-AGENT-V2-LIFECYCLE-CHECKPOINTS-01");
  assert.equal(r52.automation.jit_binding_completed,true);
  assert.equal(r52.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(r52.status,"CLOSED_RUNTIME_VERIFIED");
  const r53=manifest.roadmap_items["R5.3"];
  assert.deepEqual(r53.dependencies,["R5.2"]);
  assert.equal(r53.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r53.automation.front_id,"BRAIN-101-R5-3-AGENT-V2-PLANNING-EVALUATION-PERSISTENCE-01");
  assert.equal(r53.automation.jit_binding_completed,true);
  assert.equal(r53.automation.deployment_mode,"NO_DEPLOY");
  const r54=manifest.roadmap_items["R5.4"];
  assert.deepEqual(r54.dependencies,["R5.3"]);
  assert.equal(r54.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r54.automation.front_id,"BRAIN-101-R5-4-AGENT-V2-COGNITIVE-ROUTE-CONVERGENCE-01");
  assert.equal(r54.automation.jit_binding_completed,true);
  assert.equal(r54.automation.deployment_mode,"NO_DEPLOY");
  const r61=manifest.roadmap_items["R6.1"];
  assert.deepEqual(r61.dependencies,["R5.4"]);
  assert.equal(r61.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r61.automation.front_id,"BRAIN-101-R6-1-MEMORY-SERVICE-OWNERSHIP-INTEGRITY-BASELINE-01");
  assert.equal(r61.automation.jit_binding_completed,true);
  assert.equal(r61.automation.deployment_mode,"NO_DEPLOY");
  const r62=manifest.roadmap_items["R6.2"];
  assert.deepEqual(r62.dependencies,["R6.1"]);
  assert.equal(r62.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r62.automation.front_id,"BRAIN-101-R6-2-GOVERNED-MEMORY-CANDIDATE-PROMOTION-ROLLBACK-01");
  assert.equal(r62.automation.jit_binding_completed,true);
  assert.equal(r62.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(r62.automation.closeout.risk,"MEDIUM");
  const r63=manifest.roadmap_items["R6.3"];
  assert.deepEqual(r63.dependencies,["R6.2"]);
  assert.equal(r63.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r63.automation.front_id,"BRAIN-101-R6-3-MEMORY-RETRIEVAL-HYDRATION-REBUILD-VALIDATION-01");
  assert.equal(r63.automation.jit_binding_completed,true);
  assert.equal(r63.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(r63.automation.closeout.risk,"MEDIUM");
  const r71=manifest.roadmap_items["R7.1"];
  assert.deepEqual(r71.dependencies,["R5.4"]);
  assert.equal(r71.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r71.automation.front_id,"BRAIN-101-R7-1-GOVERNED-TRACE-SCHEMA-EVENT-WRITER-BASELINE-01");
  assert.equal(r71.automation.jit_binding_completed,true);
  assert.equal(r71.automation.deployment_mode,"NO_DEPLOY");
  const r72=manifest.roadmap_items["R7.2"];
  assert.deepEqual(r72.dependencies,["R7.1"]);
  assert.equal(r72.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r72.automation.front_id,"BRAIN-101-R7-2-RUN-TIMELINE-PROVIDER-HEALTH-OPERATIONAL-ACCOUNTING-01");
  assert.equal(r72.automation.jit_binding_completed,true);
  assert.equal(r72.automation.deployment_mode,"NO_DEPLOY");
  const r73=manifest.roadmap_items["R7.3"];
  assert.deepEqual(r73.dependencies,["R7.2"]);
  assert.equal(r73.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r73.automation.front_id,"BRAIN-101-R7-3-VISUAL-TRACE-OPERATOR-CONSOLE-CONTRACTS-01");
  assert.equal(r73.automation.jit_binding_completed,true);
  assert.equal(r73.automation.deployment_mode,"NO_DEPLOY");
  assert.ok(existsSync(resolve(ROOT,"docs/roadmap/evidence/BRAIN_101_R7_3_VISUAL_TRACE_OPERATOR_CONSOLE_CONTRACTS_CLOSEOUT.json")));
  const r81=manifest.roadmap_items["R8.1"];
  assert.deepEqual(r81.dependencies,["R5.4"]);
  assert.equal(r81.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r81.automation.front_id,"BRAIN-101-R8-1-PROVIDER-GATEWAY-POLICY-CAPABILITY-INVENTORY-01");
  assert.equal(r81.automation.jit_binding_completed,true);
  assert.equal(r81.automation.deployment_mode,"NO_DEPLOY");
  const r82=manifest.roadmap_items["R8.2"];
  assert.deepEqual(r82.dependencies,["R8.1"]);
  assert.equal(r82.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r82.automation.front_id,"BRAIN-101-R8-2-PROVIDER-RESILIENCE-SECRET-SAFE-OPERATIONS-01");
  assert.equal(r82.automation.jit_binding_completed,true);
  assert.equal(r82.automation.deployment_mode,"NO_DEPLOY");
  const r83=manifest.roadmap_items["R8.3"];
  assert.deepEqual(r83.dependencies,["R8.2"]);
  assert.equal(r83.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r83.automation.front_id,"BRAIN-101-R8-3-PROVIDER-GATEWAY-ROUTE-FALLBACK-VALIDATION-01");
  assert.equal(r83.automation.jit_binding_completed,true);
  assert.equal(r83.automation.deployment_mode,"NO_DEPLOY");
  const r91=manifest.roadmap_items["R9.1"];
  assert.deepEqual(r91.dependencies,["R8.3"]);
  assert.equal(r91.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r91.automation.front_id,"BRAIN-101-R9-1-CURATED-KNOWLEDGE-CANONICAL-INVENTORY-TAXONOMY-01");
  assert.equal(r91.automation.jit_binding_completed,true);
  assert.equal(r91.automation.deployment_mode,"NO_DEPLOY");
  const r92=manifest.roadmap_items["R9.2"];
  assert.deepEqual(r92.dependencies,["R9.1"]);
  assert.equal(r92.automation.front_id,"BRAIN-101-R9-2-CURATED-KNOWLEDGE-CONTROLLED-INGESTION-BENCHMARK-01");
  assert.equal(r92.automation.jit_binding_completed,true);
  assert.equal(r92.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(r92.status,"CLOSED_RUNTIME_VERIFIED");
  const r101=manifest.roadmap_items["R10.1"];
  assert.deepEqual(r101.dependencies,["R9.2"]);
  assert.equal(r101.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r101.automation.front_id,"BRAIN-101-R10-1-GOVERNED-SELF-IMPROVEMENT-CAPABILITY-GAP-EVALUATION-01");
  assert.equal(r101.automation.jit_binding_completed,true);
  assert.equal(r101.automation.deployment_mode,"NO_DEPLOY");
  const r102=manifest.roadmap_items["R10.2"];
  assert.deepEqual(r102.dependencies,["R10.1"]);
  assert.equal(r102.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r102.automation.front_id,"BRAIN-101-R10-2-SANDBOXED-PATCH-PROPOSAL-BENCHMARK-PIPELINE-01");
  assert.equal(r102.automation.jit_binding_completed,true);
  assert.equal(r102.automation.deployment_mode,"NO_DEPLOY");
  const r103=manifest.roadmap_items["R10.3"];
  assert.deepEqual(r103.dependencies,["R10.2"]);
  assert.equal(r103.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r103.automation.front_id,"BRAIN-101-R10-3-SELF-IMPROVEMENT-PROMOTION-GATE-ROLLBACK-01");
  assert.equal(r103.automation.jit_binding_completed,true);
  assert.equal(r103.automation.deployment_mode,"NO_DEPLOY");
  const r111=manifest.roadmap_items["R11.1"];
  assert.deepEqual(r111.dependencies,["R10.3"]);
  assert.equal(r111.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r111.automation.front_id,"BRAIN-101-R11-1-FINANCIAL-AUTONOMY-PAPER-ONLY-RUNTIME-INVENTORY-01");
  assert.equal(r111.automation.jit_binding_completed,true);
  assert.equal(r111.automation.deployment_mode,"NO_DEPLOY");
  const r112=manifest.roadmap_items["R11.2"];
  assert.deepEqual(r112.dependencies,["R11.1"]);
  assert.equal(r112.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r112.automation.front_id,"BRAIN-101-R11-2-FINANCIAL-AUTONOMY-PAPER-ONLY-AUDIT-ROLLBACK-WIRING-01");
  assert.equal(r112.automation.jit_binding_completed,true);
  assert.equal(r112.automation.deployment_mode,"NO_DEPLOY");
  const r121=manifest.roadmap_items["R12.1"];
  assert.deepEqual(r121.dependencies,["R11.2"]);
  assert.equal(r121.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r121.automation.front_id,"BRAIN-101-R12-1-PORTFOLIO-MANAGER-ALLOCATION-LEDGER-BASELINE-01");
  assert.equal(r121.automation.jit_binding_completed,true);
  assert.equal(r121.automation.deployment_mode,"NO_DEPLOY");
  const r122=manifest.roadmap_items["R12.2"];
  assert.deepEqual(r122.dependencies,["R12.1"]);
  assert.equal(r122.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r122.automation.front_id,"BRAIN-101-R12-2-RISK-ENGINE-LOSS-EXPOSURE-MARKET-FAILURE-GATES-01");
  assert.equal(r122.automation.jit_binding_completed,true);
  assert.equal(r122.automation.deployment_mode,"NO_DEPLOY");
  const r123=manifest.roadmap_items["R12.3"];
  assert.deepEqual(r123.dependencies,["R12.2"]);
  assert.equal(r123.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r123.automation.front_id,"BRAIN-101-R12-3-PORTFOLIO-REGIME-REBALANCE-RISK-ATTRIBUTION-VALIDATION-01");
  assert.equal(r123.automation.jit_binding_completed,true);
  assert.equal(r123.automation.deployment_mode,"NO_DEPLOY");
  const r131=manifest.roadmap_items["R13.1"];
  assert.deepEqual(r131.dependencies,["R12.3"]);
  assert.equal(r131.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r131.automation.front_id,"BRAIN-101-R13-1-PAPER-TRADING-COMPLIANCE-POLICY-INVENTORY-01");
  assert.equal(r131.automation.jit_binding_completed,true);
  assert.equal(r131.automation.deployment_mode,"NO_DEPLOY");
  const r132=manifest.roadmap_items["R13.2"];
  assert.deepEqual(r132.dependencies,["R13.1"]);
  assert.equal(r132.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r132.automation.front_id,"BRAIN-101-R13-2-COMPLIANCE-AUDIT-TAX-LOT-MANUAL-REVIEW-01");
  assert.equal(r132.automation.jit_binding_completed,true);
  assert.equal(r132.automation.deployment_mode,"NO_DEPLOY");
  const r141=manifest.roadmap_items["R14.1"];
  assert.deepEqual(r141.dependencies,["R13.2"]);
  assert.equal(r141.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r141.automation.front_id,"BRAIN-101-R14-1-LOCAL-VALIDATION-DATA-EXPERIMENT-REGISTRY-01");
  assert.equal(r141.automation.jit_binding_completed,true);
  assert.equal(r141.automation.deployment_mode,"NO_DEPLOY");
  const r142=manifest.roadmap_items["R14.2"];
  assert.deepEqual(r142.dependencies,["R14.1"]);
  assert.equal(r142.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r142.automation.front_id,"BRAIN-101-R14-2-BACKTEST-REALISM-WALK-FORWARD-VALIDATION-01");
  assert.equal(r142.automation.jit_binding_completed,true);
  assert.equal(r142.automation.deployment_mode,"NO_DEPLOY");
  const r143=manifest.roadmap_items["R14.3"];
  assert.deepEqual(r143.dependencies,["R14.2"]);
  assert.equal(r143.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r143.automation.front_id,"BRAIN-101-R14-3-VALIDATION-LAB-ADVERSARIAL-STATISTICAL-RESILIENCE-01");
  assert.equal(r143.automation.jit_binding_completed,true);
  assert.equal(r143.automation.deployment_mode,"NO_DEPLOY");
  const r151=manifest.roadmap_items["R15.1"];
  assert.deepEqual(r151.dependencies,["R14.3"]);
  assert.equal(r151.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r151.automation.front_id,"BRAIN-101-R15-1-PAPER-BROKER-MARKET-DATA-LIFECYCLE-01");
  assert.equal(r151.automation.jit_binding_completed,true);
  assert.equal(r151.automation.deployment_mode,"NO_DEPLOY");
  const r152=manifest.roadmap_items["R15.2"];
  assert.deepEqual(r152.dependencies,["R15.1"]);
  assert.equal(r152.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r152.automation.front_id,"BRAIN-101-R15-2-PAPER-PORTFOLIO-COMPLIANCE-RISK-INTEGRATION-01");
  assert.equal(r152.automation.jit_binding_completed,true);
  assert.equal(r152.automation.deployment_mode,"NO_DEPLOY");
  const r153=manifest.roadmap_items["R15.3"];
  assert.deepEqual(r153.dependencies,["R15.2"]);
  assert.equal(r153.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r153.automation.front_id,"BRAIN-101-R15-3-PAPER-SOAK-INCIDENT-EVIDENCE-01");
  assert.equal(r153.automation.jit_binding_completed,true);
  assert.equal(r153.automation.deployment_mode,"NO_DEPLOY");
  const r161=manifest.roadmap_items["R16.1"];
  assert.equal(r161.status,"CLOSED_RUNTIME_VERIFIED");
  assert.equal(r161.automation.front_id,"BRAIN-101-R16-1-DISABLED-LIVE-TRADING-GATE-DESIGN-01");
  assert.equal(r161.automation.live_trading_enabled,false);
  assert.equal(r161.automation.deployment_mode,"NO_DEPLOY");
  assert.equal(manifest.roadmap_items["R17.1"].status,"CLOSED_RUNTIME_VERIFIED");
  const r172=manifest.roadmap_items["R17.2"];
  assert.equal(r172.automation.front_id,"BRAIN-101-R17-2-SELECTIVE-MICROSERVICE-DECISION-CONTAINMENT-01");
  assert.equal(r172.automation.deployment_mode,"NO_DEPLOY");
  assert.ok(r172.automation.closeout);
});
