import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync,readFileSync,writeFileSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import type {ReviewerBackend,ReviewerInput} from "../../../scripts/operator_proxy/reviewer_backend.js";
import {ReviewerBackendError} from "../../../scripts/operator_proxy/reviewer_backend.js";
import {REVIEWER_MODELS,reviewerRoute} from "../../../scripts/operator_proxy/reviewer_config.js";
import {ReviewerRouter,validateReviewerEnvelope} from "../../../scripts/operator_proxy/reviewer_router.js";

const head="b".repeat(40),base="a".repeat(40);
const input=(overrides:Partial<ReviewerInput>={}):ReviewerInput=>({repository:"cesarmanuel8102/AI_Vault",repositoryRoot:"C:\\repo",pr:99,baseSha:base,headSha:head,risk:"MEDIUM",changedFiles:["scripts/operator_proxy/operator_proxy.ts"],builderSession:"builder-1",...overrides});
const pass=(model:string):ReviewerBackend=>({model,review:(_input,session)=>({backend:"opencode_ollama",model,session,providerSession:`provider-${session}`,startedUtc:"2026-01-01T00:00:00Z",completedUtc:"2026-01-01T00:00:01Z",output:{verdict:"PASS",head_sha:head,summary:"pass",findings:[]}})});

test("routes every eligible review to DeepSeek Pro and excludes its own builder output",()=>{assert.deepEqual(reviewerRoute(input()),[REVIEWER_MODELS.deepseekPro]);assert.deepEqual(reviewerRoute(input({risk:"LOW"})),[REVIEWER_MODELS.deepseekPro]);assert.deepEqual(reviewerRoute(input({changedFiles:["scripts/agent_loop/local_worker/agent_worker.py"]})),[REVIEWER_MODELS.deepseekPro]);assert.deepEqual(reviewerRoute(input({builderModel:REVIEWER_MODELS.deepseekPro})),[]);});
test("single DeepSeek Pro review persists one exact receipt and is idempotent",()=>{const calls:string[]=[],router=new ReviewerRouter(mkdtempSync(join(tmpdir(),"router-")),model=>({...pass(model),review:(value,session)=>{calls.push(model);return pass(model).review(value,session);}})),first=router.review(input()),second=router.review(input());assert.equal(first.review_mode,"single-deepseek-pro");assert.equal(first.model,REVIEWER_MODELS.deepseekPro);assert.equal(first.verifier,undefined);assert.equal(first.arbiter,undefined);assert.equal(first.output.verdict,"PASS");assert.equal(second.receipt_key,first.receipt_key);assert.deepEqual(calls,[REVIEWER_MODELS.deepseekPro]);});
test("single DeepSeek Pro retry is bounded and never falls through to another model",()=>{let first=true,calls:string[]=[];const router=new ReviewerRouter(mkdtempSync(join(tmpdir(),"router-")),model=>({model,review:(value,session)=>{calls.push(model);if(first){first=false;throw new ReviewerBackendError("truncated","REVIEWER_OUTPUT_TRUNCATED",true);}return pass(model).review(value,session);}})),run=router.review(input());assert.deepEqual(calls,[REVIEWER_MODELS.deepseekPro,REVIEWER_MODELS.deepseekPro]);assert.equal(run.attempts.length,2);assert.equal(run.attempts[0].failure_class,"REVIEWER_OUTPUT_TRUNCATED");assert.equal(run.output.verdict,"PASS");});
test("single reviewer failure and self-review conflict fail closed for manual Codex review",()=>{const offline=(model:string):ReviewerBackend=>({model,review:()=>{throw new ReviewerBackendError("offline","MODEL_UNAVAILABLE");}});assert.throws(()=>new ReviewerRouter(mkdtempSync(join(tmpdir(),"router-")),offline).review(input()),(error:any)=>error instanceof ReviewerBackendError&&error.failureClass==="SINGLE_REVIEWER_UNAVAILABLE"&&/manual Codex review required/.test(error.message));assert.throws(()=>new ReviewerRouter(mkdtempSync(join(tmpdir(),"router-")),pass).review(input({builderModel:REVIEWER_MODELS.deepseekPro})),(error:any)=>error instanceof ReviewerBackendError&&error.failureClass==="REVIEWER_MODEL_CONFLICT");});
test("single reviewer receipt rejects tampering and binds the outer envelope",()=>{const root=mkdtempSync(join(tmpdir(),"router-")),router=new ReviewerRouter(root,pass),request=input({builderModel:"codex-local"}),run=router.review(request),path=join(root,"reviews",`review-${run.receipt_key}.json`),value=JSON.parse(readFileSync(path,"utf8"));value.model=REVIEWER_MODELS.deepseekFlash;writeFileSync(path,JSON.stringify(value));assert.throws(()=>router.review(request),/single reviewer receipt invalid/);const fresh=new ReviewerRouter(mkdtempSync(join(tmpdir(),"router-")),pass).review(request),expected={issue:65,pr:99,base_sha:base,head_sha:head,front_id:"FRONT-R1-TEST",builder_session:request.builderSession,builder_model:"codex-local"},envelope={schema_version:1,...expected,session:fresh.session,router_run:fresh,result:fresh.output};assert.equal(validateReviewerEnvelope(JSON.parse(JSON.stringify(envelope)),expected,request).session,fresh.session);envelope.router_run.primary_output.summary="tampered";assert.throws(()=>validateReviewerEnvelope(envelope,expected,request),/single reviewer receipt invalid|outer review receipt evidence mismatch/);});
