import test from "node:test";import assert from "node:assert/strict";import {execFileSync} from "node:child_process";import {mkdirSync,mkdtempSync,writeFileSync,existsSync,realpathSync,readFileSync,readdirSync,rmSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {lock} from "../../../scripts/operator_proxy/single_instance_lock.js";import {Ledger} from "../../../scripts/operator_proxy/decision_ledger.js";import {resolveReviewerRepository,reviewerInvocation,runReviewer} from "../../../scripts/operator_proxy/codex_reviewer.js";import {resumePrivilegedInstall,validatePostMergeBaseAdvance} from "../../../scripts/operator_proxy/autonomous_runtime.js";import {LifecycleStore} from "../../../scripts/operator_proxy/lifecycle_store.js";import {ExternalEffectBoundary} from "../../../scripts/operator_proxy/external_effect_guard.js";import {AutonomousFlow} from "../../../scripts/operator_proxy/autonomous_flow.js";
test("single instance uses append-only epochs and blocks a live owner",()=>{const p=join(mkdtempSync(join(tmpdir(),"op-")),"l");const done=lock(p),record=JSON.parse(readFileSync(join(p,"epoch-0000000000000001.json"),"utf8"));assert.equal(record.pid,process.pid);assert.equal(record.epoch,1);assert.equal(done.owns(),true);assert.throws(()=>lock(p),/occupied/);done();assert.equal(done.owns(),false);assert.deepEqual(readdirSync(p).sort(),["epoch-0000000000000001.json","epoch-0000000000000001.release.json"])});
test("released owner advances epoch without deleting authoritative bytes",()=>{const p=join(mkdtempSync(join(tmpdir(),"op-lock-")),"l"),first=lock(p);const original=readFileSync(join(p,"epoch-0000000000000001.json"));first();const second=lock(p);assert.equal(JSON.parse(readFileSync(join(p,"epoch-0000000000000002.json"),"utf8")).epoch,2);assert.deepEqual(readFileSync(join(p,"epoch-0000000000000001.json")),original);second();});
test("legacy file and corrupt epoch or release fail closed",()=>{const root=mkdtempSync(join(tmpdir(),"op-lock-")),legacy=join(root,"legacy"),corrupt=join(root,"corrupt"),badRelease=join(root,"bad-release");writeFileSync(legacy,"");assert.throws(()=>lock(legacy),/legacy or unsafe/);mkdirSync(corrupt);writeFileSync(join(corrupt,"epoch-0000000000000001.json"),'{}\n');assert.throws(()=>lock(corrupt),/epoch record invalid/);const owned=lock(badRelease);writeFileSync(join(badRelease,"epoch-0000000000000001.release.json"),`${JSON.stringify({epoch:1,pid:process.pid,token:crypto.randomUUID(),released_utc:new Date().toISOString()})}\n`);assert.equal(owned.owns(),false);assert.throws(()=>owned(),/release identity mismatch/);});
test("ledger immutable and head idempotent",()=>{const root=mkdtempSync(join(tmpdir(),"op-"));const l=new Ledger(root);const d:any={schema_version:2,decision_key:"e".repeat(64),decision_id:"eeeeeeee-eeee-4eee-aeee-eeeeeeeeeeee",authorization_id:"a",repository:"r",issue:1,pr:2,base_sha:"a".repeat(40),head_sha:"b".repeat(40),roadmap_id:"BRAIN-101",roadmap_item_id:"R1",risk:"LOW",deterministic_gate:"PASS",codex_review:"PASS",review_findings_count:0,review_consistent:true,policy_decision:"APPROVE",allowed_action:"MERGE",policy_sha256:"c".repeat(64),evidence_sha256:"d".repeat(64),created_utc:new Date().toISOString()};l.record(d);l.consume(d);assert.equal(l.hasHead(d.head_sha),true);assert.throws(()=>l.consume(d));});
test("ledger consumption reconciles only the same decision",()=>{const root=mkdtempSync(join(tmpdir(),"op-"));const l=new Ledger(root);const d:any={schema_version:2,decision_key:"e".repeat(64),decision_id:crypto.randomUUID(),authorization_id:"a",repository:"r",issue:1,pr:2,base_sha:"a".repeat(40),head_sha:"b".repeat(40),roadmap_id:"BRAIN-101",roadmap_item_id:"R1",risk:"LOW",deterministic_gate:"PASS",codex_review:"PASS",policy_decision:"APPROVE",allowed_action:"MERGE",policy_sha256:"c".repeat(64),evidence_sha256:"d".repeat(64),created_utc:new Date().toISOString()};l.ensureConsumed(d);assert.doesNotThrow(()=>l.ensureConsumed(d));assert.throws(()=>l.ensureConsumed({...d,decision_id:crypto.randomUUID()}),/different decision/);});
test("pause marker is explicit",()=>{const root=mkdtempSync(join(tmpdir(),"op-"));writeFileSync(join(root,"PAUSE"),"");assert.equal(existsSync(join(root,"PAUSE")),true)});
test("reviewer repository is explicit and independent of cwd",()=>{const repo=mkdtempSync(join(tmpdir(),"op-repo-"));const elsewhere=mkdtempSync(join(tmpdir(),"op-cwd-"));execFileSync("git",["init",repo],{stdio:"ignore"});const previous=process.cwd();try{process.chdir(elsewhere);assert.equal(resolveReviewerRepository(repo),realpathSync(repo));}finally{process.chdir(previous);}});
test("reviewer repository fails closed when missing or not a git root",()=>{const plain=mkdtempSync(join(tmpdir(),"op-plain-"));const repo=mkdtempSync(join(tmpdir(),"op-root-"));const child=join(repo,"child");execFileSync("git",["init",repo],{stdio:"ignore"});mkdirSync(child);assert.throws(()=>resolveReviewerRepository(undefined),/repository required/);assert.throws(()=>resolveReviewerRepository("relative"),/repository required/);assert.throws(()=>resolveReviewerRepository(plain));assert.throws(()=>resolveReviewerRepository(child),/must be git root/);});
test("reviewer uses lossless node entrypoint transport",()=>{const root=mkdtempSync(join(tmpdir(),"codex-entry-"));const entry=join(root,"codex.js");writeFileSync(entry,"");assert.deepEqual(reviewerInvocation("node.exe",entry),{file:"node.exe",prefix:[entry,"-c",'service_tier="fast"',"-c",'model_reasoning_effort="high"']});assert.deepEqual(reviewerInvocation("codex.exe",""),{file:"codex.exe",prefix:[]});assert.throws(()=>reviewerInvocation("node.exe","relative.js"),/entrypoint invalid/);});
test("reviewer accepts bounded verbose process output without ENOBUFS",()=>{const root=mkdtempSync(join(tmpdir(),"codex-verbose-")),entry=join(root,"codex.js"),head="b".repeat(40),prior=process.env.CODEX_ENTRYPOINT;writeFileSync(entry,`const fs=require("fs"),a=process.argv,out=a[a.indexOf("--output-last-message")+1];fs.writeFileSync(out,JSON.stringify({verdict:"PASS",head_sha:"${head}",summary:"pass",findings:[]}));process.stdout.write("x".repeat(2*1024*1024));`);process.env.CODEX_ENTRYPOINT=entry;try{assert.equal(runReviewer(process.execPath,"review",root,"session",head).verdict,"PASS");}finally{if(prior===undefined)delete process.env.CODEX_ENTRYPOINT;else process.env.CODEX_ENTRYPOINT=prior;}});
test("post-merge closeout accepts an exact merged ancestor of the canonical base",()=>{const merge="b".repeat(40),tip="c".repeat(40),spec:any={expected_base_sha:tip},state:any={state:"CLOSEOUT_PENDING",head_sha:merge,completed_effects:[`merge:${merge}`]};assert.equal(validatePostMergeBaseAdvance(spec,state,(oldSha,newSha)=>oldSha===merge&&newSha===tip),true);});
test("post-merge install accepts the exact merge as canonical without an ancestry query",()=>{const merge="b".repeat(40),spec:any={expected_base_sha:merge},state:any={state:"INSTALL_PENDING",head_sha:merge,completed_effects:[`merge:${merge}`]};let queried=false;assert.equal(validatePostMergeBaseAdvance(spec,state,()=>{queried=true;return false;}),true);assert.equal(queried,false);});
test("post-merge closeout rejects missing, mismatched, or divergent merge identity",()=>{const merge="b".repeat(40),tip="c".repeat(40),spec:any={expected_base_sha:tip},state:any={state:"CLOSEOUT_PENDING",head_sha:merge,completed_effects:[`merge:${merge}`]};for(const mutation of [{head_sha:"d".repeat(40)},{completed_effects:[]},{completed_effects:[`merge:${"d".repeat(40)}`]}])assert.throws(()=>validatePostMergeBaseAdvance(spec,{...state,...mutation},()=>true),/post-merge base identity invalid/);assert.throws(()=>validatePostMergeBaseAdvance(spec,state,()=>false),/post-merge base identity invalid/);});
test("pre-merge states do not bypass base reconciliation",()=>{const merge="b".repeat(40),spec:any={expected_base_sha:merge},state:any={state:"BUILDING",head_sha:merge,completed_effects:[`merge:${merge}`]};assert.equal(validatePostMergeBaseAdvance(spec,state,()=>true),false);});
test("post-merge base rebind preserves merge evidence and records the canonical advance",()=>{const root=mkdtempSync(join(tmpdir(),"postmerge-")),store=new LifecycleStore(root),merge="b".repeat(40),tip="c".repeat(40),state:any={schema_version:1,front_id:"POST-MERGE-TEST",roadmap_item_id:"R1",state:"CLOSEOUT_PENDING",base_sha:"a".repeat(40),head_sha:merge,repair_cycles:0,deployment_mode:"NO_DEPLOY",completed_effects:[`merge:${merge}`],updated_utc:new Date().toISOString()};store.save(state);const updated=store.rebindPostMergeBase(state,tip);assert.equal(updated.base_sha,tip);assert.equal(updated.head_sha,merge);assert.deepEqual(updated.completed_effects,state.completed_effects);assert.match(readFileSync(join(root,"events.jsonl"),"utf8"),/lifecycle_postmerge_base_rebound/);});
test("post-merge base rebind rejects pre-merge, missing merge evidence, and no-op updates",()=>{const store=new LifecycleStore(mkdtempSync(join(tmpdir(),"postmerge-deny-"))),merge="b".repeat(40),state:any={schema_version:1,front_id:"POST-MERGE-DENY",roadmap_item_id:"R1",state:"CLOSEOUT_PENDING",base_sha:"a".repeat(40),head_sha:merge,repair_cycles:0,deployment_mode:"NO_DEPLOY",completed_effects:[`merge:${merge}`],updated_utc:new Date().toISOString()};assert.throws(()=>store.rebindPostMergeBase({...state,state:"BUILDING"},"c".repeat(40)));assert.throws(()=>store.rebindPostMergeBase({...state,completed_effects:[]},"c".repeat(40)));assert.throws(()=>store.rebindPostMergeBase(state,state.base_sha));});
test("unstarted closeout base rebind is limited to effect-free admission",()=>{const store=new LifecycleStore(mkdtempSync(join(tmpdir(),"unstarted-"))),state:any={schema_version:1,front_id:"UNSTARTED-CLOSEOUT",roadmap_item_id:"R1",state:"ADMITTED",base_sha:"a".repeat(40),repair_cycles:0,deployment_mode:"NO_DEPLOY",completed_effects:[],updated_utc:new Date().toISOString()},tip="b".repeat(40);const updated=store.rebindUnstartedBase(state,tip);assert.equal(updated.base_sha,tip);for(const patch of [{state:"BUILDING"},{issue:1},{completed_effects:["issue:1"]}])assert.throws(()=>store.rebindUnstartedBase({...state,...patch},tip));});
test("privileged install resume gates artifact reads and coordinator writes",()=>{
  const base="a".repeat(40),build="b".repeat(40),merge="c".repeat(40),root=mkdtempSync(join(tmpdir(),"install-resume-"));mkdirSync(join(root,"state"));
  const spec:any={authorization_id:"CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01",repository:"cesarmanuel8102/AI_Vault",front_id:"BRAIN-101-INSTALL-RESUME-01",roadmap_item_id:"R1.2",expected_base_sha:base,deployment_mode:"INSTALL_ONLY",install_target:"agent_loop_worker"};
  const state:any={schema_version:1,front_id:spec.front_id,roadmap_item_id:spec.roadmap_item_id,state:"ESCALATED",issue:95,pr:58,base_sha:base,head_sha:merge,builder_session:"builder-one",reviewer_session:"reviewer-one",decision_id:"11111111-1111-4111-8111-111111111111",repair_cycles:0,deployment_mode:"INSTALL_ONLY",completed_effects:["issue:95",`build:${build}`,`merge:${merge}`],last_error:"LOCAL_PRIVILEGE_REQUIRED",updated_utc:new Date().toISOString()};
  const run=(patch:any={},options:any={})=>{let artifactReads=0,installCalls=0,resumes=0;const pause=join(root,"state","PAUSE");if(options.localPause)writeFileSync(pause,"");const bus:any={branchHead:()=>options.currentBase??base,issuePaused:()=>options.paused??false,fileAt:()=>{artifactReads++;return "worker bytes";}};const boundary=new ExternalEffectBoundary(root,bus,()=>options.lease??true),coordinator:any={installReceiptPresent:()=>options.receipt??true,install:()=>{installCalls++;return "PASS";}},flow:any={resumePrivilegedInstall:()=>{resumes++;return {...state,state:"INSTALL_PENDING"};}};let error="";try{resumePrivilegedInstall(bus,boundary,coordinator,flow,spec,{...state,...patch});}catch(e){error=String(e);}finally{rmSync(pause,{force:true});}return {artifactReads,installCalls,resumes,error};};
  assert.deepEqual(run({}, {receipt:false}),{artifactReads:0,installCalls:0,resumes:0,error:""});
  for(const blocked of [run({head_sha:"invalid"}),run({}, {paused:true}),run({}, {currentBase:"d".repeat(40)}),run({}, {lease:false}),run({}, {localPause:true}),run({completed_effects:["issue:95",`merge:${merge}`]})]){assert.equal(blocked.artifactReads,0);assert.equal(blocked.installCalls,0);assert.equal(blocked.resumes,0);assert.notEqual(blocked.error,"");}
  assert.deepEqual(run(),{artifactReads:1,installCalls:1,resumes:1,error:""});
});
test("privileged install compare-and-advance rejects lifecycle drift",()=>{const root=mkdtempSync(join(tmpdir(),"install-cas-")),store=new LifecycleStore(root),merge="c".repeat(40),state:any={schema_version:1,front_id:"BRAIN-101-INSTALL-CAS-01",roadmap_item_id:"R1.2",state:"ESCALATED",issue:95,pr:58,base_sha:"a".repeat(40),head_sha:merge,builder_session:"builder-one",reviewer_session:"reviewer-one",decision_id:"11111111-1111-4111-8111-111111111111",repair_cycles:0,deployment_mode:"INSTALL_ONLY",completed_effects:["issue:95",`build:${"b".repeat(40)}`,`merge:${merge}`],last_error:"LOCAL_PRIVILEGE_REQUIRED",updated_utc:new Date().toISOString()};store.save(state);const flow=new AutonomousFlow(store,{} as any);for(const drift of [{head_sha:"d".repeat(40)},{decision_id:"22222222-2222-4222-8222-222222222222"},{completed_effects:["issue:95",`merge:${merge}`]}])assert.throws(()=>flow.resumePrivilegedInstall({...state,...drift}),/persisted state/);assert.equal(flow.resumePrivilegedInstall(state).state,"INSTALL_PENDING");});
