import test from "node:test";import assert from "node:assert/strict";import {execFileSync} from "node:child_process";import {mkdirSync,mkdtempSync,writeFileSync,existsSync,realpathSync} from "node:fs";import {tmpdir} from "node:os";import {join} from "node:path";import {lock} from "../../../scripts/operator_proxy/single_instance_lock.js";import {Ledger} from "../../../scripts/operator_proxy/decision_ledger.js";import {resolveReviewerRepository} from "../../../scripts/operator_proxy/codex_reviewer.js";
import {GitHubBus} from "../../../scripts/operator_proxy/github_bus.js";
test("single instance",()=>{const p=join(mkdtempSync(join(tmpdir(),"op-")),"l");const done=lock(p);assert.throws(()=>lock(p));done();assert.equal(existsSync(p),false)});
test("ledger immutable and head idempotent",()=>{const root=mkdtempSync(join(tmpdir(),"op-"));const l=new Ledger(root);const d:any={schema_version:1,decision_id:crypto.randomUUID(),authorization_id:"a",repository:"r",issue:1,pr:2,base_sha:"a".repeat(40),head_sha:"b".repeat(40),roadmap_id:"BRAIN-101",roadmap_item_id:"R1",risk:"LOW",deterministic_gate:"PASS",codex_review:"PASS",policy_decision:"APPROVE",allowed_action:"MERGE",policy_sha256:"c".repeat(64),evidence_sha256:"d".repeat(64),created_utc:new Date().toISOString()};l.record(d);l.consume(d);assert.equal(l.hasHead(d.head_sha),true);assert.throws(()=>l.consume(d));});
test("pause marker is explicit",()=>{const root=mkdtempSync(join(tmpdir(),"op-"));writeFileSync(join(root,"PAUSE"),"");assert.equal(existsSync(join(root,"PAUSE")),true)});
test("reviewer repository is explicit and independent of cwd",()=>{const repo=mkdtempSync(join(tmpdir(),"op-repo-"));const elsewhere=mkdtempSync(join(tmpdir(),"op-cwd-"));execFileSync("git",["init",repo],{stdio:"ignore"});const previous=process.cwd();try{process.chdir(elsewhere);assert.equal(resolveReviewerRepository(repo),realpathSync(repo));}finally{process.chdir(previous);}});
test("reviewer repository fails closed when missing or not a git root",()=>{const plain=mkdtempSync(join(tmpdir(),"op-plain-"));const repo=mkdtempSync(join(tmpdir(),"op-root-"));const child=join(repo,"child");execFileSync("git",["init",repo],{stdio:"ignore"});mkdirSync(child);assert.throws(()=>resolveReviewerRepository(undefined),/repository required/);assert.throws(()=>resolveReviewerRepository("relative"),/repository required/);assert.throws(()=>resolveReviewerRepository(plain));assert.throws(()=>resolveReviewerRepository(child),/must be git root/);});
test("governed merge uses exact-parent local CAS push without force",()=>{const base="a".repeat(40),head="b".repeat(40),merge="c".repeat(40),calls:string[]=[];const run:any=(file:string,args:string[])=>{calls.push(`${file} ${args.join(" ")}`);const text=args.join(" ");if(file==="gh"&&text.includes("baseRefName,baseRefOid"))return JSON.stringify({baseRefName:"codex/own-capital-sustainable-return",baseRefOid:base,headRefName:"control-plane/test",headRefOid:head,isDraft:true,state:"OPEN",mergeable:"MERGEABLE"});if(file==="git"&&args[0]==="ls-remote")return `${base}\trefs/heads/codex/own-capital-sustainable-return\n`;if(file==="git"&&args[0]==="rev-parse")return `${head}\n`;if(file==="git"&&args[0]==="rev-list")return `${merge} ${base} ${head}\n`;if(file==="gh"&&text.includes("state,mergeCommit"))return JSON.stringify({state:"MERGED",mergeCommit:{oid:merge}});if(file==="gh"&&args[0]==="api")return `${base}\n${head}\n`;return "";};new GitHubBus("gh","cesarmanuel8102/AI_Vault","git","C:\\review-root",run).merge(48,head,base,"decision");assert.ok(calls.some(x=>x.includes("git push origin HEAD:refs/heads/codex/own-capital-sustainable-return")));assert.ok(calls.some(x=>x.includes("gh pr ready 48")));assert.equal(calls.some(x=>/force|squash|rebase|workflow run/i.test(x)),false);});
test("governed merge blocks remote base movement before ready or push",()=>{const base="a".repeat(40),head="b".repeat(40),calls:string[]=[];const run:any=(file:string,args:string[])=>{calls.push(`${file} ${args.join(" ")}`);if(file==="gh")return JSON.stringify({baseRefName:"codex/own-capital-sustainable-return",baseRefOid:base,headRefName:"control-plane/test",headRefOid:head,isDraft:true,state:"OPEN",mergeable:"MERGEABLE"});if(file==="git"&&args[0]==="ls-remote")return `${"d".repeat(40)}\trefs/heads/codex/own-capital-sustainable-return\n`;return "";};assert.throws(()=>new GitHubBus("gh","cesarmanuel8102/AI_Vault","git","C:\\review-root",run).merge(48,head,base,"decision"),/remote base moved/);assert.equal(calls.some(x=>/ pr ready | push /.test(` ${x} `)),false);});
