import test from "node:test";import assert from "node:assert/strict";import {createHash} from "node:crypto";
import {sequenceRoadmap,MANIFEST_PATH,ROADMAP_PATH,INTEGRATION_BRANCH,type SequencerSource} from "../../../scripts/operator_proxy/roadmap_sequencer.js";
const base="a".repeat(40),roadmap="# roadmap\n",hash=(s:string)=>createHash("sha256").update(Buffer.from(s)).digest("hex");
function manifest(){return {roadmap_id:"BRAIN-101",roadmap_version:"1.0.0-reconstructed-glm-harmonized",roadmap_path:ROADMAP_PATH,roadmap_sha256:hash(roadmap),repository:"cesarmanuel8102/AI_Vault",integration_branch:INTEGRATION_BRANCH,approval_status:"HUMAN_ADOPTED",r0_status:"CLOSED_HUMAN_ADOPTED",human_final_authority:true,auto_merge:false,canonical_local_sync:false,live_trading_enabled:false,roadmap_items:{R0:{status:"CLOSED_HUMAN_ADOPTED",dependencies:[]},"R1.9":{status:"AUTHORIZED_ACTIVE",dependencies:["R0"],automation:{front_id:"BRAIN-101-R1-SYNTHETIC-01",objective:"Synthetic documentation proof",work_branch:"control-plane/brain-101-synthetic",executor:"codex_control_plane",risk:"LOW",allowed_paths:["docs/synthetic.md"],forbidden_paths:["memory/","trading/"],acceptance:["deterministic"],test_commands:["git diff --check"],deployment_mode:"NO_DEPLOY",closeout:{front_id:"BRAIN-101-R1-SYNTHETIC-CLOSEOUT-01",objective:"Close synthetic proof",work_branch:"control-plane/brain-101-synthetic-closeout",executor:"codex_control_plane",risk:"MEDIUM",allowed_paths:["docs/roadmap/BRAIN_101_MANIFEST.json"],forbidden_paths:["memory/","trading/"],acceptance:["close item"],test_commands:["git diff --check"]}}}}};}
function source(m:any=manifest(),fronts:number[]=[]):SequencerSource{return {branchHead:b=>{assert.equal(b,INTEGRATION_BRANCH);return base;},fileAt:(p,r)=>{assert.equal(r,base);return p===MANIFEST_PATH?JSON.stringify(m):p===ROADMAP_PATH?roadmap:"";},findOpenFront:()=>fronts};}
test("sequencer binds one active item to immutable remote bytes",()=>{const result=sequenceRoadmap(source());assert.equal(result.base_sha,base);assert.equal(result.spec.roadmap_item_id,"R1.9");assert.equal(result.spec.expected_base_sha,base);assert.deepEqual(result.spec.dependencies,["R0"]);assert.equal(result.spec.deployment_mode,"NO_DEPLOY");});
test("sequencer rejects zero or multiple active items",()=>{const zero=manifest();zero.roadmap_items["R1.9"].status="BLOCKED";assert.throws(()=>sequenceRoadmap(source(zero)),/exactly one/);const two:any=manifest();two.roadmap_items["R2.1"]={...two.roadmap_items["R1.9"],automation:{...two.roadmap_items["R1.9"].automation,front_id:"BRAIN-101-R2-SYNTHETIC-01"}};assert.throws(()=>sequenceRoadmap(source(two)),/exactly one/);});
test("sequencer rejects open dependency and duplicate dependency",()=>{const open:any=manifest();open.roadmap_items.R0.status="OPEN";assert.throws(()=>sequenceRoadmap(source(open)),/dependency not closed/);const duplicate:any=manifest();duplicate.roadmap_items["R1.9"].dependencies=["R0","R0"];assert.throws(()=>sequenceRoadmap(source(duplicate)),/duplicates/);});
test("sequencer rejects hash drift, metadata gaps, and duplicate fronts",()=>{const badHash=manifest();badHash.roadmap_sha256="0".repeat(64);assert.throws(()=>sequenceRoadmap(source(badHash)),/hash mismatch/);const noMeta:any=manifest();delete noMeta.roadmap_items["R1.9"].automation;assert.throws(()=>sequenceRoadmap(source(noMeta)),/metadata missing/);assert.throws(()=>sequenceRoadmap(source(manifest(),[1,2])),/duplicate/);});
test("sequencer never authorizes from working-tree values",()=>{let refs:string[]=[];const s=source();const wrapped={...s,fileAt:(p:string,r:string)=>{refs.push(r);return s.fileAt(p,r);}};sequenceRoadmap(wrapped);assert.deepEqual(refs,[base,base]);});
test("agent loop metadata requires bounded cycle count",()=>{const m:any=manifest();m.roadmap_items["R1.9"].automation.executor="agent_loop";m.roadmap_items["R1.9"].automation.test_profile="test-only";for(const cycles of [0,4,1.5]){m.roadmap_items["R1.9"].automation.max_executor_cycles=cycles;assert.throws(()=>sequenceRoadmap(source(m)),/agent loop automation metadata invalid/);}m.roadmap_items["R1.9"].automation.max_executor_cycles=2;assert.doesNotThrow(()=>sequenceRoadmap(source(m)));});
