$ErrorActionPreference="Stop"
$Root=Resolve-Path (Join-Path $PSScriptRoot "..\..")
Import-Module (Join-Path $Root "scripts\agent_loop\Repair-AgentLoop-v1.5.6.Core.psm1") -Force
function New-Install { $d=Join-Path ([IO.Path]::GetTempPath()) ("v156-"+[guid]::NewGuid().ToString("N")); New-Item -ItemType Directory -Force -Path (Join-Path $d "worker")|Out-Null; New-Item -ItemType Directory -Force -Path (Join-Path $d "state")|Out-Null; Set-Content (Join-Path $d "worker\agent_worker.py") "old"; Set-Content (Join-Path $d "state\issue-5.json") '{"cycles":3}'; return $d }
function New-Repo { $r=Join-Path ([IO.Path]::GetTempPath()) ("v156-repo-"+[guid]::NewGuid().ToString("N")); New-Item -ItemType Directory -Force -Path (Join-Path $r "scripts\agent_loop\local_worker")|Out-Null; $s=Join-Path $r "scripts\agent_loop\local_worker\agent_worker.py"; Set-Content $s "new156"; return @($r,$s,(Get-FileHash $s -Algorithm SHA256).Hash) }
function BaseInvoke($install,$repo,$sha,$recovery) { Invoke-AgentLoopV156DeploymentTransaction -Repo $repo -InstallRoot $install -HistoricalBaseSha ("1"*40) -ApprovedCurrentBaseSha ("2"*40) -ExpectedFront "PILOT-KIMI-CODEX-20260716-091529" -ExpectedIssue 5 -ExpectedPr 6 -ExpectedWorkBranch "agent/pilot-20260716-091529" -ExpectedOldPrHead ("3"*40) -ApprovedControlPlaneCommit ("4"*40) -ApprovedWorkerSha256 $sha -StopTask {param($t)} -DisableTask {param($t)} -GetTaskState {param($t) "Disabled"} -GetRepoHead {param($r) "4444444444444444444444444444444444444444"} -RunRepoCommand {param($r,[string[]]$c)} -Recovery $recovery -WriteLine {param($m) Write-Host $m} }
function Test-Success { $i=New-Install; $r,$s,$sha=New-Repo; $calls=0; BaseInvoke $i $r $sha {param($SourceWorker,$InstallRoot,$ExpectedIssue,$HistoricalBaseSha,$ApprovedCurrentBaseSha,$ApprovedControlPlaneCommit,$ExpectedOldPrHead,$ExpectedFront,$ExpectedPr,$ExpectedWorkBranch,$ApprovedWorkerSha256) $script:calls+=1; Copy-Item $SourceWorker (Join-Path $InstallRoot "worker\agent_worker.py") -Force}; if ($script:calls -ne 1) { throw "atomic call missing" }; if ((Get-Content (Join-Path $i "worker\agent_worker.py") -Raw) -notmatch "new156") { throw "worker not installed" } }
function Test-Fail { $i=New-Install; $r,$s,$sha=New-Repo; $before=Get-Content (Join-Path $i "worker\agent_worker.py") -Raw; try { BaseInvoke $i $r $sha {param($SourceWorker,$InstallRoot,$ExpectedIssue,$HistoricalBaseSha,$ApprovedCurrentBaseSha,$ApprovedControlPlaneCommit,$ExpectedOldPrHead,$ExpectedFront,$ExpectedPr,$ExpectedWorkBranch,$ApprovedWorkerSha256) throw "controlled fail"}; throw "should fail" } catch { if ($_.Exception.Message -notmatch "controlled fail") { throw } }; if ((Get-Content (Join-Path $i "worker\agent_worker.py") -Raw) -ne $before) { throw "unexpected mutation" } }
Test-Success; Test-Fail; Write-Host '{"status":"PASS","tests":["success","failure"],"atomic_command":true}'
