import re
from pathlib import Path

SERVER = r"C:\AI_VAULT\00_identity\brain_server.py"
p = Path(SERVER)
txt = p.read_text(encoding="utf-8")

BEGIN = "# === EXECUTE_STEP PERSIST PLAN (FIX) BEGIN ==="
END   = "# === EXECUTE_STEP PERSIST PLAN (FIX) END ==="

i0 = txt.find(BEGIN)
i1 = txt.find(END)
if i0 < 0 or i1 < 0 or i1 < i0:
    raise SystemExit("No encuentro markers BEGIN/END del bloque EXECUTE_STEP PERSIST PLAN (FIX).")

# Detect base indent from BEGIN line
lines = txt.splitlines(True)
# find the exact BEGIN line index
beg_line_idx = None
for idx, ln in enumerate(lines):
    if BEGIN in ln:
        beg_line_idx = idx
        break
if beg_line_idx is None:
    raise SystemExit("BEGIN line not found in splitlines (unexpected).")

indent = re.match(r"(\s*)", lines[beg_line_idx]).group(1)

new_block = []
new_block.append(f"{indent}{BEGIN}\n")
new_block.append(f"{indent}# Single Source of Truth: persist per-room plan.json here (step-driven)\n")
new_block.append(f"{indent}try:\n")
new_block.append(f"{indent}    room_id = None\n")
new_block.append(f"{indent}    try:\n")
new_block.append(f"{indent}        room_id = getattr(req, 'room_id', None)\n")
new_block.append(f"{indent}    except Exception:\n")
new_block.append(f"{indent}        room_id = None\n")
new_block.append(f"{indent}    room_id = room_id or 'default'\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    step_id_local = ''\n")
new_block.append(f"{indent}    try:\n")
new_block.append(f"{indent}        step_id_local = str(getattr(req, 'step_id', '') or '')\n")
new_block.append(f"{indent}    except Exception:\n")
new_block.append(f"{indent}        step_id_local = ''\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    mode_local = ''\n")
new_block.append(f"{indent}    try:\n")
new_block.append(f"{indent}        mode_local = str(getattr(req, 'mode', '') or '')\n")
new_block.append(f"{indent}    except Exception:\n")
new_block.append(f"{indent}        mode_local = ''\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    def _load_plan_disk(_rid: str) -> dict:\n")
new_block.append(f"{indent}        try:\n")
new_block.append(f"{indent}            _room_state_dir(_rid)\n")
new_block.append(f"{indent}            _paths = _room_paths(_rid) or {{}}\n")
new_block.append(f"{indent}            import json\n")
new_block.append(f"{indent}            from pathlib import Path\n")
new_block.append(f"{indent}            pp = _paths.get('plan')\n")
new_block.append(f"{indent}            if pp and Path(pp).exists():\n")
new_block.append(f"{indent}                return json.loads(Path(pp).read_text(encoding='utf-8')) or {{}}\n")
new_block.append(f"{indent}        except Exception:\n")
new_block.append(f"{indent}            return {{}}\n")
new_block.append(f"{indent}        return {{}}\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    def _save_plan_disk(_rid: str, plan_disk: dict) -> None:\n")
new_block.append(f"{indent}        try:\n")
new_block.append(f"{indent}            _room_state_dir(_rid)\n")
new_block.append(f"{indent}            _paths = _room_paths(_rid) or {{}}\n")
new_block.append(f"{indent}            import json\n")
new_block.append(f"{indent}            from pathlib import Path\n")
new_block.append(f"{indent}            pp = _paths.get('plan')\n")
new_block.append(f"{indent}            if pp:\n")
new_block.append(f"{indent}                Path(pp).write_text(json.dumps(plan_disk or {{}}, ensure_ascii=False, indent=2), encoding='utf-8')\n")
new_block.append(f"{indent}        except Exception:\n")
new_block.append(f"{indent}            pass\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    def _touch(plan_disk: dict) -> None:\n")
new_block.append(f"{indent}        try:\n")
new_block.append(f"{indent}            from datetime import datetime, timezone\n")
new_block.append(f"{indent}            plan_disk['updated_at'] = datetime.now(timezone.utc).isoformat()\n")
new_block.append(f"{indent}        except Exception:\n")
new_block.append(f"{indent}            pass\n")
new_block.append(f"{indent}        try:\n")
new_block.append(f"{indent}            plan_disk.setdefault('room_id', room_id)\n")
new_block.append(f"{indent}        except Exception:\n")
new_block.append(f"{indent}            pass\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    def _extract_proposal_id() -> str:\n")
new_block.append(f"{indent}        # scan common locals for proposal_id (direct or nested under ['result'])\n")
new_block.append(f"{indent}        try:\n")
new_block.append(f"{indent}            for _k in ('res','result','out','resp','response','payload','r'):\n")
new_block.append(f"{indent}                try:\n")
new_block.append(f"{indent}                    obj = locals().get(_k)\n")
new_block.append(f"{indent}                except Exception:\n")
new_block.append(f"{indent}                    obj = None\n")
new_block.append(f"{indent}                if isinstance(obj, dict):\n")
new_block.append(f"{indent}                    pid = obj.get('proposal_id')\n")
new_block.append(f"{indent}                    if pid:\n")
new_block.append(f"{indent}                        return str(pid)\n")
new_block.append(f"{indent}                    inner = obj.get('result')\n")
new_block.append(f"{indent}                    if isinstance(inner, dict) and inner.get('proposal_id'):\n")
new_block.append(f"{indent}                        return str(inner.get('proposal_id'))\n")
new_block.append(f"{indent}        except Exception:\n")
new_block.append(f"{indent}            pass\n")
new_block.append(f"{indent}        return ''\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}    if room_id and step_id_local:\n")
new_block.append(f"{indent}        plan_disk = _load_plan_disk(room_id) or {{}}\n")
new_block.append(f"{indent}        steps_disk = plan_disk.get('steps', []) or []\n")
new_block.append(f"{indent}        if isinstance(steps_disk, list):\n")
new_block.append(f"{indent}            target = None\n")
new_block.append(f"{indent}            for _s in steps_disk:\n")
new_block.append(f"{indent}                if isinstance(_s, dict) and str(_s.get('id')) == step_id_local:\n")
new_block.append(f"{indent}                    target = _s\n")
new_block.append(f"{indent}                    break\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            tool_name_step = ''\n")
new_block.append(f"{indent}            if isinstance(target, dict):\n")
new_block.append(f"{indent}                tool_name_step = str(target.get('tool_name') or '')\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            is_read = tool_name_step in ('list_dir','read_file')\n")
new_block.append(f"{indent}            is_write = tool_name_step in ('write_file','append_file')\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            # read-only propose => done\n")
new_block.append(f"{indent}            if target and is_read and mode_local == 'propose':\n")
new_block.append(f"{indent}                target['status'] = 'done'\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            # write propose => proposed + proposal_id\n")
new_block.append(f"{indent}            if target and is_write and mode_local == 'propose':\n")
new_block.append(f"{indent}                pid = _extract_proposal_id()\n")
new_block.append(f"{indent}                if pid:\n")
new_block.append(f"{indent}                    target['status'] = 'proposed'\n")
new_block.append(f"{indent}                    target['proposal_id'] = pid\n")
new_block.append(f"{indent}                    target['required_approve'] = 'APPLY_' + pid\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            # write apply => done + clear proposal fields\n")
new_block.append(f"{indent}            if target and is_write and mode_local == 'apply':\n")
new_block.append(f"{indent}                target['status'] = 'done'\n")
new_block.append(f"{indent}                try:\n")
new_block.append(f"{indent}                    target.pop('required_approve', None)\n")
new_block.append(f"{indent}                    target.pop('proposal_id', None)\n")
new_block.append(f"{indent}                except Exception:\n")
new_block.append(f"{indent}                    pass\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            plan_disk['steps'] = steps_disk\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            # auto-complete if all done\n")
new_block.append(f"{indent}            try:\n")
new_block.append(f"{indent}                if steps_disk and all((str(x.get('status'))=='done') for x in steps_disk if isinstance(x, dict)):\n")
new_block.append(f"{indent}                    plan_disk['status'] = 'complete'\n")
new_block.append(f"{indent}            except Exception:\n")
new_block.append(f"{indent}                pass\n")
new_block.append(f"{indent}\n")
new_block.append(f"{indent}            _touch(plan_disk)\n")
new_block.append(f"{indent}            _save_plan_disk(room_id, plan_disk)\n")
new_block.append(f"{indent}except Exception:\n")
new_block.append(f"{indent}    pass\n")
new_block.append(f"{indent}{END}\n")

# Replace old block region by regex from BEGIN..END inclusive
txt2 = re.sub(
    r"(?s)^[ \t]*# === EXECUTE_STEP PERSIST PLAN \(FIX\) BEGIN ===.*?^[ \t]*# === EXECUTE_STEP PERSIST PLAN \(FIX\) END ===\n",
    "".join(new_block),
    txt,
    count=1,
    flags=re.MULTILINE
)

if txt2 == txt:
    raise SystemExit("No se aplicó el reemplazo (regex no matcheó).")

p.write_text(txt2, encoding="utf-8")
print("OK: Replaced EXECUTE_STEP PERSIST PLAN block with step-driven version")
