import type {Evidence,ProxySpec,ReviewerOutput} from "./types.js";import {GitHubBus} from "./github_bus.js";import {normalizeReviewerOutput,reviewIsConsistent} from "./review_contract.js";
export const REQUIRED_CHECKS=["Phase 1 baseline (Windows)","Brain Agent V2 Hygiene Baseline","Security Smoke Tests","Dashboard / Trace Tests","Memory / Retrieval Regression","Roadmap / Policy Regression","Agent V2 Boundary Contracts","Financial Autonomy Dry-Run Contract","Hygiene Guard"];
export function verifiedCommitChecks(bus:GitHubBus,head:string){
  const runs=bus.commitCheckRuns(head);const latest=new Map<string,any>();
  for(const run of runs){
    if(!Number.isInteger(run?.id)||run.id<1||run.head_sha!==head||typeof run.name!=="string"||!run.name||typeof run.status!=="string"||run.status==="completed"&&typeof run.conclusion!=="string"||run.status!=="completed"&&run.conclusion!==null&&typeof run.conclusion!=="string"||run.app?.slug!=="github-actions"||typeof run.details_url!=="string"||!/^https:\/\/github\.com\/cesarmanuel8102\/AI_Vault\/actions\/runs\/\d+\/job\/\d+$/.test(run.details_url))throw new Error("commit check receipt invalid");
    const prior=latest.get(run.name);if(!prior||run.id>prior.id)latest.set(run.name,run);
  }
  return [...latest.values()].map(run=>({name:run.name,status:String(run.status).toUpperCase(),conclusion:run.conclusion===null?"":String(run.conclusion).toUpperCase()}));
}
export function evaluateChecks(bus:GitHubBus,head:string,headBranch:string){const checks=verifiedCommitChecks(bus,head);const byName=new Map(checks.map((c:any)=>[c.name,c]));const required=REQUIRED_CHECKS.map(name=>byName.get(name));const allowedSkips=headBranch.startsWith("agent/pilot-")?new Set<string>():new Set(["deterministic","codex","publish"]);const terminal=checks.length>0&&checks.every((c:any)=>c.status==="COMPLETED");const green=terminal&&required.every((c:any)=>c?.status==="COMPLETED"&&c.conclusion==="SUCCESS")&&checks.every((c:any)=>c.conclusion==="SUCCESS"||(c.conclusion==="SKIPPED"&&allowedSkips.has(c.name)));return {checks,terminal,green};}
export function collect(bus:GitHubBus,issue:number,pr:number,reviewer:string,review:ReviewerOutput,spec:ProxySpec):Evidence{const p=bus.json(["pr","view",String(pr),"--json","baseRefOid,headRefOid,headRefName,baseRefName,isCrossRepository,mergeable,isDraft,state,author,files"]);review=normalizeReviewerOutput(review,p.headRefOid);const {terminal,green}=evaluateChecks(bus,p.headRefOid,p.headRefName);const files=p.files.map((x:any)=>x.path);let itemAuthorized=false;try{const manifest=JSON.parse(bus.fileAt("docs/roadmap/BRAIN_101_MANIFEST.json",p.baseRefOid));const item=manifest.roadmap_items?.[spec.roadmap_item_id];itemAuthorized=manifest.roadmap_id===spec.roadmap_id&&manifest.roadmap_version===spec.roadmap_version&&manifest.repository===spec.repository&&manifest.integration_branch===p.baseRefName&&manifest.approval_status==="HUMAN_ADOPTED"&&manifest.human_final_authority===true&&manifest.live_trading_enabled===false&&item?.status==="AUTHORIZED_ACTIVE";}catch{itemAuthorized=false;}const reviewBound=review.head_sha===p.headRefOid;const author=p.author?.login??"";return {issue,pr,base_sha:p.baseRefOid,head_sha:p.headRefOid,head_branch:p.headRefName,base_branch:p.baseRefName,author,state:p.state,draft:p.isDraft,from_fork:p.isCrossRepository,mergeable:p.mergeable==="MERGEABLE",checks_terminal:terminal,checks_green:green,deterministic_gate:green?"PASS":"FAIL",changed_files:files,sensitive_files:files.filter((f:string)=>/(\.env|secret|credential|memory\/semantic|faiss|trading|financial_autonomy|api_security)/i.test(f)),review:reviewBound?review.verdict:"BLOCKED",review_session:reviewer,builder_session:`github-builder:${author}:${p.headRefOid}`,item_authorized:itemAuthorized,review_p0:!reviewBound||review.findings.some(f=>f.severity==="P0"),review_p1:review.findings.some(f=>f.severity==="P1"),review_findings_count:review.findings.length,review_consistent:reviewBound&&reviewIsConsistent(review),repair_cycles:bus.repairCount(issue)};}
