import {execFileSync} from "node:child_process";
import type {EffectAssertion} from "./external_effect_guard.js";
import {redactedError,redactString} from "./redaction.js";

export class GitHubBus {
  private mutationGuard?:EffectAssertion;
  constructor(readonly gh="gh",readonly repo="cesarmanuel8102/AI_Vault"){}
  setMutationGuard(guard:EffectAssertion){this.mutationGuard=guard;}
  private guard(effect:Parameters<EffectAssertion>[0],context?:Parameters<EffectAssertion>[1]){if(!this.mutationGuard)throw new Error("GitHub mutation guard missing");this.mutationGuard(effect,context);}
  call(args:string[]){try{return execFileSync(this.gh,args,{encoding:"utf8",windowsHide:true,timeout:120000});}catch(error){throw new Error(redactedError(error));}}
  json(args:string[]){return JSON.parse(this.call([...args,"--repo",this.repo]));}
  queued(){return this.json(["issue","list","--state","open","--label","operator:queued","--json","number,title,body,labels"]);}
  branchHead(branch:string){return this.call(["api",`repos/${this.repo}/commits/${branch}`,"--jq",".sha"]).trim();}
  isAncestor(older:string,newer:string){if(!/^[0-9a-f]{40}$/.test(older)||!/^[0-9a-f]{40}$/.test(newer)||older===newer)return false;return this.call(["api",`repos/${this.repo}/compare/${older}...${newer}`,"--jq",".status"]).trim()==="ahead";}
  issuePaused(issue:number){const labels=this.json(["issue","view",String(issue),"--json","labels"]).labels??[];return labels.some((x:any)=>x.name==="operator:pause");}
  prIdentity(pr:number){return this.json(["pr","view",String(pr),"--json","author,baseRefName,baseRefOid,body,headRefName,headRefOid,headRepository,isCrossRepository,isDraft,state,mergeable"]);}
  findOpenFront(front:string){const issues=this.json(["issue","list","--state","open","--limit","1000","--json","number,body"]);return issues.filter((x:any)=>String(x.body??"").split(/\r?\n/).some(line=>line.trim()===`FRONT_ID: ${front}`)||String(x.body??"").includes(`\"front_id\": \"${front}\"`)).map((x:any)=>Number(x.number));}
  issueBody(issue:number){return String(this.json(["issue","view",String(issue),"--json","body"]).body??"");}
  replaceIssueBodyExact(issue:number,expected:string,replacement:string){if(this.issueBody(issue)!==expected)throw new Error("governed Issue changed before base reconciliation");this.guard("issue_modify",{issue});this.call(["issue","edit",String(issue),"--repo",this.repo,"--body",redactString(replacement)]);if(this.issueBody(issue)!==replacement)throw new Error("governed Issue base reconciliation readback failed");}
  issueSnapshot(issue:number){const value=this.json(["issue","view",String(issue),"--json","body,labels,state"]);return {state:String(value.state??""),body:String(value.body??""),labels:(value.labels??[]).map((x:any)=>String(x.name))};}
  findPrByBranch(branch:string){const prs=this.json(["pr","list","--state","open","--head",branch,"--json","number,headRefOid"]);if(prs.length>1)throw new Error("duplicate PRs for work branch");return prs.length===1?{number:Number(prs[0].number),head_sha:String(prs[0].headRefOid)}:undefined;}
  prCandidatesByBranch(branch:string){return this.json(["pr","list","--state","all","--limit","100","--head",branch,"--json","author,baseRefName,baseRefOid,headRefName,headRefOid,headRepository,isCrossRepository,isDraft,number,state"]);}
  remoteBranchHead(branch:string){try{const head=this.call(["api",`repos/${this.repo}/git/ref/heads/${branch}`,"--jq",".object.sha"]).trim();return /^[0-9a-f]{40}$/.test(head)?head:undefined;}catch{return undefined;}}
  createDraftPr(branch:string,base:string,title:string,body:string){this.guard("pr_create");const url=this.call(["pr","create","--repo",this.repo,"--draft","--head",branch,"--base",base,"--title",redactString(title),"--body",redactString(body)]).trim();const match=url.match(/\/pull\/(\d+)$/);if(!match)throw new Error("draft PR creation result invalid");return Number(match[1]);}
  createGovernedIssue(title:string,body:string,label="operator:building"){this.guard("issue_create");const url=this.call(["issue","create","--repo",this.repo,"--title",redactString(title),"--body",redactString(body),"--label",label]).trim();const match=url.match(/\/issues\/(\d+)$/);if(!match)throw new Error("governed Issue creation result invalid");return Number(match[1]);}
  bindPrToIssue(issue:number,pr:number){const data=this.json(["issue","view",String(issue),"--json","body"]);const marker=`OPERATOR_PROXY_PR: ${pr}`;if(String(data.body??"").includes(marker))return;if(/OPERATOR_PROXY_PR:\s*\d+/.test(String(data.body??"")))throw new Error("Issue already bound to another PR");this.guard("issue_modify",{issue,pr});this.call(["issue","edit",String(issue),"--repo",this.repo,"--body",redactString(`${String(data.body??"").trim()}\n\n${marker}\n`)]);}
  repairPrompt(issue:number){const comments=this.json(["issue","view",String(issue),"--json","comments"]).comments??[];const repair=comments.filter((c:any)=>String(c.body??"").includes("[OPERATOR-PROXY][REPAIR]")).at(-1);return redactString(String(repair?.body??""));}
  fileAt(path:string,ref:string){const raw=this.call(["api",`repos/${this.repo}/contents/${path}?ref=${ref}`,"--jq",".content"]);return Buffer.from(raw.replace(/\s/g,""),"base64").toString("utf8");}
  repairCount(issue:number){const comments=this.json(["issue","view",String(issue),"--json","comments"]).comments??[];return comments.filter((c:any)=>String(c.body??"").includes("[OPERATOR-PROXY][REPAIR]")).length;}
  hasComment(kind:"issue"|"pr",n:number,marker:string){const comments=this.json([kind,"view",String(n),"--json","comments"]).comments??[];return comments.some((c:any)=>String(c.body??"").split(/\r?\n/).some(line=>line.trim()===marker));}
  commentOnce(kind:"issue"|"pr",n:number,marker:string,body:string){if(this.hasComment(kind,n,marker))return false;if(kind==="issue")this.comment(n,body);else this.prComment(n,body);return true;}
  reconcileLabel(kind:"issue"|"pr",n:number,add:string,remove:string[]=[]){const labels=(this.json([kind,"view",String(n),"--json","labels"]).labels??[]).map((x:any)=>String(x.name));if(!labels.includes(add)){this.guard("label_modify",kind==="issue"?{issue:n}:{pr:n});this.call([kind,"edit",String(n),"--repo",this.repo,"--add-label",add]);}for(const old of remove)if(labels.includes(old)){this.guard("label_modify",kind==="issue"?{issue:n}:{pr:n});this.call([kind,"edit",String(n),"--repo",this.repo,"--remove-label",old]);}}
  comment(issue:number,body:string){this.guard("comment_publish",{issue});this.call(["issue","comment",String(issue),"--repo",this.repo,"--body",redactString(body)]);}
  prComment(pr:number,body:string){this.guard("comment_publish",{pr});this.call(["pr","comment",String(pr),"--repo",this.repo,"--body",redactString(body)]);}
  label(kind:"issue"|"pr",n:number,add:string,remove:string[]=[]){const context=kind==="issue"?{issue:n}:{pr:n};for(const old of remove){this.guard("label_modify",context);this.call([kind,"edit",String(n),"--repo",this.repo,"--remove-label",old]);}this.guard("label_modify",context);this.call([kind,"edit",String(n),"--repo",this.repo,"--add-label",add]);}
  verifyMerged(pr:number,head:string,base:string){const merged=this.json(["pr","view",String(pr),"--json","state,mergeCommit"]);const commit=String(merged.mergeCommit?.oid??"");if(merged.state!=="MERGED"||!/^[0-9a-f]{40}$/.test(commit))throw new Error("governed merge not confirmed");const parents=this.call(["api",`repos/${this.repo}/git/commits/${commit}`,"--jq",".parents[].sha"]).trim().split(/\s+/);if(parents.length!==2||parents[0]!==base||parents[1]!==head)throw new Error("governed merge parents mismatch");return commit;}
  merge(pr:number,head:string,base:string,decisionId:string){const meta=this.json(["pr","view",String(pr),"--json","baseRefName,baseRefOid,headRefOid,isDraft,state,mergeable"]);if(meta.baseRefName!=="codex/own-capital-sustainable-return"||meta.baseRefOid!==base||meta.headRefOid!==head||meta.isDraft!==true||meta.state!=="OPEN"||meta.mergeable!=="MERGEABLE")throw new Error("PR identity changed before merge dispatch");const title=`operator-proxy-merge-${decisionId}`;let runs=this.json(["run","list","--workflow","operator-proxy-merge.yml","--event","workflow_dispatch","--limit","100","--json","databaseId,displayTitle,status,conclusion"]);let matching=runs.filter((x:any)=>x.displayTitle===title);if(matching.length>1)throw new Error("duplicate governed merge workflows");if(!matching.length){this.guard("workflow_dispatch",{pr,expected_head:head});this.guard("merge",{pr,expected_head:head});this.call(["workflow","run","operator-proxy-merge.yml","--ref",meta.baseRefName,"-f",`decision_id=${decisionId}`,"-f",`pr=${pr}`,"-f",`expected_base=${base}`,"-f",`expected_head=${head}`,"-f","authorization_id=CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01","--repo",this.repo]);}let run:any=matching[0];for(let attempt=0;attempt<120;attempt++){runs=this.json(["run","list","--workflow","operator-proxy-merge.yml","--event","workflow_dispatch","--limit","100","--json","databaseId,displayTitle,status,conclusion"]);matching=runs.filter((x:any)=>x.displayTitle===title);if(matching.length>1)throw new Error("duplicate governed merge workflows");run=matching[0];if(run?.status==="completed")break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,5000);}if(!run||run.status!=="completed"||run.conclusion!=="success")throw new Error("governed merge workflow failed");return this.verifyMerged(pr,head,base);}
}
