import {createHash} from "node:crypto";import type {Decision,Evidence,ProxySpec} from "./types.js";import {classify} from "./risk_classifier.js";
export const AUTH="CESAR-BRAIN-101-OPERATOR-PROXY-20260722-01";export const REPO="cesarmanuel8102/AI_Vault";
export const POLICY="v1:exact-repo;active-item;stable-shas;green-ci;independent-review;allowlist;no-sensitive;no-fork;no-p0p1;merge-commit-only;human-escalation";
export const sha=(v:unknown)=>createHash("sha256").update(typeof v==="string"?v:JSON.stringify(v,Object.keys(v as object).sort())).digest("hex");
const pathMatches=(file:string,rule:string)=>rule.endsWith("/")?file.startsWith(rule):file===rule;
export function decide(spec:ProxySpec,e:Evidence):Decision {let pd:Decision["policy_decision"]="BLOCK", action:Decision["allowed_action"]="NONE";const risk=classify(spec);const scope=e.changed_files.length>0&&e.changed_files.every(f=>spec.allowed_paths.some(p=>pathMatches(f,p))&&!spec.forbidden_paths.some(p=>pathMatches(f,p)));const immutable=spec.authorization_id===AUTH&&spec.repository===REPO&&e.base_sha===spec.expected_base_sha&&e.base_branch==="codex/own-capital-sustainable-return";const independent=e.builder_session!==e.review_session;
 const trusted=e.author==="cesarmanuel8102"&&(e.head_branch.startsWith("control-plane/")||e.head_branch.startsWith("agent/pilot-"))&&e.state==="OPEN"&&e.draft;const admissible=immutable&&trusted&&e.item_authorized&&scope&&!e.from_fork&&e.sensitive_files.length===0;
 if(risk==="HIGH"||risk==="CRITICAL")pd="ESCALATE_TO_OWNER";else if(admissible&&e.review_consistent&&e.review==="CHANGES_REQUESTED"&&e.review_findings_count>0&&!e.review_p0_p1&&e.repair_cycles<2){pd="REPAIR";action="REQUEST_REPAIR";}else if(admissible&&e.mergeable&&e.checks_terminal&&e.checks_green&&e.deterministic_gate==="PASS"&&e.review_consistent&&e.review==="PASS"&&e.review_findings_count===0&&independent&&!e.review_p0_p1){pd="APPROVE";action="MERGE";}
 return {schema_version:1,decision_id:crypto.randomUUID(),authorization_id:spec.authorization_id,repository:spec.repository,issue:e.issue,pr:e.pr,base_sha:e.base_sha,head_sha:e.head_sha,roadmap_id:spec.roadmap_id,roadmap_item_id:spec.roadmap_item_id,risk,deterministic_gate:e.deterministic_gate,codex_review:e.review,review_findings_count:e.review_findings_count,review_consistent:e.review_consistent,policy_decision:pd,allowed_action:action,policy_sha256:sha(POLICY),evidence_sha256:sha(e),created_utc:new Date().toISOString()};}
